### ISSUE TITLE
R&D: Where do adapter macros live? (filesystem & namespaces both)

### ISSUE THREAD

**Issue by cmcarthur** [fishtown-analytics/dbt#1069]

**Comment by beckjake** [comment]
My current plan for this based on some experimentation:
 - Make `dbt.include` a python namespace package in core and all plugins, just like `dbt.adapters`
 - Make `global_project` also a python package (by adding an `__init__.py`), and move the path-information currently in `dbt/include/__init__.py` into that.
 - Plugins currently have `dbt.adapters.${plugin_name}`, add `dbt.include.${plugin_name}`, and have plugins import their global project and attach path information to the adapter.
 - Update `ref` to look through all registered adapter projects instead of just the global project
     - ref can't just search the currently active adapter project, because redshift macros sometimes depend upon postgres macros.

There's probably some light refactoring to do on the plugin/plugin registration front in light of this.
