### ISSUE TITLE
dbt init should be able to create a project in the current directory

### ISSUE THREAD

**Issue by tconbeer** [fishtown-analytics/dbt#1121]
## Feature
`dbt_init` should be able to create a project in the current directory

### Feature description
Sometimes its's helpful to create a new dbt project in the current directory, rather than in a new directory. One example is when using dbt with pipenv. Ideally this sequence of commands would install dbt from scratch in a virtual environment, and then create a dbt project in that same directory:
```
> mkdir dbt\my-dbt-project
> cd my-dbt-project
> pipenv install dbt
> pipenv run dbt init
```
If dbt needs a project name, it could take it from the path or take a different argument to override the default "create a directory" behavior
`> pipenv run dbt init my-dbt-project --current-directory`

### Who will this benefit?
People creating a new dbt project who plan on collaborating and require specific dbt versions to be installed across multiple machines.

**Comment by drewbanin** [comment]
this is a reasonable idea, but I don't think it's something we're going to prioritize any time soon. Closing, but we can re-open if anyone feels strongly

**Comment by thomashandorf** [comment]
this is bugging me for some time. It different from the semantics of other tools. E.g. 'git init' . It would be event great if it would ask in the first step to take the current directory or a subdirectory

**Comment by jtcohen6** [comment]
More recent issue proposing something similar: https://github.com/dbt-labs/dbt-core/issues/4141

I'm not strictly opposed, if lots of folks want this

**Comment by thomashandorf** [comment]
Great to hear. I often have the workflow: create repo on github, clone repo to local, try to init dbt - damn ;)

**Comment by schlich** [comment]
I think this should be supported in the CLI.  The current instructions are a pain if you'd like to use dbt's root-level configuration without using the dbt tool to bootstrap a project.  For example, I use `poetry new` to bootstrap my python projects and it makes much more sense to handle the installation of dbt first with poetry and configure the dbt config second.  I shouldn't have to need `mv` for what others have mentioned is a basic cli option in many tools (git was mentioned, but also see `poetry init` vs `poetry new`).

**Comment by emilyriederer** [comment]
Upvoting this for the same use case as @schlich . I've been experimenting with switching to `poetry` for virtual environment management with dbt. Currently, it feels a bit clumsy to need the last two lines in:

```
poetry init
poetry add dbt-core
poetry add dbt-duckdb
dbt init 
cp -r dbt_demo/* .
rm -rf dbt_demo
```

**Comment by schlich** [comment]
@emilyriederer i'd still like to see first class support for this feature (particularly I think there are some details around getting the name of the profiles/paths right that need to be considered) but just as an FYI your workaround can be shortened to one line instead of two by using `mv` instead of `cp` 🙂

**Comment by matthias-fbi** [comment]
Any updates on this?

I create a folder with an `.venv` inside, install dbt + connector and then try to run `dbt init` -> "A project called test_dbt already exists here"

But I need a `.venv` first to run `dbt init` in the first place but then can't run `dbt init` because of that .... ?!

**Comment by pxlhuntr** [comment]
@matthias-fbi That's exactly what brought me here! +1 for this, I thought I was crazy but glad to see I'm not alone in this.

**Comment by zheacker** [comment]
Adding to this chorus, I'm also using uv and I'm trying to roll dlt, dbt, and dagster into a single project, and it would be a bit easier if this was supported.

**Comment by gdubya** [comment]
@zheacker ditto!

**Comment by brian-equilife** [comment]
Same issue here.

**Comment by antonpious** [comment]
I would like to re-consider this option specially with the virtual environment setup.

The dbt-core is installed only in the context of the virtual environment.

The expectation of dbt init is to use the current directory instead of another directory within in.

This way the flow for git is correct
1. A repo is created for the project
2. The repo is cloned on the local
3. virtual environment is setup  and activated
4. dbt-core is installed
5. dbt init to get the folder structure
6. check-in dbt project


The current work around to create the same folder name as the parent name and to move file back to the parent directory is painful.

The dbt init specifying the dbt_project.yml is also not working as expected as it doesn't recreate the folder structure but only verifies the connection profile.
