### ISSUE TITLE
Provide test name and kwargs in test nodes in the manifest

### ISSUE THREAD

**Issue by foundinblank** [fishtown-analytics/dbt#1154]
### Feature description
In the documentation website, the columns box shows three different types of built-in schema tests: P, U, N (primary key, unique, not_null). But not for the fourth built-in schema test, `accepted_values`. It also doesn't show any custom schema tests. 

### Who will this benefit?
Anyone who uses `accepted_values` and was expecting to see it in their docs site! For custom schema tests, a single letter would need to be defined...or just stuff the name of it into the Tests column. 🙂 

Link to code: https://github.com/fishtown-analytics/dbt-docs/blob/master/src/app/docs/model.html#L126-L134

**Comment by drewbanin** [comment]
This is prioritized for our Wilt Chamberlain release.

If you want to feel sad, have a look at [the code responsible for rendering column tests](https://github.com/fishtown-analytics/dbt-docs/blob/master/src/app/services/project_service.js#L168-L208) in the docs site. The docs site needs to parse test attributes out of generated test names because dbt is not currently encoding this information in the manifest in a structured way.

In order to delete all of this code, as well as support accepted_values tests, we should add a structured dict to `test` nodes with the following information:
1. the name of the test macro
2. the arguments supplied to the test macro (represented as a dictionary)

The docs site is going to need to semantically know what `unique`, `not_null`, etc mean, but I think that's acceptable for now.

In the future, I'd like to make schema tests capable of generating their own descriptions. This would help us render custom schema test information in the docs site. Out of scope for this particular issue, but worth keeping in mind.

**Comment by drewbanin** [comment]
Kicking this out of Wilt Chamberlain and into Louisa May Alcott

**Comment by drewbanin** [comment]
fyi the corresponding fix for this in the autogenerated docs site was merged and will be live in 0.15.0

Thanks for the initial request - hope you're doing well @foundinblank :)
