### ISSUE TITLE
Support dynamic configuration of model databases

### ISSUE THREAD

**Issue by drewbanin** [fishtown-analytics/dbt#1183]
### Feature description
dbt has historically only supported a single database as the destination for models. This comes from a Redshift-centric worldview, in which reading/writing data across databases is not supported. With Snowflake, BigQuery, and Presto, cross-database reads/writes are indeed supported, and frequently very useful.

 dbt should support the dynamic configuration of model databases, as it current does with `schemas` and `aliases`. Though different adapters use different terminology for databases, dbt should only accept the config value `database`.

### Example usage:

**models/something.sql**
```
{{ config(database='dev') }}

select * from somedb.someschema.sometable
```

Assuming a profile config:
```
database: analytics
schema: dbt_drew
```

dbt will build the relation:
```
dev.dbt_drew.something
```

### Example dbt_project.yml usage
```yml
models:
  my_project:
    postgres:
      database: postgres
      ....
```

### Implementation Details
On Snowflake and BigQuery, I think dbt can get away with just writing:
```sql
create table database.schema.identifier as (
   ...
)
```

On databases like Presto, dbt may instead need to issue a `use {catalog}` query (or similar) in order to create the relation in the appropriate catalog. Further investigation is required to determine the exact syntax that is required.

In the general case, dbt shouldn't try too hard to restrict users from performing invalid operations. While there is generally little use for custom databases on Redshift, dbt should allow the user to use custom databases and then return an error message from the database accordingly. We can definitely document this, but support for cross-db queries is pretty varied, and the database will always do a better job of generating error messages than we will.

### Who will this benefit?
Snowflake, BigQuery, Presto users

**Comment by beckjake** [comment]
A couple questions as I start to dive into this:

1) On BigQuery, we already support "projects" in some ways, right? Is that their version of "database"? If so, should bigquery keep calling it "projects" throughout? This is mostly going to be a thing about flipping the "include policy" to `true`.

Maybe we should define some consistent names for internal-to-dbt use and a formal map of aliases or whatever that we maintain so users can give consistent behavior. Maybe adapter plugins could define their own aliases for the "canonical names" and dbt could automatically handle it?

2) regarding this bit:

>While there is generally little use for custom databases on Redshift, dbt should allow the user to use custom databases and then return an error message from the database accordingly.

Does this mean we should issue the `database.schema.identifier` syntax on Redshift if it's specified (and I guess flip the include_policy flag at that point), or that we should open a new connection to the database with the new database field? I would expect dbt to try to connect to the new database and issue the command there, since Redshift does have a concept with that name. Or I would expect an error.

**Comment by drewbanin** [comment]
@beckjake you're totally right - BigQuery's "projects" map to dbt's general notion of "databases". I like the idea of aliasing these configs in the adapters. On BQ for instance, schemas are actually called "datasets". This leads to a nonzero amount of confusion, and it would be good to let people specify a `dataset` config instead of a `schema` config on BigQuery. Historically, my fear is that the code would become a mess if we tried to do this, but if you can divine a good mechanism for doing this, then i'm into it! 

I think aliasing profile configs like database/schema is super appropriate, but I definitely _do not_ want to implement our own nomenclature for table-level configs. There is some overlap between:
Redshift: sort/dist keys
Snowflake: clustering keys
BigQuery: clustering keys / table partitioning

It sounds to me like each database will require its own database/connection logic. On Snowflake, you can connect to any database you want, then execute queries against a different database. Here, I connected to `dbt_test`:
```
create schema dbt_test_2.debug;
create table dbt_test_2.debug.new_table as (select 1 as id);
select * from dbt_test_2.debug.new_table;
```

^ That definitely doesn't work on Redshift, and I'm unsure how well it's supported on other databases (eg. Presto). I imagine it will be much simpler to connect to a single database, then execute queries against a different database using the `database.schema.identifier` syntax when possible. If dbt did make a new connection for each distinct database, I imagine our connection pooling code would become a lot more complicated :)

I think to start, dbt should just connect to the database specified in the profile, then use `database.schema.identifier` everywhere. This will break for cross-db queries on Redshift, and that's a-ok with me. I _think_ it will work with Snowflake/BQ/(+Presto?), which is where this feature is really useful.

I'm still clarifying my own thoughts here, so happy to follow up if any of this doesn't make sense!

**Comment by beckjake** [comment]
In Presto, to my knowledge, you do not connect to a specific catalog at all. You can `use {catalog}.{schema}` during a connection to switch the "active" catalog/schema, but the syntax you outlined above on snowflake will work fine. I do not understand at all how Presto chooses the default catalog/schema, but I can tell you that it seems to be 'hive' even if you don't have a connector with that name configured!

When you say this:

```
I think to start, dbt should just connect to the database specified in the profile, then use database.schema.identifier everywhere. This will break for cross-db queries on Redshift, and that's a-ok with me. I think it will work with Snowflake/BQ/(+Presto?), which is where this feature is really useful.
```

How do you see redshift/postgres' `dbname` interacting with the `database` config? Does `database` just override it? Same goes for the bigquery `project` thing. One thing I feel this issue is missing is how profile configs should interact with configurations.

**Comment by drewbanin** [comment]
yeah, great question. Let me carve out some time to look through all of the existing configs in dbt and build out the mapping. I imagine that each adapter can supply accepted aliases for profile configs, but it would be an error to supply a value for one of these configurations with > 1 alias. Will follow up here shortly!

**Comment by cmcarthur** [comment]
> I think it will work with Snowflake/BQ/(+Presto?),
+ Postgres

> Maybe we should define some consistent names for internal-to-dbt use and a formal map of aliases or whatever that we maintain so users can give consistent behavior.

Love this idea. Though I would be in favor of soft deprecating `dbname` for now and eventually getting rid of it. `project` and `catalog` are less clear, because those are meaningful in the context of those adapters.

**Comment by beckjake** [comment]
Ok, thanks for the clarifications! I think since in the adapters as plugins world we basically make the plugin responsible for deciding how to parse its configs, this will come out pretty clean on the profile front - the plugin already has control of that since it provides its own credentials class+json schema.

**Comment by crunkilton** [comment]
Apologies for reopening a closed issue, but I'm not sure that this works if you specify a database in your `profiles.yml` file - if I set up my dbt_project.yml file like so:

models:
  dwh:
    folder:
      +database: DIFFERENT_DB_FROM_PROFILES_YML_FILE

`dbt run` gives an error:
"Schema '<PROFILES_DB>.SCHEMA' does not exist or not authorized."

Interestingly, this seems to actually succeed - the correct table (DIFFERENT_DB.SCHEMA.MODEL_TABLE) does get updated in Snowflake when I run this - but DBT is telling me it fails and triggers all the associated alerts I have set up.

Entirely possible this is user error on my part - does anyone know how this is supposed to work? Or, any workarounds so a single DBT project can write to multiple databases?

**Comment by jtcohen6** [comment]
@crunkilton Looking at the [Slack thread](https://getdbt.slack.com/archives/C0VLZPLAE/p1616632850180200?thread_ts=1616620122.179000&cid=C0VLZPLAE) from last week, it looks like you found the resolution?

> figured this out, for anyone in the future who comes across this: if you are using any post hooks, make sure that if you do a grant usage on `{{this.schema}}` you change that to grant usage on `{{this.database}}.{{this.schema}}` - `{{this.schema}}` will append the incorrect database and cause errors

Another tool available: the special `{{ database_schemas }}` Jinja variable, available in the [on-run-end context](https://docs.getdbt.com/reference/dbt-jinja-functions/on-run-end-context#database_schemas). This is relevant if you're granting permissions in an end-of-project `on-run-end` hook, rather than a post-hook following each model.
