### ISSUE TITLE
DBT archive performance improvement

### ISSUE THREAD

**Issue by afka2d** [fishtown-analytics/dbt#1294]
### Feature description
DBT archive works as desired, but performance is slower than desired. 
Right now dbt archive takes just as long to run every subsequent time it is run on a table as the first time it runs on the table. This is because even though dbt archive is only inserting incremental row changes, it is scanning through the full table and comparing the full table against itself instead of only unioning the incremental changes

https://github.com/fishtown-analytics/dbt/blob/development/dbt/include/global_project/macros/materializations/archive/archive.sql

### Who will this benefit?
everyone. especially if you want to invoke dbt archive on large tables

**Comment by drewbanin** [comment]
Thanks for the report @afka2d! Have you checked out the code already? What kinds of changes would you recommend that we make here?

**Comment by afka2d** [comment]
I think it is related to the way the insertions cte is done here: https://github.com/fishtown-analytics/dbt/blob/development/dbt/include/global_project/macros/materializations/archive/archive.sql#L120. The idea is that we don't always need this from statement to refer to `current_data`. I'm hoping it's possible to use something like the {% if is_incremental() %} so that if this is not the first time archive is invoked we only join the changed rows to archived data.

**Comment by drewbanin** [comment]
In the code that you linked to, `current_data` represents the source data table. The `insertions` CTE works by joining from the source table to the archive table in order to determine when source records have been overwritten with data that's newer than the corresponding version in the archive table.

I suppose it's possible to add a filter to the `insertions` CTE like:
```
        select
            current_data.*,
            {{ timestamp_column.literal('null') }} as {{ adapter.quote('valid_to') }}
        from current_data
        left outer join archived_data
          on archived_data.{{ adapter.quote('dbt_pk') }} = current_data.{{ adapter.quote('dbt_pk') }}
        where archived_data.{{ adapter.quote('dbt_pk') }} is null or (
          archived_data.{{ adapter.quote('dbt_pk') }} is not null and
          current_data.{{ adapter.quote('dbt_updated_at') }} > archived_data.{{ adapter.quote('dbt_updated_at') }} and
          archived_data.{{ adapter.quote('tmp_valid_to') }} is null
        )
        -- This is new:
        and current_data.{{ adapter.quote('dbt_updated_at') }} > (select max(valid_to) from {{ this }})
```

This additional filter would only consider records that are _newer_ than the newest record in the archive table. I'd have to think harder about if this is valid logic for archival (it's a complicated query!) but I suppose this could indeed speed up your queries.

What kind of warehouse are you using? I'd be curious if the addition of sort/dist keys, table partitioning, etc, would measurably archive improve performance for you.

**Comment by afka2d** [comment]
yeah, we're using redshift, so specifying sort/dist keys could help I think, but our source data table is >1.5B rows so preventing this whole table from being reloaded every time we run the query would significantly improve the performance. Right now `dbt archive` takes a half hr to run, but if we can instead just insert incremental changes to the existing table we're hoping we can get this run time down significantly.

**Comment by drewbanin** [comment]
Hey @afka2d - I'm going to close out this issue. We've revamped archives as "snapshots" and added some more functionality around this feature coming in dbt v0.14.0.

If this process is indeed too slow for your needs, i'd recommend generating change events upstream if possible. That's always going to be the best solution to this class of problem! Thanks for opening this issue, and feel free to follow up if this is still something you're thinking about :)
