### ISSUE TITLE
Caching INFORMATION_SCHEMA request resultsets

### ISSUE THREAD

**Issue by fetanchaud** [fishtown-analytics/dbt#1322]
## Feature

Caching INFORMATION_SCHEMA requests to speed up Adapter function calls.

### Feature description

From what I understand, model's SQL are all parsed and built at startup. 
While this is preventing us from cascading model definition changes (imagine a new column was added in a source table, that could be added in cascade all along the models' hierarchy),
it has a benefit : INFORMATION_SCHEMA requests could be cached for reuse in Adapter function calls.

### Who will this benefit?

All dynamic models users.

**Comment by drewbanin** [comment]
Hey @fetanchaud - not sure I totally understand what you're looking for here.

dbt currently caches (most) information_schema queries during _compilation_. We have an open issue to cache these queries [during parsing](https://github.com/fishtown-analytics/dbt/issues/1306) too, which should generally speed up dbt build times.

The following types of queries are _currently_ cached:
 - existence for relations (eg. `information_schema.tables`)

The following types of queries are not currently cached:
 - the columns in a relation
 - user-specified queries (ie. `statements`) 

Can you provide a little more information about which types of queries you think dbt should be caching? Or maybe better stated: what's the actual change you'd like to see here? Do you want your dbt runs to be faster? Or to reduce the query load on the database? Or something else?

Thanks!

**Comment by fetanchaud** [comment]
Here is our current use case : 

We wrote a fully dynamic incremental model in jinja.
The .sql consists of a single call to a jinja macro.

This model implements a so called persistent staging area table, based on a source table : 
- all the columns of the source table + load timestamp (run_started_at) + hash of non PK columns
- PK = source table PK + load timestamp

By left outer joining on the source table, we can use an insert-only strategy to load only new or updated rows in incremental mode.

By comparing model and source definitions, we can propagate source definition changes to the model : 
- add new columns at the end of the model
- substitue null to dropped columns in select clause
- keep the hash values stable among all row versions

But this requires to emit the same calls to the adapter's functions in pre-hook, model, and pos-hook.
As we currently work on premise with postgres, we have no pay as you go problems, maybe only performance issues.
So we are wondering if there is a way to cache requests, to reuse resultsets at different stages : pre_hook, model and post_hook. Maybe a jinja solution with shared variables ?

Is there any documentation online on the way dbt works ? I still have to understand differences between compilation, parsing, execution...

Thank you again !

**Comment by drewbanin** [comment]
Thanks for the additional info @fetanchaud! I'd have to think hard about whether or not dbt can effectively cache the introspective queries made by adapter functions like `get_columns_in_table()`. I do however think there's merit to making some sort of global cache that can be populated by models.

With this approach you could make a macro that looks like:
```
{% macro get_something(table) %}
  {% if cache.get(table) %}
   {{ return(cache[table]) }}
  {% endif %}

  ... expensive queries here...
{% endif %}
```

Your use of pre- and post- hooks is noteworthy to me! These hooks are predominately meant for things like running `grant` statements when models finish running. Are you able to share some of your example code? This would help me understand if there's an alternative way of accomplishing your goals, or maybe some other type of feature that can make a workflow like this more natural.

**Comment by fetanchaud** [comment]
Yes, here are examples, where schema.table is the aforementioned source table : 

```jinja
{%- macro stg_pre_hook(schema, table) -%}
    {%- if is_incremental() -%}
        {%- set altered_type_columns = altered_type_columns(adapter.get_columns_in_table(schema, table), adapter.get_columns_in_table(this.schema, this.table)) -%}
        {%- if altered_type_columns | length > 0 -%}
            {{ exceptions.raise_compiler_error("Source table has altered column(s) of incompatible type : " ~(altered_type_columns | string)) }}
        {%- endif -%}
        {%- set source_pk_colnames = get_pk_colnames(schema, table) -%}    
        {%- set model_pk_colnames = get_pk_colnames(this.schema, this.table) | reject('eq', var('load_dts_colname')) | list -%}
        {%- if source_pk_colnames | length != model_pk_colnames | length 
                or source_pk_colnames | reject('in', model_pk_colnames) | list | length > 0 -%}
            {{ exceptions.raise_compiler_error("Source table primary key has changed.") }}
        {%- endif -%}
        {% set added_columns = adapter.get_missing_columns(schema, table, this.schema, this.table) %}
        {% if added_columns | length > 0 %}
            {{ log("Source table has new column(s) : " ~ (added_columns | string), info=True) }}
            {%- for added_column in added_columns -%}
                alter table {{this}} add column {{added_column.name}} {{added_column.data_type}}
            {%- endfor -%}
        {% else %}
            select 1
        {% endif %}
    {% else %}
        select 1        
    {%- endif -%}
{%- endmacro -%}

{%- macro stg_post_hook(schema, table) -%}
    {%- if not is_incremental() -%} 
        alter table {{this}} add primary key({{ (get_pk_colnames(schema, table) + [ var('load_dts_colname')]) | join(', ') }});
    {% else %}
        select 1
    {% endif %}
{%- endmacro -%} ```

As you can see, there are the same calls in both hooks (here, get_pk_colnames), and also in the dynamic model definition.

So model and source table Columns may be asked three times.

Am I right saying that : 
- models are evaluated together at startup
- dynamic pre and post hooks are evaluated and executed before and after the model sql execution ?

As in our use case we are altering the models, we have to know when these modifications happens.

Thank you !

**Comment by drewbanin** [comment]
Ok, thanks for sending this over! It took me a while to digest this, but I think I have a good handle on what you're looking to accomplish.

To answer your questions:
**Are models are evaluated together at startup?**
dbt has two discrete steps: parsing, and running. In parsing, dbt will inspects all of the resources in your project (models, tests, macros, etc) and finds any `ref` calls. From calls to the `ref()` function, dbt can build the dependency graph for your project. Once parsing is complete, dbt runs your project with any provided configuration (eg. `--models` selectors).

In order for dbt to find _all_ of the `ref()` calls in a model, it needs to evaluate all of the models/tests/macros/etc (we call these things "resources"). You can imagine someone writing a model like:
```

{% for table in adapter.list_relations("salesforce") %}
select * from {{ ref(table) }} union all ...
{% endfor %}
```

Writing models like this is an anti-pattern to be sure, but dbt lacks the ability to know that `list_relations` is a method that invokes a database query. As a result, dbt needs to execute a query in order to correctly _parse the ref functions_ out of this model!

When dbt moves onto parsing, it will compile this model code again. There's a good reason for this, but suffice it to say: dbt needs to evaluate this model twice: once during parsing and once during when it runs the model.

**Are pre and post hooks are evaluated and executed before and after the model sql execution?**

dbt's pre- and post- hooks were originally intended for use with simple `grant ...` statements. As such, they work in a sort of unusual way, and we haven't gone back and fixed them yet. Increasingly, I think now is a good time to make them work correctly!

In short, the problem with hooks is that they are evaluated and stored at parse-time, but then executed at run-time. Given your `stg_post_hook` macro example, I imagine you are calling it with something like:

```
{{
  config(post_hook=stg_post_hook(this.schema, this.table))
}}
```

The problem with this approach is that dbt doesn't know that you want your post-hook to be "call the stg_post_hook macro with `this` as the arguments". Instead, when dbt parses this whole block, it evaluates to something like:
```
config(post_hook="select 1")
```

In the process of calling the `config()` function, dbt has no choice but to also evaluate the expression `stg_post_hook(this.schema, this.table)`. The terrible, not good workaround is to _defer_ the execution of this hook until runtime, and you can do that by putting this hook inside of a jinja string. That looks like:
```
{{
  config(post_hook="{{ stg_post_hook(this.schema, this.table) }}")
}}
```

This isn't ideal, but dbt will not interpolate the string when calling `config()`, but _will_ interpolate that hook at run-time.

------

Ok, so, caching the information_schema. I think the operative issue there is this one: https://github.com/fishtown-analytics/dbt/issues/1306. That said, I don't think you actually want these queries to be cached given that you're modifying the tables (and invalidating the cache!) as a part of your hooks.

Have you considered making a [custom materialization](https://docs.getdbt.com/docs/creating-new-materializations) to implement the logic you're describing here? Pre- and post- hooks are _really_ not well suited for this use case. I'd poke around in some of our existing materializations. You can just copy one of these, modify it to suit your needs, and then drop it in your `macros/` directory to use it in your project. Here's an example to get you started: https://github.com/fishtown-analytics/dbt/blob/dev/stephen-girard/core/dbt/include/global_project/macros/materializations/incremental/incremental.sql

The benefit of using a materialization is that you don't need to "cache" query results from pre-hooks to the model and into post-hooks. Instead, you can just define all of the logic you need in one place. If you want to manage the columns in your table manually, you can see how we do something similar in the [archival materialization](https://github.com/fishtown-analytics/dbt/blob/dev/stephen-girard/core/dbt/include/global_project/macros/materializations/archive/archive.sql#L174-L179).

This was a lot of info! I tried to answer all of the questions you asked, and some of the ones you didn't ;) 

Let me know if you buy any of this, happy to point you in the right direction if you decide to pursue a materialization

**Comment by fetanchaud** [comment]
Hi @drewbanin,
Thank you very much for all these informations !

Fridthjof-G Eriksen in 

https://discourse.getdbt.com/t/implementing-a-persistent-staging-area-with-a-dynamic-incremental-model/252

also suggested that materializations are the way to go. I am going to translate the PSA model.

Roelant Vos' work (http://roelantvos.com/blog/) gave me the idea to implement the PSA with DBT.
IMHO there are a lot of informations in that site on EDWH virtualization.
