### ISSUE TITLE
Issue: Mysterious macro compilation error using postgres connector

### ISSUE THREAD

**Issue by mikekaminsky** [fishtown-analytics/dbt#1382]
### Issue description
I'm getting a difficult-to-parse error running `dbt run` in my dbt demo repo that I normally use for testing.  It works great with version `0.12.2` but fails with the following error on `0.13.0`:

```
dbt run
Running with dbt=0.13.0
Found 4 models, 0 tests, 1 archives, 0 analyses, 94 macros, 0 operations, 0 seed files, 0 sources

Encountered an error:
Compilation Error in macro statement (macros/core.sql)
  exception_handler() takes 2 positional arguments but 3 were given

  > in macro postgres__list_relations_without_caching (macros/adapters.sql)
  > called by macro adapter_macro (macros/adapters/common.sql)
  > called by macro list_relations_without_caching (macros/adapters/common.sql)
  > called by macro statement (macros/core.sql)
``` 

### System information
The output of `dbt --version`:
```
$dbt --version
installed version: 0.13.0
   latest version: 0.13.0

Up to date!
```

The operating system you're running on: macos

The python version you're using (probably the output of `python --version`)
`Python 3.7.2`

### Steps to reproduce
I was trying to run dbt on the local repo I often use for testing dbt (I've pushed up the [code here](https://github.com/mikekaminsky/dbt-issue-1382))

It runs dbt against a local postgres database (I suspect there's an issue with the postgres adapater).

**Comment by mikekaminsky** [comment]
I'll also note that when I run my tests for `dbt-helper` (which also uses a postgres backend) I _do not_ get this error so I'm sort of at a loss for what might be going on here :(

**Comment by beckjake** [comment]
We had a call on this - I believe it was caused by some combination of `dbt` being installed in develop mode and upgrading from 0.12.2 to 0.13.0 via `git pull`, and re-installing, or something! Python appeared to be picking up dbt from places it did not belong and cleaning up `site-packages` manually didn't help. The end result was we fixed it by resetting the virtualenv. I saw a mix of `dbt-core` as an `egg-link` and `dbt` as a folder with `adapters` in it. I think this is basically similar to the `mod.Plugin` `AttributeError` we've seen come up in slack a few times with dbt upgrades going poorly.
