### ISSUE TITLE
docs in Snowflake: "Certificate attached to OCSP response is invalid"

### ISSUE THREAD

**Issue by jtcohen6** [fishtown-analytics/dbt#1404]
### Issue description

Not sure if this belongs here or in dbt-docs. When trying to run `dbt docs generate` on Snowflake, I'm getting the following error:

```
Running with dbt=0.13.0
Found 47 models, 0 tests, 0 archives, 0 analyses, 194 macros, 1 operations, 1 seed files, 1 sources

11:05:31 | Concurrency: 8 threads (target='dev')
11:05:31 |
11:06:47 | Done.
11:06:48 | Building catalog
Encountered an error:
254010: None: Certificate attached to OCSP response is invalid. OCSP response current time - 2019-04-17 15:07:08.666506+00:00 certificate not before time - 2018-04-17 12:15:42+00:00 certificate not after time - 2019-04-17 12:15:42+00:00 for sfc-ds1-customer-stage.s3.amazonaws.com
```

I wonder if it is related to a [relatively recent change](https://github.com/snowflakedb/snowflake-connector-python/commit/0df9da1eea62b1130a1554e08880a6a538c07ef2) to Snowflake's python connector.

### System information
The output of `dbt --version`:
```
installed version: 0.13.0
   latest version: 0.13.0

Up to date!
```

**Comment by beckjake** [comment]
Well, since it is currently April 17th at 15:15 UTC, it looks to me like snowflake is responding with an invalid certificate (expired 3h ago), and recently added a check to make sure their certificates were valid. Those are mutually incompatible choices!

Does downgrading to `snowflake-connector-python` to `1.6.12` fix it?

**Comment by braunreyes** [comment]
Turned out they have an open issue with certificate issues with Python 2 version of connector.

https://github.com/snowflakedb/snowflake-connector-python/issues/59

I had same issue today.

I think I may have installed dbt on python2 on my Macbook.  Once I did pip3 install dbt...everything worked fine
