### ISSUE TITLE
Investigate why Snowflake integration tests are so slow

### ISSUE THREAD

**Issue by cmcarthur** [fishtown-analytics/dbt#1433]

**Comment by beckjake** [comment]
I looked over some logs from before drew dropped all the test databases and rebuilt them vs after.

Before, the full snowflake suite took [almost 4 hours](https://circleci.com/gh/fishtown-analytics/dbt/12230#artifacts/containers/0). After, it took [a bit over 30 minutes](https://circleci.com/gh/fishtown-analytics/dbt/12325#artifacts/containers/0).

The problem in snowflake is that over time something happens to a database where certain information_schema queries become extremely slow. One interesting fact is that queries to the `information_schema.schemata` view appear to stay around the same speed throughout. Both of these queries didn't have any significant change between the two runs:

 - ```select count(*)
      from CIRCLE_TEST.information_schema.schemata
      where upper(schema_name) = upper('TEST15568098360309_SIMPLE_ARCHIVE_004')
          and upper(catalog_name) = upper('CIRCLE_TEST');```
 - ```select distinct schema_name
    from CIRCLE_TEST.information_schema.schemata
    where catalog_name='CIRCLE_TEST';```

But these queries both saw wild swings:

 - ```select
      table_catalog as database,
      table_name as name,
      table_schema as schema,
      case when table_type = 'BASE TABLE' then 'table'
           when table_type = 'VIEW' then 'view'
           else table_type
      end as table_type
    from CIRCLE_TEST.information_schema.tables
    where table_schema ilike 'test15568098360309_simple_archive_004'
      and table_catalog ilike 'circle_test';```
 - ```select
          column_name,
          data_type,
          character_maximum_length,
          numeric_precision,
          numeric_scale
      from
      information_schema.columns
      where table_name ilike 'archive_actual_dbt_archival_view_tmp'        
      order by ordinal_position;```

Maybe next time the database gets really slow we can drop... cascade all the schemas in the database instead of just dropping the database, and see if that fixes it. That would be an interesting data point. Or perform some of the slow queries without all the filters, to see if there's extra data in that that we don't expect.

**Comment by cmcarthur** [comment]
- Combine tests (remove simple test cases?)
- Look into creating fast schema inspection methods for test purposes only

**Comment by beckjake** [comment]
The "simple copy" cases in snowflake are mostly testing weird quoting/casing configurations. It doesn't seem like anything else in the integration suite really covers all those crazy settings, and I have broken those settings more than once myself - I think we should leave them in.

I'd feel good about removing them if we added some "unit" tests that actually do the full rendering process for snowflake - I have to think about that some more, but this idea has been bouncing around in my head for a while, some sort of test level between unit/integration that tests inputs/outputs of the rendering stack with mocked out adapters and stuff.

We could remove the `test__snowflake__simple_copy` that doesn't mess with quotes, that one actually has lots of implicit coverage.

These tests have my attempted speedups in them, we'll see how they go: https://circleci.com/gh/fishtown-analytics/dbt/12836
