### ISSUE TITLE
Cross-db utils defined in adapter macros

### ISSUE THREAD

**Issue by jtcohen6** [fishtown-analytics/dbt#1457]
### Feature description

Currently, there is no way to add adapter versions to crucial utility macros, such as the ones defined in [dbt-utils](https://github.com/fishtown-analytics/dbt-utils), without opening PRs against each macro package. 

Specific use case: We want to implement `date_spine` on Spark. The only required changes are special implementations of `dateadd` and `datediff`, as on [this branch](https://github.com/fishtown-analytics/dbt-utils/compare/feature/spark_adapter). (The rest of the date spine works exactly the same.)

In the long run, we should _not_ house an implementation of these core functions, for every single adapter, in the `dbt-utils` package. Ideally, we'd be able to create _extension_ packages, e.g. `dbt-utils-spark-ext`, that include just the custom implementations for a few critical macros. But this doesn't work with the way that package macros are currently scoped. We need some system of dependency resolution.

My best current proposal: Implement the [`cross_db_utils`](https://github.com/fishtown-analytics/dbt-utils/tree/feature/spark_adapter/macros/cross_db_utils) in the  `dbt/include/adapters.sql` of each adapter plugin. Packages like `dbt_utils` call these adapter macros instead of calling macros name-spaced to specific packages.

### Who will this benefit?

Anyone running dbt with an adapter outside of the Core Four. At present, that list includes [Presto](https://github.com/fishtown-analytics/dbt-presto) and [Spark](https://github.com/fishtown-analytics/dbt-spark).

**Comment by drewbanin** [comment]
@cmcarthur  and @beckjake: you had some thoughts on how we could accomplish something like this in dbt. I'm picturing:

```
# root project packages.yml

packages:
  - hub: fishtown-analytics/dbt_utils
  - hub: fishtown-analytics/spark_utils
```

The `dbt_utils` implementation of `date_spine` should make an `adapter_macro` call to a macro like `dateadd`, which should be dispatched to `spark__dateadd`, defined in `spark_utils`. I think this wouldn't work currently because `spark_utils` isn't in-scope in the `dbt_utils` macro context.

Jake, Connor, you guys seemed to have some alternative ideas about how we could accomplish something like this. Let's start by enumerating some possibilities before we get to any implementation

**Comment by beckjake** [comment]
These are a few of the ideas I've been thinking about for this problem. I like the first the best because I think it's the easiest to understand if you know dbt already and is pretty easy to implement... probably.

- Allow packages to declare a "namespace" that they're a part of, and have `spark_utils` declare itself part of the `dbt_utils` namespace
    - We talked about this during adapters as plugins but ended up just special-casing adapter plugins
    - We could still do it though!
- Define a concept of macro attributes, include the concept of a macro being in a different namespace. Like above, but just for one macro in a package (or more!)
  - I've yet to find pleasant syntax for this, but something like:
  - `{% attrmacro my_macro(a, b, ...): package_name=dbt_utils %} {% endattrmacro %}`
- Define a concept o macro attributes that are defined inside a macro:
  - `{% macro my_macro(a, b, ...) %} {{ config(...) }} ... {% endmacro %}`
  - Big downside: we'd have to actually parse macros during parsing, currently we only extract the names.
- Allow packages to have `adapter_macro` like names and use that
  - `spark__dbt_utils` -> `dbt_utils` if you have the spark adapter 
  - this really restricts package names 😬

**Comment by cmcarthur** [comment]
> Define a concept of macro attributes, include the concept of a macro being in a different namespace. Like above, but just for one macro in a package (or more!)
> * I've yet to find pleasant syntax for this, but something like:
> * `{% attrmacro my_macro(a, b, ...): package_name=dbt_utils %} {% endattrmacro %}`

this feels like the "right" solution to me, but, yes, the hard part is figuring out a syntax that works well. i can imagine a dozen alternatives, like:

`{% attrmacro {package_name: dbt_utils} my_macro(a, b, ...):  %} {% endattrmacro %}`
`{% attrmacro metadata={package_name: dbt_utils} my_macro(a, b, ...):  %} {% endattrmacro %}`
`{% attrmacro my_macro(a, b, ...) package_name=dbt_utils:  %} {% endattrmacro %}`
`{% attrmacro my_macro package_name=dbt_utils (a, b, ...):  %} {% endattrmacro %}`

... etc...

> Allow packages to have `adapter_macro` like names and use that
> * `spark__dbt_utils` -> `dbt_utils` if you have the spark adapter
> * this really restricts package names 😬

this feels just OK, and is an easy solution

the others don't seem ideal to me. esp #3 -- since it accomplishes the same thing as #2, but makes it harder for dbt to understand the metadata attached to a macro, and opens the door for weird dynamic metadata behavior

**Comment by drewbanin** [comment]
Thanks for enumerating these options! I like the idea of namespacing macros, but I think I'd prefer to use (mostly) vanilla macro syntax if possible!

@cmcarthur do you think docstrings are tractable here? 

@beckjake I think jinja has a [with block](http://jinja.pocoo.org/docs/2.10/templates/#with-statement) that provides a contextual namespace for a series of statements. Is there any world where we can do something like this with a `package` block? eg:

```
{% package_namespace dbt_utils %}

  {% macro my_macro() %}
    ....
  {% endmacro %}

{% endpackage_namespace %}
```

This would render the `my_macro` macro into the `dbt_utils` namespace.

#### An alternative mindset

Something about attaching these macros to a specific package namespaces feels not right to me. Is there a way to sort of... invert... this problem? Rather than defining a macro in the `dbt-utils-spark` package and declaring it to be a member of the `dbt-utils` package, can we instead change `dbt-utils` to dispatch adapter macro calls to a relevant package? This might require some convention, but i imagine in the `adapter_macro` call, we could dispatch this method call in the following order:
1. this package, macro called `<adapter>__<macro_name>`
2. included package, macro called `<adapter>`, called `<adapter>__<macro name>` (new)
3. local package, macro called `default__<macro name>`

Do you guys buy this line of reasoning?

**Comment by cmcarthur** [comment]
> @cmcarthur do you think docstrings are tractable here?

@drewbanin I'm not sure what you mean by this

> included package, macro called <adapter>, called <adapter>__<macro name>

I think there might be a typo here?

> can we instead change dbt-utils to dispatch adapter macro calls to a relevant package

this is interesting as a "quick way to get there" approach. but do we need to magically match up the adapter macro call to the relevant package name? i'm imagining a situation where a user wants to override an adapter macro in their own package. what if we just searched all of the available package namespaces for a matching `<adapter>__<macro_name>`? it would involve a little bit of inspection on the manifest (similar to what we were discussing yesterday with dynamically generating lists of sources) but it would mean that the package name would not need to be some exact string. and i believe all we would need to do is add a list of available package namespaces to the context

**Comment by beckjake** [comment]
I think he's saying that in the spark example, all you'd need is to have a dependency package of any kind that has a macro named `spark__dateadd` (or maybe even in your root project? I see no reason to restrict that)

The problem I see here is one of collisions. Currently I can do `dbt_utils.dateadd` and know that the only code that will be executed is `dbt_utils` code. In fact, in dbt-utils, I see that the dateadd macro does:
```
{% macro dateadd(datepart, interval, from_date_or_timestamp) %}
  {{ adapter_macro('dbt_utils.dateadd', datepart, interval, from_date_or_timestamp) }}
{% endmacro %}
```

Is this to avoid picking up any global-level `snowflake__dateadd` (for example) macros? Is that a common pattern?

**Comment by drewbanin** [comment]
@cmcarthur 
> do you think docstrings are tractable here?
```
{% macro my_macro() %}
"""
  @package: dbt_utils
  @description: ....
"""

{% endmacro %}
```

> I think there might be a typo here?

yep, updated :( 

> but do we need to magically match up the adapter macro call to the relevant package name

yeah, good question! I think you're right - i really like "what if we just searched all of the available package namespaces for a matching `<adapter>__<macro_name>`?"

How would we handle precedence? Eg. what if two different packages both provide a macro called `spark__datediff`? Maybe it's something simple like 1) your "root" package 2) the package that's calling the adapter macro 3) alphabetically (or something deterministic) after that? Maybe this is in fact a compiler error? Maybe we should implement a `z-index`?


@beckjake yeah, you're totally right - we'd need to change the adapter macro calls to not specify a package name. We actually did this out of necessity I think. If I understand correctly, the `context` only contains the macros that are provided by:
1. the global project (via `dbt/core/include/global_project`) and
2. the root project from which dbt is invoked

The macros for all other packages are namespaced under their package name in the `context` variable, so we needed to tell the `adapter_macro` function to look for the `dateadd` implementation in `dbt_utils` specifically. Check out this code in the [adapter_macro](https://github.com/fishtown-analytics/dbt/blob/dev/wilt-chamberlain/core/dbt/include/global_project/macros/adapters/common.sql#L9-L13). 

I _think_ this is only a limitation of macros defined in packages. A macro defined in the root project doesn't strictly need to do this.

It's miraculous that we've made it this far with that `adapter_macro` implementation :)

**Comment by cmcarthur** [comment]
> How would we handle precedence? Eg. what if two different packages both provide a macro called spark__datediff?

yeah, that's hard. my first thought was we'd raise a compiler error on conflict, but that doesn't let you override an adapter macro from dbt_utils, either. how would this work with our existing dbt-utils adapter_macros? is there any way to override just one? `z-index` sounds bad :D 

now that i'm thinking about it, this problem applies to a package injecting a macro into another package's namespace, right? you couldn't override `postgres__datediff` outside of dbt-utils since then you would have a conflict.

**Comment by drewbanin** [comment]
Not making a recommendation here, but maybe one possibility is to remove the magic from the equation? Just brainstorming here...

It wouldn't be crazy to configure `dbt-utils` with an implementing package. Imagine:
```
# dbt_project.yml

models:
  dbt_utils:
    implemented_by: dbt_utils_spark
```

Then there's a firm contract in place for other packages to implement. dbt_utils can implement the defaults, but you can configure it to use some other package to implement the "base" macros instead. This sort of obviates the "what do we do if there are name collisions" question, but presents new ones:
- what should happen in this case?
```
your project ---> dbt-utils<implemented by spark>
       |
       \-------> snowplow ---> dbt-utils<no implementation specified>
```

I think there's a way to do some `var` magic, but would want to look into this a little further.

**Comment by KimchaC** [comment]
I'd like to add the perspective of an end-user who is new to dbt and just ran into this issue. 

First of all, I am absolutely blown away by what you guys have created here and extremely grateful for your work.

I started experimenting with dbt on MS SQL and assumed that if a third party adapter passes all integration tests that it will "just work".

Then I tried to use `dbt_utils.surrogate_key` and promptly ran into several issues. My first assumption was that the adapter wasn't implemented properly and was lacking functionality.

So I tried to add the missing pieces to the adapter itself, but they just wouldn't get applied. That's how I ended up here :)

One of the things that failed was the `type_string()` macro. To me this seems like rather fundamental stuff that would probably be useful across many different packages and in my mind it would make most sense to implement it on the adapter level so that all packages can use it.

I had the same issue with `concat` and `hash`.

So why not implementing something where the main adapter can expose adapter specific functions and those can be used by all packages.

For missing functions a user could add additional user-specified adapter functions to make a package work before the maintainer of the main package gets around it.

**Comment by balmasi** [comment]
as an end-user, the behaviour I expected was for dbt to look at all my packages and find the `<adapter>__<macro>` pattern. I was intuitively looking for a way to register my adapter with the original namespace when defining it.  Something like mentioned above as

```jinja
{% package_namespace dbt_utils %}

  {% macro my_macro() %}
    ....
  {% endmacro %}

{% endpackage_namespace %}
```

You need some sort of interface to maintain adapters anyway, I don't think using a package name + macro name is any more restrictive than adapter+macro

However, this still doesn't solve the issue of the conflicts when multiple packages implement the same adapter.  

For example, let's say package `packageA` implement the `dbt_utils.concat`adapter for `dbA` and package `packageB` implements it for `dbB`

Ultimately it is the **developer's choice** which one they would want to use so it seems to me like developer configuration is  _inevitable_ (whether it's z-indexing, white/blacklist, or composition)

I think whitelisting is a good option and maybe a natural fit because

A) You'll need to be granular (don't want to define overrides for entire package, just an adapter)

B) You only need to choose 1 macro to override any given adapter (so whitelisting makes more sense)

```
# some sort of config step, yaml or code, essentially just saying 
dbA__concat -->  packageA.dbA__concat
```

**Comment by jtcohen6** [comment]
Closing! Made possible by the addition of [`adapter.dispatch`](https://docs.getdbt.com/reference/dbt-jinja-functions/adapter/#dispatch) in v0.18.0. See [`spark-utils`](https://github.com/fishtown-analytics/spark-utils) for a demonstration of how this can work.
