### ISSUE TITLE
The on-run-end context should have access to a sources object

### ISSUE THREAD

**Issue by tconbeer** [fishtown-analytics/dbt#1462]
### Feature description
Similar to the `schemas` object, there should be an iterable `sources` object available to macros that run in the on-run-end context that list all source Relations. "All" could mean every source in the project, or it could mean all sources upstream from all models that just ran.

Having an iterable of all sources will simplify and streamline maintenance operations in hooks, especially `vacuum` and `analyze` operations for Redshift.

I'm assuming `on-run-end` is the most logical place for this, but if it could be available earlier in the run, that could also be interesting; for example, in addition to taking snapshots of freshness, you could build a model that iterates through all/some sources and logs the change in row counts.

### Who will this benefit?
Mostly people on Redshift who only want to perform table maintenance operations on source tables that are used in their dbt project, but there may be several other creative uses

**Comment by drewbanin** [comment]
Hey @tconbeer - thanks for making this issue! Rather than specifying `sources` directly in the `on-run-end` context, how would you feel about exposing methods that return nodes from dbt's manifest? Check out this issue comment for one proposal: https://github.com/fishtown-analytics/dbt/issues/1212#issuecomment-493111070

I actually think the implementation required here would be a little different. Rather than `nodes.ref.sources`, we'd probably want to implement `nodes.find.resources` as shown in the "Other relevant things to think about" section of that comment.

**Comment by tconbeer** [comment]
Nailed it. Thanks, Drew. I anticipated the complexity of not having the DAG parsed at compile time; I had suggested `on-run-end` as a workaround, but clearly the solution you outlined in #1212 would be much more generally useful. Happy to wait for this to be done right.

**Comment by drewbanin** [comment]
FYI sources are accessible via `graph.sources` in dbt >= 0.17.0, and they are populated in the `graph.nodes` dict in dbt < 0.17. Closing this one!

**Comment by tconbeer** [comment]
Thanks, Drew!
