### ISSUE TITLE
Cannot load the string 'null' in seed data

### ISSUE THREAD

**Issue by ianterrell** [fishtown-analytics/dbt#1466]
### Issue description

I am being passed the string value `'null'` in upstream data, and I would like to use my mapping file, maintained by checked in seed data, to turn it into something more pleasant to read like `'Unknown'`.

However, I can't get the literal string `'null'` into my seed table!

All of the following rows result in a `NULL` value rather than a non-null string value of `'null'` after seeding:

```csv
key,original,mapped
a,null,Unknown
b,'null',Unknown
c,"null",Unknown
```

### System information
The output of `dbt --version`:
```
dbt --version
installed version: 0.12.2
```
The operating system you're running on: OS X
The python version you're using: Python 2.7.10

**Comment by drewbanin** [comment]
thanks for the report @ianterrell! My recommendation would be to use some sentinel value besides `null` (like `literal:null`) for these values, then use a model to rename these values back to `null`. 

I think the implementation you're describing is totally reasonable, but dbt's CSV parser is explicitly configured to treat `"null"` string literals in seeds as representations of `null` data points. You can see this configuration in the [agate type tester code](https://github.com/fishtown-analytics/dbt/blob/dev/wilt-chamberlain/core/dbt/clients/agate_helper.py#L9-L18).

I think both approaches (treat `null` as the string `"null"`, or as a missing value `null`) are reasonable implementations, and I think some nonzero number of people would be upset if we just flipped the implementation! It's conceivably possible to configure this on a per-seed basis, but that's not really something I'm interested in supporting in dbt.

I'd say: since [seed files should be version controlled](https://discourse.getdbt.com/t/dbt-seed-for-large-csv-files/328/3?u=drew), your best bet is going to be to use some value other than `null`, then post-process the seed in a model. If that approach doesn't work for you, it could be that some tool other than `dbt seed` is the right one for this use case!

**Comment by beckjake** [comment]
Even in barbualara-gittings, with our agate updates, we still don't support this. Do we actually want to prioritize this, and if so how?

The only reasonable-ish method I can think of is allowing users to specify something special in the `column_types` field (adding `NOT NULL` at the end?), looking at that when generating the override fields, and not setting any null values allowed for the type tester in that case.

So something like

```
seeds:
  - name: my_seed
    columns:
    - name: original
      data_type: text not null
```

And then dbt would create a TypeTester for that column with no `null` values, strip the `not null` off your data type, and do everything else the same as it currently does (interpret the column as raw text and cast it in your query - in this case to `text`).

Is that horrible?

**Comment by drewbanin** [comment]
@beckjake is agate unable to differentiate between `null` and `"null"`? I haven't seen any agate functionality to-date that considers value quoting, but it would sure be great if that was natively supported.

If agate doesn't support this out of the box, then I don't think we'll want to address this issue ourselves. I would not be in favor of supporting the kind of functionality that you've described above (though it is very clever 😄 )

**Comment by beckjake** [comment]
If you tell agate that the string `null` is  database `NULL`, [as we do](https://github.com/fishtown-analytics/dbt/blob/b9f8dedc8bb5a38611ba5eb166056fb73b527a1d/core/dbt/clients/agate_helper.py#L48-L51), then it can't tell the difference. My point was we can control whether or not we decide if it's null based on the config...

**Comment by drewbanin** [comment]
Ok - let's not make any changes here quite yet.

I'm going to close this issue as a #wontfix for now, but we can certainly revisit if there's any renewed interest. We queued this issue up alongside other agate issues, but this one is a little bit different in nature. Whereas most of the issues in #1639 prevented dbt seeds from loading data correctly, this issue can be addressed by a model in user-land to coalesce null values to some sort of sentinel value.

@ianterrell let me know if this is still an issue for you, happy to discuss further. Thanks @beckjake for checking it out!

**Comment by moseleyi** [comment]
What if the column in the seed is INTEGER but we still want to pass `null` not quoted. What I don't like in CSV are empty values. I would prefer either `null` or `'null'` to be treated as nulls. Is it possible?
