### ISSUE TITLE
Provide Ability to pass results from pre-events to the model query

### ISSUE THREAD

**Issue by richmintz** [fishtown-analytics/dbt#1861]
### Describe the feature
I would be very useful to be able to set a variable with the scalar result from pre-event or post event query for use later in the model or subsequent steps in the the process. 
This would be very useful when using an audit table to store the floor to be used in the next run of your model

### Who will this benefit?
This will benefit any process that is moving large incremental loads that does not want to suffer the overhead of a max sub query of {{ this }} in the predicate. It will also allow logging of the max update date or id on post-event

**Comment by drewbanin** [comment]
Thanks for making this feature request @richmintz!

How do you imagine dbt capturing the max date in a table in a pre- or post- hook? If the idea is that you'd query for the `max(timestamp)`, then you're going to need to incur this cost _somewhere_, right? My instinct is that any query planner worth its salt will execute the following query patterns in similar amounts of time:
```
select
  ...
from source_table
where timestamp > (select max(timestamp) from {{ this }})
group ...
```
vs.
```
-- store this result in a variable $MAX_TIME
select max(timestamp) from some_big_table;

select
  ...
from source_table
where timestamp > $MAX_TIME
group ...
```

I do buy that "caching" the results of this `max(timestamp)` query to re-use across different models could result in a model build time improvement, but managing a cache like this in a parallelized dbt run could be pretty tricky!

I'll also say: I think it's a bad idea to try to store this data in the database directly. You might be able to get away with this on a database like Postgres, but Redshift/Snowflake/BigQuery/Presto/Spark are not going to be super happy running individual insert/update statements to keep an audit table up-to-date in a parallelized fashion.

You identified two use cases here:
1. caching results from a model hook to re-use in a downstream model of the same build
2. caching results from a hook to re-use in a subsequent invocation of dbt

If we were going to support one of these things, I think the first one would be a lot more tractable than the second. dbt doesn't have a good way of persisting data between invocations, and that's sort of a feature -- the entire state of the run is stored in the tables and views in the database. Adding an external cache could lead to inconsistency between the tables in the database and the cached data (whether stored on disk, or stored in a database table).

Ultimately, I don't totally see the merit to supporting this feature -- if you have a sort key / partition key / clustering config defined on your incremental timestamp field, then the database should be able to find the `max()` value of that field _super_ quickly.

Last, if you do want to execute a post-hook to grab the max timestamp/id for a model and insert it into a database table, you can certainly already do that today! I think this a super cool idea and one that's worth doing if your requirements demand it. I don't think I'd recommend this, but if you did want to join to that table to find the max timestamp for an incremental model, I imagine you could already do that today as well, right?

I'm going to close this issue because I don't imagine accepting a PR for something like this in the near-to-medium-term future, but I am _super_ happy to discuss this further! We can always re-open it. Let me know if I missed something important, or if you have other ideas about how this could work.

Thanks again!
