### ISSUE TITLE
dbt 0.14.3 install from from pip doesn't work with snowflake

### ISSUE THREAD

**Issue by guy-adams** [fishtown-analytics/dbt#1892]
### Describe the bug
dbt install from from pip doesn't work with snowflake. dbt run gives:
```
Running with dbt=0.14.3
Encountered an error:
ssl_wrap_socket_with_ocsp() got an unexpected keyword argument 'key_password'
```

### Steps To Reproduce
```
pip3 --no-cache-dir install -U dbt
```
### Expected behavior
Connects to snowflak

### System information
**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [ ] bigquery
- [X] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
installed version: 0.14.3
   latest version: 0.14.3

Up to date!
```

**The operating system you're using:**

**The output of `python --version`:**

### Additional context
I believe this is related to the snowflake-connector-python version. I tried checking out the source, and building (without making any changes) and I get:
```
pip3 install -r requirements.txt
Processing ./core
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-fhlty2xe-build/setup.py", line 2, in <module>
        from setuptools import find_namespace_packages
    ImportError: cannot import name 'find_namespace_packages'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-fhlty2xe-build/
```

**Comment by drewbanin** [comment]
Thanks for the report @guy-adams - we're going to cut an 0.14.4 release that fixes this issue.

The issue you're seeing is related to https://github.com/snowflakedb/snowflake-connector-python/issues/225 and https://github.com/snowflakedb/snowflake-connector-python/issues/228.

Longer term, we are going to:
1. Provide a list of frozen package versions at release-time that will serve as a workaround for this problem
2. Tighten the `snowflake-connector-python` version range we accept so that changes to their lib can't break the installation of dbt

The second point here isn't ideal because it will make dbt difficult to install alongside other python programs, but "hard to install" is better than "uninstallable" 10 times out of 10 :)
