### ISSUE TITLE
source() behaves differently between parse and runtime

### ISSUE THREAD

**Issue by brian-bk** [fishtown-analytics/dbt#1998]
### Describe the bug
It looks like dbt's `source()` callable is different between compile and runtime. I stumbled on it when trying to include compile-time exceptions that behaved differently from what generated SQL was actually being run.

### Steps To Reproduce
I have a model file that looks something like this:
```
{{ log('SOURCE_LOG_STMT' + source('source_database', 'source_table')|string) }}
custom_macro_handling_source('source_database', 'source_table')
```

When I run `dbt -d compile | grep SOURCE_LOG_STMT` I'm able to get 2 differing values:

```
2019-12-10 17:08:03,299 (MainThread): SOURCE_LOG_STMT`dev_database`.`dev_schema`.`source_table`
2019-12-10 17:08:12,021 (Thread-12): SOURCE_LOG_STMT`source_database`.`source_schema`.`source_table`
```

Note the log statements are different between (MainThread) and (Thread-12).

The dev_database and dev_schema are related to the `profiles.yml` configuration, and not the source database and schema configuration, which is as expected.

### Expected behavior
`source('source_database', 'source_table_name')` should behave the same at compile and runtime, so that I can do compile time exception handling.

### System information
**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [x] bigquery
- [ ] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
installed version: 0.14.3
   latest version: 0.15.0

Your version of dbt is out of date! You can find instructions for upgrading here:
https://docs.getdbt.com/docs/installation
```

**The operating system you're using:**
```
Mac OSX
```

**The output of `python --version`:**
```
Python 3.7.4
```

### Additional context
I can try to fully build out this example in a fully-scoped play project, if this is not reproducible.

I don't yet fully understand if it's relevant, but not we have different schema name determination between prod and non-prod through:
```
{% macro generate_schema_name(custom_schema_name, node) -%}
  {{ generate_schema_name_for_env(custom_schema_name, node) }}
{%- endmacro %}

**Comment by drewbanin** [comment]
hey @brian-bk - thanks for making this issue! If you try the same thing out with `ref('...')`, you'll actually notice a similar behavior. The big problem here is that at parse-time, dbt is still figuring out the contents of your project, so it's not really possible for dbt to know what the correct output of `source(...)` should be!

There are actually two different implementations of the source function: one that runs at parse-time and one that runs at run-time. If you're interested in checking this code out, you can find the parse-time implementation here:
https://github.com/fishtown-analytics/dbt/blob/40839c79fcf1854942f8db44d1a2648bffe0a2ab/core/dbt/context/parser.py#L110-L121

and the run-time implementation here:
https://github.com/fishtown-analytics/dbt/blob/40839c79fcf1854942f8db44d1a2648bffe0a2ab/core/dbt/context/runtime.py#L62-L82

The parse-time implementation exists solely to capture the `source(...)` method call so that an edge between the source and the calling model can be created in the DAG. It returns an approximate (but not exact) Relation object because dbt simply doesn't know what the exact return value should be yet.

If you can tell me more about why this implementation is problematic for you, I'd be happy to suggest some workarounds. One option might be to use the [execute](https://docs.getdbt.com/docs/execute) context variable to determine if dbt is parsing or running the model in question.

I'm going to close this issue out with a wontfix label because it's not something I anticipate us fixing directly. I am however excited to better rationalize how parsing works in the future, as there are _many_ quirks like this that are tricky for users to understand and work around. Happy to follow up here, let me know if you have any further thoughts!

**Comment by brian-bk** [comment]
@drewbanin ah interesting. That workaround with `execute` will surely work for me, I just won't do the check if it is false.

The use-case I was working on was I wanted a macro to fail-fast and raise an error at compile time if it didn't see expected columns from `get_columns_in_relation`. Thank you for the workaround and context!
