### ISSUE TITLE
Snapshots ignore the generate_schema_name macro

### ISSUE THREAD

**Issue by bfil** [fishtown-analytics/dbt#2112]
### Describe the bug

I have custom macro definitions for `generate_schema_name` and `generate_alias_name`, they work fine when running models, but when running `dbt snapshot` only `generate_alias_name` seems to be used, while `generate_schema_name` doesn't have an effect on the output schema of the snapshot.

### Steps To Reproduce

Define custom overrides for macros `generate_schema_name` and `generate_alias_name`, create a snapshot file and run it with `dbt snapshot`.

### Expected behavior

The output schema and table name match the expected output of the macros.

### System information
**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [X] bigquery
- [ ] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
installed version: 0.15.0
   latest version: 0.15.2
```

**The operating system you're using:**

Mac OS Mojave 10.14.6

**The output of `python --version`:**

Python 3.7.4

**Comment by beckjake** [comment]
A note on the expected behavior, from drew on slack:

>snapshots _should not consider_ either `generate_schema_name` or `generate_alias_name` at present

**Comment by bfil** [comment]
@beckjake we currently use these custom macros to support isolating environments for each user working on DBT models. For example, our custom macro might output to a custom schema prefix for each user: `$USER_schema`.  It works very well for seeds and models and I would actually expect the same behaviour for snapshots rather than a different one.

**Comment by beckjake** [comment]
@drewbanin - not sure how you feel about this feedback. I actually have always agreed with @bfil but I know treating it this way was a design choice we made about what snapshots "mean". Maybe in the context of them being ref-able queries (and therefore in the middle of a potentially more complex graph), supporting `generate_*_name` makes more sense?

**Comment by drewbanin** [comment]
@bfil how would you actually expect this to work? I too would love it if snapshots were sandboxed to environment-based schemas, but that workflow would require each user to have their own copy of a potentially very-large snapshot table. Further, each copy of the snapshot would need to be re-run frequently in order for the development data to look anything like the production data!

For this reason, we use the config `target_schema` instead of `schema`. The two config values are generated differently. Have you instead considered calling the `generate_schema_name` macro yourself when configuring the snapshot? Maybe something like:

```
{% snapshot my_snapshot %}

    {{
        config(
            target_schema=generate_schema_name('snapshot', model),
            strategy='timestamp',
            unique_key='id',
            updated_at='updated_at'
        )
    }}

    select
        ...

{% endsnapshot %}
```

Here, the `model` context variable is automatically injected into the context. This will generate an environment-aware schema name for your snapshot. It comes with the caveat that you will need to run a `dbt snapshot` in each new dbt environment to populate the initial snapshot table. You may also need to run this on a schedule in order to have any real/sensible data in the snapshot table that can be consumed by downstream models.

I felt _very_ strongly about this design decision in the past, but that's been tempered a little bit by the sands of time. I'm super open to making snapshots environment-aware if we can convince ourselves that it it simpler/less error prone/as sensible as the existing approach!

**Comment by bfil** [comment]
@drewbanin thanks for the insights  (I always wondered why snapshots used `target_schema` instead of `schema`). As I don't know the internals of DBT  that well and why some decisions were taken it made more sense to me to expect the same behaviour.

You are right stating that isolated environment for each user snapshotting the entire production dataset seems a pretty unusual thing to do unless you have small-ish datasets, which is my current rather unusual situation, "big data" right? ;)

I tried the workaround by calling the macro directly, it just felt a little weird having to remember calling the macro in the config to make it align with the behaviour of models and seeds.

I guess it's mostly up to you, the maintainers, making a decision as you know best why snapshots were built using a different approach.

**Comment by drewbanin** [comment]
closing this as we probably won't make any changes here in the near future, but I would :love: to figure out a way to build snapshots in an environmentally-aware way in the future. The implementation will most likely _not_ use `generate_schema_name` directly though!

**Comment by drnielsen** [comment]
This behavior is odd and defies expectation. Do you have an explanation of why snapshot schemas don't work the same way as model schemas? I just don't see the logic in it.

**Comment by jtcohen6** [comment]
There is an FAQ in the docs which offers an explanation: https://docs.getdbt.com/faqs/snapshots/snapshot-target-schema
