### ISSUE TITLE
set_sql_header works well with 'table', but not 'incremental'

### ISSUE THREAD

**Issue by fhoffa** [fishtown-analytics/dbt#2136]
### Describe the bug
This test fails when you change 'table' for 'incremental':

test/integration/022_bigquery_test/models/sql_header_model.sql

### Steps To Reproduce

1. Change 'table' to 'incremental' in sql_header_model.sql
2. `dbt run` works well the first time (creates the table)
3. `dbt run` fails the next time (when doing incremental)

### Expected behavior

The incremental run should bring the same headers - the model will again need the temporal function.

### Screenshots and log output

"Function not found: yes_no_to_boolean at [14:8]"

### System information
**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [x ] bigquery
- [ ] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
0.15.2

**Comment by drewbanin** [comment]
Thanks for the report @fhoffa - we'll check it out!

**Comment by drewbanin** [comment]
@fhoffa see the fix for this here: https://github.com/fishtown-analytics/dbt/pull/2200

We're in the late phases of the 0.16.0 release and we've generally locked down PRs with the exception of any regressions discovered during the release candidate phase. I think we should target an 0.16.1 bugfix release for this PR. Just wanted to give you a heads up!
