### ISSUE TITLE
Default models[].name to yml file name

### ISSUE THREAD

**Issue by ran-eh** [fishtown-analytics/dbt#2189]
### Describe the feature
In a schema yml file under models, if the name property is not specifies, default to yml file name.

### Describe alternatives you've considered
N/A

### Additional context
See next section

### Who will this benefit?
We like to store schema yml info (tests etc.) for close to the model close to the model.  So a typical dir would like like:
```
model1.sql
model1.yml
model2.sql
model2.yml
...
```
It will be nice to be able to omit the model name in the yml file, and have it automatically set to the file name, like so

**`model1.yml`**
```
models:
  # - name: model1 # no longer needed - set from file name.
  - description:blah
  ...
```

This is obviously a low priority item.  However, if this is easy to do, I will be happy to implement it myself.

**Comment by drewbanin** [comment]
hey @ran-eh - this is a cool idea, but I don't think I'm in favor of adding something like this. I like the idea of these yaml specs being unambiguous, and it would be unclear how to handle the behavior shown here if there were multiple model entries in the same .yml file. I think we'd have to disallow that, which would make for some pretty weird/confusing error handling behavior.

I'm applying the wontfix label here because I don't think this is something that we should implement, but I do want to thank you for opening this issue! I'm happy to discuss below, let me know what you think :)
