### ISSUE TITLE
Support overriding internal macros from root projects

### ISSUE THREAD

**Issue by drewbanin** [fishtown-analytics/dbt#2301]
### Describe the bug
Users should be able to override plugin-specific macros from their root project.

### Steps To Reproduce
```
{# macros/override.sql #}

{% macro postgres__get_columns_in_relation() %}

    {{ log("OVERRIDE", info=true) }}

{% endmacro %}
```

```
-- models/my_model.sql

{{ adapter.get_columns_in_relation(this) }}
```

I'd expect to see log output indicating that the override macro was being used. This does not work for macros named `get_columns_in_relation` or `postgres__get_columns_in_relation`.

I haven't done enough digging to know why this behavior would be different from something like `create_table_as`, but I suspect it has something to do with going through the context used by the `adapter.get_*` methods.

### Expected behavior
Macros defined in a project should override dbt's core implementation, or the implementation provided by a dbt plugin.

**The output of `dbt --version`:**
```
0.16.0
```

**Comment by beckjake** [comment]
This happens because `adapter.get_columns_in_relation` doesn't take a manifest, so it doesn't pass a manifest to `execute_macro`, so `execute_macro` uses the "internal manifest", which only has macros from `core`.

We might be able to avoid this by parsing _all_ project macros up-front and building that into the "internal manifest". I feel a lot more comfortable with that path now that we've refactored manifest loading quite a bit.

**Comment by ArtiJain0688** [comment]
Hello Jacob, 

I am trying to override some macros with respect to "Snapshot" materialization. As you mentioned in the above issue even though I have overwritten the macros it still reads from the core.
Could you please tell me steps how to override this behaviour so that the code reads the overwritten macros and functions according to the changes made in it

**Comment by jtcohen6** [comment]
@ArtiJain0688 Could you provide some more details of your implementation? Which version of dbt are you using? Which macro in the `snapshot` materialization are you trying to override, and how have you gone about it? As long as you have defined a macro in your own project with the same name as a macro in dbt-core or a dbt adapter plugin, dbt should know to prefer yours.

**Comment by ArtiJain0688** [comment]
Hello Jeremy,

Thank you so much for your reply.
I did try again to override the already existing snapshot macro and it
worked.

I really appreciate your response on this query.

Regards,
Arti Jain
