### ISSUE TITLE
error installing with pip

### ISSUE THREAD

**Issue by morenoh149** [fishtown-analytics/dbt#2372]
### Describe the bug
When I run `pip install dbt` I get
```
Collecting minimal-snowplow-tracker==0.0.2
  Using cached minimal-snowplow-tracker-0.0.2.tar.gz (12 kB)
Collecting hologram==0.0.6
  Using cached hologram-0.0.6.tar.gz (19 kB)
  Installing build dependencies ... error
  ERROR: Command errored out with exit status 1:
   command: /Users/harrymoreno/.asdf/installs/python/3.7.3/bin/python3.7 /Users/harrymoreno/.asdf/installs/python/3.7.3/lib/python3.7/site-packages/pip install --ignore-installed --no-user --prefix /private/var/folders/02/s7870fmd71nc5w282qhp64rw0000gn/T/pip-build-env-_vfnjrec/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=40.8.0' wheel
       cwd: None
  Complete output (14 lines):
  Traceback (most recent call last):
    File "/Users/harrymoreno/.asdf/installs/python/3.7.3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
      "__main__", mod_spec)
    File "/Users/harrymoreno/.asdf/installs/python/3.7.3/lib/python3.7/runpy.py", line 85, in _run_code
      exec(code, run_globals)
    File "/Users/harrymoreno/.asdf/installs/python/3.7.3/lib/python3.7/site-packages/pip/__main__.py", line 16, in <module>
      from pip._internal.cli.main import main as _main  # isort:skip # noqa
    File "/Users/harrymoreno/.asdf/installs/python/3.7.3/lib/python3.7/site-packages/pip/_internal/cli/main.py", line 5, in <module>
      import locale
    File "/Users/harrymoreno/.asdf/installs/python/3.7.3/lib/python3.7/locale.py", line 16, in <module>
      import re
    File "/Users/harrymoreno/.asdf/installs/python/3.7.3/lib/python3.7/re.py", line 143, in <module>
      class RegexFlag(enum.IntFlag):
  AttributeError: module 'enum' has no attribute 'IntFlag'
  ----------------------------------------
ERROR: Command errored out with exit status 1: /Users/harrymoreno/.asdf/installs/python/3.7.3/bin/python3.7 /Users/harrymoreno/.asdf/installs/python/3.7.3/lib/python3.7/site-packages/pip install --ignore-installed --no-user --prefix /private/var/folders/02/s7870fmd71nc5w282qhp64rw0000gn/T/pip-build-env-_vfnjrec/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=40.8.0' wheel Check the logs for full command output.
```

**The operating system you're using:**
osx 10.14.6

**The output of `python --version`:**
3.7.3

### Additional context
I use asdf to manage my python versions https://asdf-vm.com

**Comment by beckjake** [comment]
Hi @morenoh149! It looks like something is up with your Python environment. The `enum` package has had `IntFlag` since python 3.6 (see [here](https://docs.python.org/3.6/library/enum.html)), so that error message doesn't make much sense.

Is it possible that you have the `enum34` package installed? This stack overflow page seems relevant! https://stackoverflow.com/a/45716067/11262881 dbt doesn't support python < 3.6 so compatibility isn't a concern.

I'd suggest you make a new virtualenv entirely and use that for dbt. The [packaging.python.org docs](https://packaging.python.org/guides/installing-using-pip-and-virtual-environments/) on the subject are pretty good.

**Comment by morenoh149** [comment]
ok I installed dbt with pip but the cli tool is not available

```
$ dbt debug
-bash: dbt: command not found   
```
should I open another issue?

**Comment by drewbanin** [comment]
Hey @morenoh149 - it's pretty tough for us to do support via GitHub issues. Can you instead try another medium for getting community support with installing dbt? One great place to check out is the dbt Slack (slack.getdbt.com). That type of medium is way better suited for live community support like this.

The issues you're having a problems with your local development environment, and while we'd be happy to help you get sorted on Slack, I'm going to close this issue because no code change is anticipated in the resolution of this issue.

Thanks!

**Comment by morenoh149** [comment]
asdf python currently needs to be reshimmed to pick up newly install pip modules. See https://github.com/danhper/asdf-python/issues/37

workaround is to run `asdf reshim python`
