### ISSUE TITLE
Question: Oracle Support

### ISSUE THREAD

**Issue by cemremengu** [fishtown-analytics/dbt#2424]
Does dbt support Oracle? I couldnt see it in the supported databases list. I am hoping that it does but just unlisted 😞

**Comment by jtcohen6** [comment]
dbt doesn't support Oracle—yet. We try to list all supported databases that we're aware of in the [supported databases](https://docs.getdbt.com/docs/supported-databases) page of the docs.

There's no reason there _couldn't_ be a `dbt-oracle` plugin, as far as I'm aware. We have a fairly solid (and always improving) framework for plugins contributed and supported by members of the community. If that's something you'd be interested in building, check out the docs on [building a new adapter](https://docs.getdbt.com/docs/contributing/building-a-new-adapter). I'd be more than happy to help answer any questions, too.

**Comment by max-sixty** [comment]
This is available: https://github.com/techindicium/dbt-oracle

**Comment by jtcohen6** [comment]
Great point @max-sixty. I'm going to close this issue because it's out of scope for this repository (dbt core), and because members of the community stepped in & stepped up.

There's an open PR (https://github.com/fishtown-analytics/docs.getdbt.com/pull/187) to add Oracle to the list of supported databases, I just assigned myself for review.
