### ISSUE TITLE
dbt seed --select {model_name} and dbt run --models {model_name} error out when other model dependencies are missing

### ISSUE THREAD

**Issue by agnesbao** [fishtown-analytics/dbt#2503]
### Describe the bug
I am collaborating on the same project with my team and working on a specific model. Under the models/ directory there're other model sql which contains seed data that cannot be shared. 

### Steps To Reproduce
When I run `dbt seed --select  {model_name}` or `dbt run --models {model_name}` which only contains my own model, it will error out with: 
```
Encountered an error:
Compilation Error in model {other_model} (models/{other_model}.sql)
  Model '{other_model}' (models/{other_model}.sql) depends on a node named '{other_model_seed}' which was not found
```
The way i get around it is to move the sql in question out of the place temporarily 

### Expected behavior
Can we only check dependencies of specified models when using --select or --models and disregard other independent ones

### System information
**Which database are you using dbt with?**
- [ ] postgres
- [x] redshift
- [ ] bigquery
- [ ] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
installed version: 0.18.0-a1
   latest version: 0.16.1

Your version of dbt is ahead of the latest release!

Plugins:
  - bigquery: 0.18.0a1
  - snowflake: 0.18.0a1
  - redshift: 0.18.0a1
  - postgres: 0.18.0a1
```

**The operating system you're using:**
macOS Catalina
version 10.15.4

**The output of `python --version`:**
Python 3.6.10

**Comment by jtcohen6** [comment]
dbt needs to construct and verify the entire DAG before it can run any part of it. I don't think we plan to build a version of `compile`, `seed`, or `run` that will work if there are missing references.

> other model sql which contains seed data that cannot be shared.

This is fair! You may want to make this a `source` instead of a seed file, if its contents need to be kept hidden from some dbt users.

I'm also surprised to see you're using an `0.18.0-a1` version of dbt, given that haven't released 0.17.0 yet.
