### ISSUE TITLE
There are incompatible versions in the resolved dependencies

### ISSUE THREAD

**Issue by rbval** [fishtown-analytics/dbt#2544]
Getting the following line when trying to install dbt 0.17.0 with pipenv:

```
There are incompatible versions in the resolved dependencies:
  botocore<1.15,>=1.5.0 (from dbt-redshift==0.17.0->dbt==0.17.0->-r /var/folders/k_/qxkwwjjn16n9f9s53vc4g8q00000gn/T/pipenvtddq7bxhrequirements/pipenv-hyvox2_3-constraints.txt (line 6))
  botocore<1.18.0,>=1.17.2 (from boto3==1.14.2->-r /var/folders/k_/qxkwwjjn16n9f9s53vc4g8q00000gn/T/pipenvtddq7bxhrequirements/pipenv-hyvox2_3-constraints.txt (line 8))
  botocore<2.0a.0,>=1.12.36 (from s3transfer==0.3.3->boto3==1.14.2->-r /var/folders/k_/qxkwwjjn16n9f9s53vc4g8q00000gn/T/pipenvtddq7bxhrequirements/pipenv-hyvox2_3-constraints.txt (line 8))
```

This was with the following Pipfile:
```
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[packages]
ipdb = "*"
boto3 = "*"

[requires]
python_version = "3.7"

[pipenv]
allow_prereleases = true
```

Seems like `dbt` doesn't work at all if `boto3` gets separately installed within the same Pipfile. Only way I was able to fix this was by removing the `boto3` altogether, however this hides that dependency under `dbt`. Any way to handle this in `dbt`'s end?

**Comment by drewbanin** [comment]
hey @rbval - thanks for opening this issue! I might be a little confused here, but I don't see dbt stated in the Pipfile you've shown here. Maybe if you included that, I'd have a better idea of what your repro scenario is? That said:

I don't think this is a dbt bug -- I think this just how pip works. pip will install a suitable version of these modules, and their dependencies, in this order:
 - ipdb
 - boto3
 - dbt

If you try this on the command line with:
```
pip install ipdb boto3 dbt
```

You'll see the output:
```
ERROR: snowflake-connector-python 2.2.1 has requirement boto3<1.12,>=1.4.4, but you'll have boto3 1.14.3 which is incompatible.
ERROR: snowflake-connector-python 2.2.1 has requirement botocore<1.15,>=1.5.0, but you'll have botocore 1.17.3 which is incompatible.
ERROR: dbt-redshift 0.17.0 has requirement boto3<1.12,>=1.4.4, but you'll have boto3 1.14.3 which is incompatible.
ERROR: dbt-redshift 0.17.0 has requirement botocore<1.15,>=1.5.0, but you'll have botocore 1.17.3 which is incompatible.
```

This is unfortunate because pip has all of the information it needs to do the right thing, but it instead chooses to do the wrong thing. I think this is just the nature of python package management in 2020!

Instead of the approach you're using above, I'd recommend pinning your boto dep to a version range commensurate with dbt's requirements. At present, that looks like [>=1.4.4,<1.12'](https://github.com/fishtown-analytics/dbt/blob/74c78ef9279638d14949d4e93ae76166d4fd8022/plugins/redshift/setup.py#L45).

Something like this should work:
```
pip install ipdb 'boto3>=1.4.4,<1.12' dbt
```

I'm going to close this issue as I don't think there's really any mechanism we can employ at all here inside of dbt, but please let me know if you have any further questions!
