### ISSUE TITLE
Running `dbt snapshot` succeed the first time but fails the other times

### ISSUE THREAD

**Issue by cabouffard** [fishtown-analytics/dbt#2574]
### Describe the bug
I'm running DBT 0.17 and we've been playing with the snapshot feature.

I'm hitting an oddity that I'm not sure how to resolve or what to understand from it.

Keep in mind that my tables currently have no data inside them.

* The first time I run `dbt snapshot` everything is successful: https://share.getcloudapp.com/E0uzrezL
* The second time and subsequent time I run DBT I get errors: https://share.getcloudapp.com/DOuA9Exe

It seems like some snapshots can't infer the column types for some reason and I'm not sure what could be wrong.

### Steps To Reproduce
My Snapshot query:
```sql
{% snapshot snapshot_shipmonk__shipping_addresses %}
{{
    config(
      target_database='output',
      target_schema='dbt_cab',
      unique_key='id',
      strategy='timestamp',
      updated_at='modified',
    )
}}
select * from {{ source('public', 'shipmonk_shipping_address') }}
{% endsnapshot %}
```

The compiled query (the second time I run `dbt snapshot`):
```sql
   update "output"."dbt_cab"."snapshot_shipmonk__shipping_addresses"
    set dbt_valid_to = DBT_INTERNAL_SOURCE.dbt_valid_to
    from "snapshot_shipmonk__shipping_addresses__dbt_tmp20200618215824103241" as DBT_INTERNAL_SOURCE
    where DBT_INTERNAL_SOURCE.dbt_scd_id::text = "output"."dbt_cab"."snapshot_shipmonk__shipping_addresses".dbt_scd_id::text
      and DBT_INTERNAL_SOURCE.dbt_change_type::text = 'update'::text
      and "output"."dbt_cab"."snapshot_shipmonk__shipping_addresses".dbt_valid_to is null;
    insert into "output"."dbt_cab"."snapshot_shipmonk__shipping_addresses" ()
    select 
    from "snapshot_shipmonk__shipping_addresses__dbt_tmp20200618215824103241" as DBT_INTERNAL_SOURCE
    where DBT_INTERNAL_SOURCE.dbt_change_type::text = 'insert'::text;
```

The DDL of the table when it was first generated:
```sql
create table dbt_cab.snapshot_shipmonk__shipping_addresses
(
	id integer,
	integration_id integer,
	shipping_order_id integer,
	company text,
	street1 text,
	street2 text,
	street3 text,
	city text,
	state text,
	postal_code text,
	phone text,
	country text,
	is_residential boolean,
	is_verified boolean,
	created timestamp with time zone,
	modified timestamp with time zone,
	dbt_scd_id text,
	dbt_updated_at timestamp with time zone,
	dbt_valid_from timestamp with time zone,
	dbt_valid_to timestamp with time zone
);
alter table dbt_cab.snapshot_shipmonk__shipping_addresses owner to postgres;
```

1) Remove all snapshot tables (i.e. start from a clean snapshot schema)
2) Have the source tables contain no data
3) Run `dbt snapshot`
4) Run `dbt snapshot` again

Notice that some snapshot fails: https://share.getcloudapp.com/DOuA9Exe

### Expected behavior
`dbt snapshot` should run all snapshot successfully and not have any failures

### Screenshots and log output
See links and queries above

### System information
**Which database are you using dbt with?**
- [x] postgres
- [ ] redshift
- [ ] bigquery
- [ ] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
/usr/src # dbt --version
installed version: 0.17.0
   latest version: 0.17.0

Up to date!

Plugins:
  - postgres: 0.17.0
  - bigquery: 0.17.0
  - redshift: 0.17.0
  - snowflake: 0.17.0
```

**The operating system you're using:**
```
Docker container with: python:3.7-alpine (i.e. Alpine Linux)
```

**The output of `python --version`:**
```
/usr/src # python --version
Python 3.7.7
```

### Additional context
N/A

**Comment by jtcohen6** [comment]
Thanks for the detailed writeup, @cabouffard.

Here's what _should_ be happening in the snapshot materialization on all subsequent runs:

1. dbt creates a temporary "staging" table, e.g. `snapshot_shipmonk__shipping_addresses__dbt_tmp20200618215824103241`, that contains all records that have been updated since the last time you added records to the snapshot table, i.e.
```sql
where dbt_cab.snapshot_shipmonk__shipping_addresses.dbt_valid_from < public.shipmonk_shipping_address.modified
```
2. dbt grabs the list of columns in the temp table via `adapter.get_columns_in_relation`, which on postgres looks like:
```sql
select * from information_schema.columns
where table_name = 'snapshot_shipmonk__shipping_addresses__dbt_tmp20200618215824103241'
```
3. dbt uses the list of columns from step 2 to add/expand columns in the existing snapshot table, if necessary.
4. dbt runs an `update` statement followed by an `insert` statement that includes the full list of columns from step 2.

In your case, the column list obtained by step 2 is empty, causing the error in step 4. Here are things I could imagine going wrong:
- Is there any reason why the temporary "staging" table would be missing columns? Even if there are no new records (i.e. `{{ strategy.row_changed }}` always evaluates to `false`), the resulting table should still have zero rows and the full column specification.
- Since `dbt-postgres` [includes the current timestamp](https://github.com/fishtown-analytics/dbt/blob/dev/marian-anderson/plugins/postgres/dbt/include/postgres/macros/adapters.sql#L121) in its temp table naming, is it possible that dbt is generating that table name twice, with _different_ timestamps, when creating the table vs. when querying `information_schema.columns` for its metadata?
- Is it possible that dbt is performing steps 1 and 2 with different connections? Temp tables in Postgres only stick around for the duration of the session. If dbt is making a new connection connection to query `information_schema.columns`, or doing so from a different thread, it would return an empty list of columns.

Of those three possibilities, the third feels most plausible to me. You could examine the `logs/` to figure out if dbt is indeed opening a new connection or running from a different thread between the two steps.

@drewbanin Any thoughts here? I may be missing something obvious.

**Comment by drewbanin** [comment]
This report reminds me a lot of #2197. The identifier `snapshot_shipmonk__shipping_addresses__dbt_tmp20200618215824103241` is 67 bytes long, which is unfortunately longer than the 63 byte limit on postgres :(

So, dbt is indeed creating the temp table, but postgres silently drops the last four characters of the temp table name. When we go to look up the columns in this table in the information schema, we don't find the relation we're looking for!

We should:
 - figure out a way to address #2197 (probably with some sort of verification in the `create_table_as` and `create_view_as` macros).
 - add a check to the snapshot logic which assets `len(columns)` > 0, since the failure mode described here is tremendously unhelpful, and it can be hard to piece things together from the snapshot logs

**Comment by cabouffard** [comment]
Is the suggested fix for us to reduce the length of the table name to ensure that it's always below 63 bytes long until an "official" fix is released?

**Comment by drewbanin** [comment]
Glad to hear you got it working! There really isn't anything we can do to _fix_ this -- we will instead just add a very prominent and notable error message whenever dbt tries to create a table/view > 63 characters long on Postgres. It's not an ideal outcome, but it's better than the failure mode that you observed here IMO!

I'm closing this in favor of #2197 -- this should be addressed in our next release of dbt!
