### ISSUE TITLE
dbt_utils.surrogate_key — Syntax error

### ISSUE THREAD

**Issue by VigneshwaranSundaresan** [fishtown-analytics/dbt#2585]
### Describe the bug

vigneshwaransundaresan@Vigneshwarans-MacBook-Pro my-first-dbt-project % dbt run --m example.insert_sample
Running with dbt=0.17.0
* Deprecation Warning: dbt v0.17.0 introduces a new config format for the
dbt_project.yml file. Support for the existing version 1 format will be removed
in a future release of dbt. The following packages are currently configured with
config version 1:
 - dbt_utils

For upgrading instructions, consult the documentation:
  https://docs.getdbt.com/docs/guides/migration-guide/upgrading-to-0-17-0
Found 7 models, 15 tests, 1 snapshot, 0 analyses, 208 macros, 1 operation, 0 seed files, 1 source

12:49:26 | 
12:49:26 | Running 1 on-run-start hook
12:49:26 | 1 of 1 START hook: dbt_from_scratch.on-run-start.0................... [RUN]
12:49:26 | 1 of 1 OK hook: dbt_from_scratch.on-run-start.0...................... [SUCCESS 1 in 0.16s]
12:49:26 | 
12:49:26 | Concurrency: 1 threads (target='dev')
12:49:26 | 
12:49:26 | 1 of 1 START incremental model DBT.TYPE1_TESTING..................... [RUN]
12:49:28 | 1 of 1 ERROR creating incremental model DBT.TYPE1_TESTING............ [ERROR in 1.97s]
12:49:29 | 
12:49:29 | Finished running 1 incremental model, 1 hook in 5.14s.

Completed with 1 error and 0 warnings:

**Database Error in model insert_sample (models/example/insert_sample.sql)
  001003 (42000): SQL compilation error:
  syntax error line 4 at position 4 unexpected 'md5'.
  syntax error line 11 at position 1 unexpected ','.
  compiled SQL at target/compiled/dbt_from_scratch/models/example/insert_sample.sql**

Done. PASS=0 WARN=0 ERROR=1 SKIP=0 TOTAL=1

### Steps To Reproduce
**packages.yml file:**

packages:
  - package: fishtown-analytics/dbt-utils
    version: 0.1.18

### Expected behavior
Model:

{{ dbt_utils.surrogate_key(['C_CUSTKEY','AS_OF_DT']) }} as natural_key

{{
config(
  materialized='incremental',
  incremental_strategy='delete+insert',
  alias='TYPE1_TESTING',
  unique_key='natural_key'
)
}}

### Screenshots and log output
If applicable, add screenshots or log output to help explain your problem.

### System information
Snowflake

**The output of `dbt --version`:**

vigneshwaransundaresan@Vigneshwarans-MacBook-Pro my-first-dbt-project % dbt --version
installed version: 0.17.0
   latest version: 0.17.0

Up to date!

Plugins:
  - bigquery: 0.17.0
  - snowflake: 0.17.0
  - redshift: 0.17.0
  - postgres: 0.17.0

**The operating system you're using:**

macOS

**The output of `python --version`:**

**Comment by jtcohen6** [comment]
Hey @VigneshwaranSundaresan! In general, when you need specific support debugging something, your best first bet is to message our [Slack community](http://community.getdbt.com/), rather than opening an issue here.

`dbt_utils.surrogate_key` isn't actually defined in this repository, it's defined in the [dbt-utils repository](https://github.com/fishtown-analytics/dbt-utils). If you run into a specific issue using that macro, you'll want to look at the README and source code there.

It _looks_ like what you're trying to do is set the `unique_key` config via the `surrogate_key` macro. That's totally possible, but it requires a few Jinja changes:
```
{% set natural_key = dbt_utils.surrogate_key(['C_CUSTKEY','AS_OF_DT']) %}

{{
config(
materialized='incremental',
incremental_strategy='delete+insert',
alias='TYPE1_TESTING',
unique_key=natural_key
)
}}
```
Your database error will make more sense if you look at the compiled model SQL. Check out our [docs on using Jinja in dbt](https://docs.getdbt.com/docs/writing-code-in-dbt/getting-started-with-jinja), if you haven't already.

I'm going to close this issue because it doesn't require a code change in dbt.
