### ISSUE TITLE
Encountered an error: Unresolvable JSON pointer: “definitions/NoValue”

### ISSUE THREAD

**Issue by hanachurch** [fishtown-analytics/dbt#2605]
### Describe the bug
A clear and concise description of what the bug is. What command did you run? What happened?

Migrated to dbt 0.17. Received the above error message as soon as I ran 'dbt compile' on a project that worked fine with dbt 0.15.1.  

```
Running with dbt=0.17.0
Encountered an error:
Unresolvable JSON pointer: “definitions/NoValue”
```
I have another Windows PC on which this error doesn't occur.

### Steps To Reproduce
In as much detail as possible, please provide steps to reproduce the issue. Sample data that triggers the issue, example model code, etc is all very helpful here.

See above

### Expected behavior

dbt compiles the project successfully without errors.

### Screenshots and log output
If applicable, add screenshots or log output to help explain your problem.

This error doesn't generate a log. (dbt.log)

### System information
**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [ ] bigquery
- [ ] snowflake
- [ ] other (specify: _dbt-sqlserver but this project doesn't specifically use dbt-sqlserver package___________)

**The output of `dbt --version`:**
```
<output goes here>
```

**The operating system you're using:**

**The output of `python --version`:**

**Comment by drewbanin** [comment]
hey @hanachurch - the information included in this issue template is really important for diagnosing new issues. In particular, the `python --version` output would have been super helpful to see here. My guess is that you're using Python < 3.6.3, which is a new requirement for running dbt v0.17.0. Check out the Python Requirements section in the [upgrading guide](https://docs.getdbt.com/docs/guides/migration-guide/upgrading-to-0-17-0#python-requirements) for 0.17.0.

I'd recommend getting upgraded to a more recent release of Python. FWIW, we've also made some changes to produce a better warning when dbt is run with an incompatible version of Python. See https://github.com/fishtown-analytics/dbt/pull/2537 for more info.

I'm going to close this out, but happy to continue the thread if you have any further questions!

**Comment by beckjake** [comment]
For posterity: This is due to having a downlevel version of `hologram` (in particular, `hologram<0.0.7`), which can happen for various reasons. In this user's case, it was because they were using anaconda and had an old version of `hologram` installed. `pip` doesn't see/maintain anaconda-installed packages, but they do show up when you `import`. So if you get `dbt` + `hologram` installed via `conda` somehow, and then do `conda remove dbt`, `hologram` will remain. Then when you `pip install dbt` you'll get new `dbt` that requires new `hologram`, but you'll still have old invalid `hologram` first in the import path.

The solution was to `conda remove hologram`.
