### ISSUE TITLE
Writing Logs to Separate File in Logs Directory 

### ISSUE THREAD

**Issue by VigneshwaranSundaresan** [fishtown-analytics/dbt#2617]
### Describe the feature
DBT does not have the feature to update log messages to different log files in Logs directory or custom directory specified in dbt_project.yml file. 

For example:

source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
log-path: dbt_logs

Instead of writing the dbt.log in log folder. The above configuration created a new log directory called dbt_logs and started writing to the dbt.log file

What i am looking for is writing to a separate log file everytime when i run a model. Like below:
logs
   dbt_<model-name>_<invocation-id>_<run_time>.log
   dbt_<model-name>_<invocation-id>_<run_time>.log
   dbt_<model-name>_<invocation-id>_<run_time>.log

### Describe alternatives you've considered
I have tried all the options mentioned in [https://docs.getdbt.com/reference/project-configs/log-path/]
### Additional context
No this is not database specific

### Who will this benefit?
This would help developers to have a greater look at the log-file for debugging.

### Are you interested in contributing this feature?
Yes. I would like to contribute if possible

**Comment by jtcohen6** [comment]
@VigneshwaranSundaresan Thanks for following up by opening an issue! I want to clarify a few points:

> What i am looking for is writing to a separate log file every time when i run a model.

In particular, it sounds like you're interested in dbt writing to a different log file _for each model_ in a run, rather than just _for each invocation_. Is that right?

The [dbt Cloud Develop interface](https://docs.getdbt.com/docs/dbt-cloud/the-dbt-ide) does something similar today.

> This would help developers to have a greater look at the log-file for debugging.

If my understanding above is correct, I see the appeal in being able to debug a specific model by finding its unique log file. I can also see this becoming quite unwieldy in big projects.

Do you envision that dbt would write log files into subdirectories, based on the subdirectories of the model files—similar to how it organizes `target/compiled` and `target/run`?

A related issue here is significantly improving the `target` artifacts, which has long been part of our vision for a materialization rework:
* Include the compiled code for _all_ materialization steps in `target/compiled`, like a dry-run mode (https://github.com/fishtown-analytics/dbt/issues/1059)
* Include _all_ associated queries in `target/run` for materializations that require running more than one query (e.g. `incremental`)

**Comment by jtcohen6** [comment]
I don't think we're going to add native functionality to dbt that supports writing different log files based on the thread or node being executed.

For users who want to split out separate logs for each model, our recommendation is going to be:
- turn on json-formatted logging
- write those logs to a file
- parse out each model via `extra.unique_id`

E.g.:
```bash
dbt -d --log-format json > logs.json run -m stg_orders
cat logs.json | jq '. | select(.extra.unique_id=="model.jaffle_shop.stg_orders")'
```

**Comment by vianmora** [comment]
Hello :) 

I'm rather sad to see that single-file logs will remain the norm :'( 

I find it rather difficult to read, especially after several executions :/  

Is there any way to make a default log architecture that could looks like this? : ) 

```
dbt_logs
└─ {timestamp}
       ├─ dbt.log
      └─ target (to have the target generated during the run? Instead of only the last one? )
```

Thank you for your answer ;)

**Comment by jtcohen6** [comment]
@vianmora Depending on how you're developing/deploying dbt, you might be able to use the `--log-path` flag to control which directory dbt is writing the `dbt.log` file.

A simple bash-y example:
```
$ dbt run --log-path "logs/$(date +%Y/%m/%d/%H:%M:%s)"
```
Writes the logs to:
```
$ tree logs/
logs/
├── 2024
│   └── 02
│       └── 05
│           └── 13:07:1707134865
│               └── dbt.log
```

**Comment by PratikshaPanpaliya** [comment]
Hello @jtcohen6 I tried the way you suggested but it's not working. I want separate log file for each run 
I added log-path in dbt_project.yml 
log-path: 'logs/dbt_$(date +%Y/%m/%d/%H:%M:%s).log'
still I can't see log files
