### ISSUE TITLE
The initial snapshot creation does not seem to enforce "check" strategy on "unique_key"

### ISSUE THREAD

**Issue by eugene-nikolaev** [fishtown-analytics/dbt#2691]
### Describe the bug
Hello!
The initial snapshot creation does not seem to enforce "check" strategy on "unique_key".

### Steps To Reproduce

1. Create a source table:
```
create table snap_test(id integer, period date, data varchar);
insert into snap_test(id, period, data) values(1, '1/12/2019', 'blah1');
insert into snap_test(id, period, data) values(2, '2/12/2019', 'blah2');
insert into snap_test(id, period, data) values(3, '3/12/2019', 'blah3');
insert into snap_test(id, period, data) values(1, '1/12/2019', 'blah4');    -- NOTE: it's a key duplicate 
```
2. Run the snapshot:

```
{% snapshot snap_test %}

{{ config(
      target_schema='snapshots',
      unique_key='id_and_period',
      strategy='check',
      check_cols='all' ) }}

select
    id,
    period,
    data,
    CONCAT(id, billing_period) as id_and_period
from {{source('<schema_here>', 'snap_test')}}

{% endsnapshot %}
```

And it will go OK.

3. Run `dbt snapshot`
It will fail

### Expected behavior
Failure on point 2, on initial snapshot creation

### Screenshots and log output
```
(dbt-transformations) bash-3.2$ dbt snapshot -s snap_test
Running with dbt=0.17.1
Found 129 models, 135 tests, 4 snapshots, 0 analyses, 140 macros, 0 operations, 1 seed file, 54 sources

18:19:24 | Concurrency: 1 threads (target='dev')
18:19:24 | 
18:19:24 | 1 of 1 START snapshot snapshots.snap_test............................ [RUN]
18:19:26 | 1 of 1 OK snapshotted snapshots.snap_test............................ [SUCCESS 1 in 2.32s]
18:19:27 | 
18:19:27 | Finished running 1 snapshot in 7.39s.

Completed successfully

Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
(dbt-transformations) bash-3.2$ 
(dbt-transformations) bash-3.2$ 
(dbt-transformations) bash-3.2$ 
(dbt-transformations) bash-3.2$ 
(dbt-transformations) bash-3.2$ 
(dbt-transformations) bash-3.2$ dbt snapshot -s snap_test
Running with dbt=0.17.1
Found 129 models, 135 tests, 4 snapshots, 0 analyses, 140 macros, 0 operations, 1 seed file, 54 sources

18:19:40 | Concurrency: 1 threads (target='dev')
18:19:40 | 
18:19:41 | 1 of 1 START snapshot snapshots.snap_test............................ [RUN]
18:19:45 | 1 of 1 ERROR snapshotting snapshots.snap_test........................ [ERROR in 4.74s]
18:19:46 | 
18:19:46 | Finished running 1 snapshot in 9.19s.

Completed with 1 error and 0 warnings:

Database Error in snapshot snap_test (snapshots/snap_test.sql)
  100090 (42P18): Duplicate row detected during DML action
  Row Values: [1, 17908, "blah1", "12019-01-12", "442e7c125fb18f499f99def30f8e6cad", 1596813565121000000, 1596813565121000000, NULL]
  compiled SQL at target/run/smartly_data_mart/snapshots/snap_test.sql

Done. PASS=0 WARN=0 ERROR=1 SKIP=0 TOTAL=1
```

### System information
**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [ ] bigquery
- [x] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
(dbt-transformations) bash-3.2$ dbt --version
installed version: 0.17.1
   latest version: 0.17.2

Your version of dbt is out of date! You can find instructions for upgrading here:
https://docs.getdbt.com/docs/installation

Plugins:
  - bigquery: 0.17.1
  - snowflake: 0.17.1
  - redshift: 0.17.1
  - postgres: 0.17.1
```

**The operating system you're using:**
MacOS 10.15.5 (19F101)

**The output of `python --version`:**
Python 3.7.7

### Additional context
None

**Comment by jtcohen6** [comment]
@eugene-nikolaev Thanks for the detailed walkthrough! I believe this to be the expected behavior. I'll do my best to explain why.

When you declare a `unique_key` column, dbt expects that column to be a totally unique identifier for the snapshot query. A given value of that column should only ever appear once _at any point in time_. (The `merge` query that dbt runs on Snowflake/BigQuery will break—as it does in your example—if that assumption is untrue.) Obviously, the table is updated and other columns change over time; given the same the unique key, `dbt snapshot` is able to capture both the old and new values.

Here's the same scenario as the one you outlined above, with an important distinction: the `unique_key` is always unique at each point in time.

1. Create a source table:
```sql
create table snap_test(id integer, period date, data varchar);
insert into snap_test(id, period, data) values(1, '1/12/2019', 'blah1');
insert into snap_test(id, period, data) values(2, '2/12/2019', 'blah2');
insert into snap_test(id, period, data) values(3, '3/12/2019', 'blah3');
```
2. Define + run the snapshot:

```sql
{% snapshot snap_test %}

{{ config(
      target_schema='snapshots',
      unique_key='id_and_period',
      strategy='check',
      check_cols='all' ) }}

select
    id,
    period,
    data,
    CONCAT(id, period) as id_and_period
from {{source('<schema_here>', 'snap_test')}}

{% endsnapshot %}
```

```bash
$ dbt snapshot
```

3. Update the source table record
```sql
update snap_test set data = 'blah4' where id = 1;
```
or
```sql
truncate table snap_test(id integer, period date, data varchar);
insert into snap_test(id, period, data) values(2, '2/12/2019', 'blah2');
insert into snap_test(id, period, data) values(3, '3/12/2019', 'blah3');
insert into snap_test(id, period, data) values(1, '1/12/2019', 'blah4');    -- NOTE: it's a key duplicate 
```

4. Run `dbt snapshot`:
```
$ dbt snapshot
```

And you should end up with something like:

id | period | data | id_and_period | dbt_scd_id | dbt_updated_at | dbt_valid_from | dbt_valid_to
-- | -- | -- | -- | -- | -- | -- | --
1 | 2019-01-12 | blah1 | 12019-01-12 | 9a198c6901b441d9baa3bf0cb83f0809 | 2020-08-07 14:48:47 | 2020-08-07 14:48:47 | 2020-08-07 14:49:07
2 | 2019-02-12 | blah2 | 22019-02-12 | bb3254c51612d172912224d1a3365b63 | 2020-08-07 14:48:47 | 2020-08-07 14:48:47
3 | 2019-03-12 | blah3 | 32019-03-12 | e0c3cc65af2e302f31c7a985dd771b1a | 2020-08-07 14:48:47 | 2020-08-07 14:48:47
1 | 2019-01-12 | blah4 | 12019-01-12 | 412aa909ba9d1eb582d0fe734b78c94a | 2020-08-07 14:49:07 | 2020-08-07 14:49:07

Let me know if there's a piece of this that I've missed, or misunderstood.

**Comment by eugene-nikolaev** [comment]
@jtcohen6 thanks for so detailed answer and for awesome project!

Could you please give us also some recommendations?

The confusion here is that we were following this point:
```
Your models should then select from these snapshots, treating them like regular data sources.
As much as possible, snapshot your source data in its raw form and use downstream models to clean up the data
```
https://docs.getdbt.com/docs/building-a-dbt-project/snapshots/#snapshot-source-data

This didn't work well because the source was Google Sheets data which was populated manually. Therefore typing was loose and it contained some errors.

I think this is a good exclusion case to the best practices and should be solved as:
Google Sheets -> 3rd party extraction service -> DBT staging table (type casting + uniqueness tests) -> DBT snapshot.

Otherwise, e.g. if we have nightly extracts and using the `DBT snapshot -> DBT staging -> ...` approach, we could notice any issue second day.

Does it make sense?

**Comment by jtcohen6** [comment]
That's a fair reading! We do believe in snapshotting data as close to the source as possible. At the same time, further up in the [same docs](https://docs.getdbt.com/docs/building-a-dbt-project/snapshots/#ensure-your-unique-key-is-really-unique), we say:

> **Ensure your unique key is really unique**
> The unique key is used by dbt to match rows up, so it's extremely important to make sure this key is actually unique! If you're snapshotting a source, I'd recommend adding a uniqueness test to your source ([example](https://github.com/fishtown-analytics/jaffle_shop/blob/demo/master/models/staging/jaffle_shop/jaffle_shop.yml#L22)).

We should be clearer about saying that, when the best practices are at odds—because the source data does _not_ have a reliable unique identifier—it's more important to guarantee your `unique_key` than it is to snapshot directly at the source.

> `Google Sheets -> 3rd party extraction service -> DBT staging table (type casting + uniqueness tests) -> DBT snapshot -> ....`

I think this approach makes a lot of sense!

**Comment by eugene-nikolaev** [comment]
Thank you @jtcohen6!
