### ISSUE TITLE
Add --ignore_when_empty flag to snapshot-freshness for excluding empty sources

### ISSUE THREAD

**Issue by bashyroger** [fishtown-analytics/dbt#2750]
### Describe the feature
We automatically generate our sources.yml and the source tables based on source database information schema data.
**Depending on the source database (we have 600)**, it can happen that some of the source tables are empty.
When this happens, snapshot-freshness returns NULL, displayed as 2020 years out of date (now in 2020).
We would like to have an option to add a **--ignore_when_empty** flag then ignores sources with 0 rows

### Describe alternatives you've considered
Changing the error_after per table, but that is not doable as we don't know that by forehand

### Who will this benefit?
Everyone that wants to exclude empty sources from a freshness test

### Are you interested in contributing this feature?
I would like to / or I can try to let someone on my team to do it as they are the real coders. Though I guess this change cannot be that complex...

**Comment by jtcohen6** [comment]
Check out https://github.com/fishtown-analytics/dbt/issues/2428. I don't know what the right general answer is for empty tables: should they pass, warn, fail? There are arguments to make for ignoring them or for bringing them to attention. I hesitate to change the default behavior, which errs on the side of erroring.

Rather than add a CLI flag to configure this behavior, you could override the `default__collect_freshness` macro in your own project so that it reflects your desired outcome. In the linked issue, I advised changing the code to look like:

```sql
select
    case when count(*) = 0 then {{ current_timestamp() }} else max({{ loaded_at_field }}) end as max_loaded_at,
    {{ current_timestamp() }} as snapshotted_at
from {{ source }}
```

What do you think @bashyroger?

**Comment by bashyroger** [comment]
Hi @jtcohen6 , #2428 indeed provides the answer to what we want to do, so this issue can be closed.

Note that I did not suggest to change the **default** behavior though, my only suggestion was to add an additional / optional flag that overwrites the standard behavior.

While I agree that changing a standard macro works, my only fear in the pattern of _'adapting standard macros'_ is that when using this a lot, this for sure will have an impact on **forward** DBT compatibility...

**Comment by bashyroger** [comment]
Closing the issue...
