### ISSUE TITLE
Custom data test included in `dbt test --models source:*`

### ISSUE THREAD

**Issue by rrbarbosa** [fishtown-analytics/dbt#2783]
### Describe the bug
I'm following the recommendations from [discourse](https://discourse.getdbt.com/t/what-are-the-dbt-commands-you-run-in-your-production-deployment-of-dbt/366/2) to separate source and data/model tests. The flow looks like this:

```
dbt test --models source:*
dbt run 
dbt test --exclude source:*
```

The problem is that every custom test that has a `source()` and a `ref()` macro on it will match the first `test` call, and will fail because the models have not been built yet.

### Steps To Reproduce

After running `dbt init my_proj`, define a simple source:

```
sources:
  - name: public
    tables:
      - name: series_day
```

And a test:

```
select *
from {{ source('public', 'series_day') }}
inner join {{ ref('my_first_dbt_model') }}
```

Run: `dbt test --models source:*` to run the test custom test above.

### Expected behavior

No tests should run.

### System information
**Which database are you using dbt with?**
- [ ] postgres
- [x] redshift
- [ ] bigquery
- [ ] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
installed version: 0.17.0
   latest version: 0.18.0
```

### Additional context

The workaround is to replace all `source()` calls with `ref()`, implementing simple models for all needed sources. But that makes the pipeline brittle, as we need to catch these cases manually during code review.

**Comment by jtcohen6** [comment]
@rrbarbosa I appreciate this issue because it gets at the heart of two very different, very important concepts. Thanks for opening it!

### Test selection

Because of the way that test selector expansion works today, it's harder than it should be to exclude individual tests, or to exclude a test based on its own attributes rather than attributes of the resource it depends on. This is especially tricky for "multi-pronged" tests, where selector criteria matches one leg but not all. There's a lot of thinking about this in other issues currently open, and we're likely to revisit it later this year.

For now, the way to rewrite this would be a bit hacky:
```
dbt test --models source:*,test_type:schema
dbt run 
dbt test --exclude source:*,test_type:schema
```

This wouldn't handle `relationships` tests on a source with a referent to a model (or vice versa), but I really wouldn't recommend that, either. I'll say more about that below.

This isn't the first time I wished we had a `resource_type` node selector, so you could write this a bit more cleanly. There's also merit to a "not" operator.

### Modeling + design

The discourse post you linked is a Fishtown recommendation, so I think it's fair to answer with another Fishtown recommendation. You said it as much yourself:

> The workaround is to replace all `source()` calls with `ref()`, implementing simple models for all needed sources. But that makes the pipeline brittle, as we need to catch these cases manually during code review.

This is, in fact, our best practice. We [limit dependencies to raw data](https://docs.getdbt.com/docs/guides/best-practices/#limit-references-to-raw-data) and [create staging models](https://discourse.getdbt.com/t/how-we-structure-our-dbt-projects/355) that are 1:1 with our `sources`. We create a staging model for _every single source_, even if it feels unnecessary, because any additional upfront work is vastly outweighed by the potential downside of missing that dedicated gate for cleaning/renaming/recasting/deduping later on.

There is still a lot of value in using `sources` and in testing them. But we rarely (if ever) have models or data tests that select partly from models and partly from sources. If I were working in your project, I would rewrite the data test to be:
```
select *
from {{ ref('stg_series_day') }}
inner join {{ ref('my_first_dbt_model') }}
```

Then your (much simpler) command sequence will work the way you expect.

I'm going to close this issue because I don't foresee us making a dbt code change to resolve it, aside from the larger questions about test selection mentioned above (and discussed in other open issues).
