### ISSUE TITLE
dbt looking for pip install location, not brew install location

### ISSUE THREAD

**Issue by robertdefilippi** [fishtown-analytics/dbt#2792]
### Describe the bug
I previously installed `dbt` using `pip`, but switched to using `brew` because I need to control the version. Now, when I run a `dbt` command it looks for the `pip` version of `dbt` rather than the `brew` version. And, because the `pip` version is uninstalled it throws an error. 

I know the `brew` version has been installed and linked through the installation instructions [here](https://docs.getdbt.com/dbt-cli/installation-guides/macos), and the installation works because I can directly call `dbt` from the brew directory

```
# This works
$ /usr/local/bin/dbt run

```
I have a feeling a path is not being updated somewhere, but I'm not sure where.

### Steps To Reproduce
Install `dbt` through `pip`, then uninstall `dbt`, and install instead through `homebrew`.

### Expected behavior
Use the brew version of dbt after linking.

The command below should work and look for `dbt` in the correct install location after linking has been done
`$ dbt run`

### Screenshots and log output
```
$ dbt debug
> bash: /Users/me/.pyenv/shims/dbt: No such file or directory
```

### System information
**Which database are you using dbt with?**
- [ ] postgres
- [x] redshift
- [ ] bigquery
- [ ] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
 dbt --version
installed version: 0.17.2
```

**The operating system you're using:**

OSX

**The output of `python --version`:**

$ python --version 
Python 3.6.8

**Comment by max-sixty** [comment]
What does `which dbt` return?

**Comment by max-sixty** [comment]
What does `which dbt` return?

**Comment by drewbanin** [comment]
hey @robertdefilippi - I'm going to close this issue because this is related to your environment, not dbt! I don't think we could resolve this issue with a code change.

I too am curious what you see for `which dbt`, but will also point you to the `brew link` command. This command will overwrite the `dbt` script in your PATH, and should be the fix for the issue you're seeing here.

Can you try running:
```
brew link --overwrite dbt
```

If you installed a specific version of dbt with homebrew, you might instead need to run
```
brew link --overwrite dbt@0.18.0
```

I think something like that should get your `dbt` executable pointing to the right place!

**Comment by robertdefilippi** [comment]
Ah did not know about the `--overwrite` command. I'll try it out. Thanks @drewbanin
