### ISSUE TITLE
[BigQuery] Allow more recent versions of google-api-core?

### ISSUE THREAD

**Issue by max-sixty** [fishtown-analytics/dbt#2794]
### Describe the feature

Currently dbt-bigquery has [an upper limit of 1.16 on `google-api-core`](https://github.com/fishtown-analytics/dbt/blob/v0.18.1b3/plugins/bigquery/setup.py#L53). That release is from Jan of this year.

Would it be possible to loosen that?

While it's clearly not dbt's responsibility for us to be able to install arbitrary packages, here's an example where we can't instally `google-cloud-bigquery-datatransfer` because of this restriction:

```
[SolverProblemError]
Because no versions of google-cloud-bigquery-datatransfer match >2.0.0,<3.0.0
 and google-cloud-bigquery-datatransfer (2.0.0) depends on google-api-core (>=1.22.2,<2.0.0dev), google-cloud-bigquery-datatransfer (>=2.0.0,<3.0.0) requires google-api-core (>=1.22.2,<2.0.0dev).
And because dbt-bigquery (0.18.0) depends on google-api-core (>=1.16.0,<1.17.0), google-cloud-bigquery-datatransfer (>=2.0.0,<3.0.0) is incompatible with dbt-bigquery (0.18.0).
And because dbt (0.18.0) depends on dbt-bigquery (0.18.0)
 and no versions of dbt match >0.18.0,<0.19.0, google-cloud-bigquery-datatransfer (>=2.0.0,<3.0.0) is incompatible with dbt (>=0.18.0,<0.19.0).
So, because {repo} depends on both dbt (^0.18.0) and google-cloud-bigquery-datatransfer (^2.0.0), version solving failed.
```

Thanks as ever for the awesome product!

**Comment by drewbanin** [comment]
hey @max-sixty - sure thing - we'd be super happy to expand this version range as long as there are no breaking changes we'd need to account for. 

I scanned through [the changelog](https://googleapis.dev/python/google-api-core/latest/changelog.html) and i don't see anything too controversial in there. I'd be supportive of changing the upper bound to `1.21.0`.

We probably _do not_ want to set the upper bound to `<2.0.0` because breaking changes in libraries like this one can (and do) break older versions of dbt down the line. You buy it?
