### ISSUE TITLE
Rebuild only table materialisations

### ISSUE THREAD

**Issue by sminnee** [fishtown-analytics/dbt#2810]
### Describe the feature
I have about 90 models, 3 or 4 of which are materialised as tables.

An hourly cronjob is rebuilding everything with dbt run. However, it's rebuilding a lot of things that don't rebuild. On a single thread, it takes a few minutes, and on multiple threads I've had some reliability issues.

In addition to the execution time (which consumes a worker on our CI server for the duration of the job) there is also the availability issue - views are deleted during this rebuild step. Anyone wanting to query them at this time would be blocked.

It would be nice if there was a command to just refreshing those models materialised as tables (and maybe incremental datasets too). Ideally this could be done without dropping the dependent views (eg by replacing the data not the schema). Otherwise it would need to rebuild any views dropped by cascade.

### Describe alternatives you've considered
 * Run multiple threads to speed it up. Has reliability issues (which is tracked in a separate ticket)
 * Manually track which models need to be rebuilt and provide this as an explicit --models command. Because of the need to track dependent models this will be brittle, and risks models becoming unavailable after a refresh if one was missed.

### Additional context
I was wondering if:

 * there's a good reason why this feature doesn't exist
 * this feature exists but I couldn't find its documentation

### Who will this benefit?
people materialising a small subset of their models as tables

### Are you interested in contributing this feature?
I don't write much python but could give it a go. I also have a colleague who knows more python that I might rope in. ;-) To get me started, it would be helpful to understand which subsystems i would be modifying to make such a change.

**Comment by sminnee** [comment]
Having read #2806 I believe that this was the intended way of achieving this. But there's a bug.

That being the case, I'd flag that I looked but struggled to find documentation about this; I could provide a docs PR once I understand what the best practise is?

**Comment by jtcohen6** [comment]
Hey @sminnee, thanks for the detailed writeup!

> In addition to the execution time (which consumes a worker on our CI server for the duration of the job) there is also the availability issue - views are deleted during this rebuild step. Anyone wanting to query them at this time would be blocked.

Out of curiosity, are you running on Postgres or with bound views on Redshift? You should only experience significant view downtime if dbt needs to cascade-drop views that depend on tables it's trying to rebuild. In this scenario, the "rebuild tables only" strategy wouldn't work, since the views would be cascade-dropped and not recreated.

Otherwise, I think I've got good answers for you. The issue you linked is indeed a bug, but it's entirely limited to the interaction of tests + `config.materialized:view`. So these should work just fine for you, as long as you're running the latest version of dbt (v0.18):

```
dbt run -m config.materialized:table config.materialized:incremental
dbt run --exclude config.materialized:view
```

The relevant docs here are on selection methods, specifically [the "config" method](https://docs.getdbt.com/reference/node-selection/methods/#the-config-method).

I'm going to close this issue, since I think you should be all set with the functionality currently available in dbt. I encourage you to comment here again if that's not quite what you're looking for.
