### ISSUE TITLE
test dbt with Python 3.9

### ISSUE THREAD

**Issue by gshank** [fishtown-analytics/dbt#2822]
Hologram pull request https://github.com/fishtown-analytics/hologram/pull/37 updates hologram to be compatible with Python 3.9. Update tox.ini with Python 3.9 targets and ensure that the test suite passes.

**Comment by jtcohen6** [comment]
If we determine that adding python 3.9 support is as simple as bumping the hologram dependency, we should release a new patch version (v0.18.2) that is compatible with py39, in addition to making v0.19.0 compatible. This will be a boon to users who cannot immediately upgrade to v0.19 because of breaking changes and deprecations.

**Comment by jtcohen6** [comment]
We won't be able to "officially" support python 3.9 for the core dbt distribution until `snowflake-connector-python` adds support for 3.9, by way of `pyarrow`: https://github.com/snowflakedb/snowflake-connector-python/issues/562

As such, we won't be releasing a py39-compatible patch (v0.18.2). In the meantime, we'll make dbt-core work with python 3.9, and users of specific plugins will be able to `pip install dbt-{adapter}` within 3.9 environments. Hopefully it will _just work_, unless that plugin has other dependencies that are not yet compatible (as in the case of dbt-snowflake).

**Comment by MartinNowak** [comment]
> As such, we won't be releasing a py39-compatible patch (v0.18.2). In the meantime, we'll make dbt-core work with python 3.9, and users of specific plugins will be able to `pip install dbt-{adapter}` within 3.9 environments. Hopefully it will _just work_, unless that plugin has other dependencies that are not yet compatible (as in the case of dbt-snowflake).

It seems that hologram wasn't updated as part of that v0.18.2 release, thus I'm still running into #2865 (duplicate of *this* issue) with Python 3.9.

The fix was merged with https://github.com/fishtown-analytics/hologram/issues/34 and released with `hologram==0.0.12`, `dbt==0.18.2` requires exactly [`hologram==0.0.10`](https://github.com/fishtown-analytics/dbt/blob/v0.18.2/core/setup.py#L73).

As a workaround I've been able to use dbt 0.18.2 with the newer hologram 0.0.14 for our dbt-bigquery use cases.

**Comment by smitthakkar1** [comment]
Is dbt 0.20 compatible with Python 3.9.4 ?

**Comment by jtcohen6** [comment]
@smitthakkar1 Yes! Are you seeing any issues using the two together?

**Comment by smitthakkar1** [comment]
No, I just wanted to confirm before I go ahead with it. Thanks for
answering my question.

Thanks
