### ISSUE TITLE
DBT Cloud API: HTML Response

### ISSUE THREAD

**Issue by grahamcarman** [fishtown-analytics/dbt#2836]
Hi! At my company we are big fans of DBT, and we are using DBT cloud. 

We use Airflow to trigger a job every hour (via DBT Cloud API). 

Every so often (once /day for the last couple days) the API DOES NOT return JSON, but instead returns an HTML document:
![image](https://user-images.githubusercontent.com/31483215/96275406-ef548b00-0f8e-11eb-886e-62a9815e1887.png)

The funny thing is that this is considered an error in Airflow, so it gets us all ready to address some problem with the DBT run. However, each time we have looked into it in DBT Cloud, we find that the DBT job was actually triggered properly. So this is an unexpected response that does not properly reflect the status of the DBT job trigger.

**Comment by jtcohen6** [comment]
Hey @grahamcarman, glad to hear that you're getting a lot out of dbt!

Since this is specific to dbt Cloud and its API, could you open a support ticket via Intercom? ("Contact Support" in the screenshot, or chat bubble in the top-right corner.) I want to make sure your request reaches the right folks.
