### ISSUE TITLE
dbt seed does not handle blanks as NULLS (for int fields)

### ISSUE THREAD

**Issue by alittlesliceoftom** [fishtown-analytics/dbt#2843]
### Describe the bug
A clear and concise description of what the bug is. What command did you run? What happened?

Running `dbt seed -s mycsv` leads to this error: 

 ('22018', "[22018] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Conversion failed when converting the varchar value 'None' to data type int. (245) (SQLExecDirectW)")

### Steps To Reproduce
In as much detail as possible, please provide steps to reproduce the issue. Sample data that triggers the issue, example model code, etc is all very helpful here.

Below .csv fails with Errror
Id, col
1,1
2,NULL
3,3

Below .csv fails with Errror
Id, col
1,1
2,
3,3

Below .csv passes
Id, col
1,1
2,2
3,3

### Expected behavior

Blank columns that Python inteprets as Nones are interpreted as NULLS by DB 

### Screenshots and log output
If applicable, add screenshots or log output to help explain your problem.

### System information
**Which database are you using dbt with?**
dbt-synapse adapter

**The output of `dbt --version`:**
```
installed version: 0.18.0
   latest version: 0.18.1
```

**The operating system you're using:**
Windows
**The output of `python --version`:**
Python 3.8.6

**Comment by jtcohen6** [comment]
Hey @alittlesliceoftom, have you tried setting the [`column_types`](https://docs.getdbt.com/reference/resource-configs/column_types/) config in dbt_project.yml?
```
seeds:
  my_project:
    my_seed:
      +column_types:
        col: int
```

If that doesn't work, you could work around this issue by setting the type to `varchar` and then nullif and casting in a staging model.

In general, I believe this issue is specific to Synapse and the dbt-synapse adapter. I don't think there's a code change we can make in this repository, and as such I'm going to close the issue. I'd recommend re-opening in that plugin's repository to investigate enhancements to type inference in the synapse implementation of the seed materialization.
