### ISSUE TITLE
Configure local timezone in DBT cloud

### ISSUE THREAD

**Issue by bashyroger** [fishtown-analytics/dbt#2846]
### Describe the feature
When scheduling jobs in DBT cloud, we would like to set them up according to our local time-zone / also taking account daylight savings. Having to deal with UTC offsets is not very scheduling-friendly.

### Describe alternatives you've considered
Deal with the UTC offset

### Additional context
The interesting bit is the daylight saving part / an UTC offset is not constant throughout the year

### Who will this benefit?
Everyone using the DBT cloud scheduler

**Comment by jtcohen6** [comment]
@bashyroger This is a totally reasonable request. I just had a scheduling snafu of my own because of misaligned daylight savings switches across countries.

Could you open a ticket with dbt Cloud support to make the same feature request? I'm going to close the issue here, just because it's not a code change we can make in this repository.

**Comment by drzorrz** [comment]
Hi, why this has been closed - what is the rationale of abandoning this suggestion?

**Comment by KoenVerbeeck** [comment]
> Hi, why this has been closed - what is the rationale of abandoning this suggestion?

Curious as well. Any decent scheduler has timezone support .

**Comment by kcd83** [comment]
Can we reopen this please? @jtcohen6  DBT may not get notifications on closed tickets ... so perhaps we duplicate it

There are more DBT use cases where the output of a job is customer facing which a great example why it has to be timezone aware for daylight savings
