### ISSUE TITLE
Merge code should compare non-key columns to determine rows to update

### ISSUE THREAD

**Issue by naterinke** [fishtown-analytics/dbt#2847]
### Describe the feature
Currently the generated merge code updates every row in the target table if the unique key exists in the source.  It would be preferable to also compare the the non-key columns to see if they have changed before blindly updating the target row. 

Example of the current generated code:
```
merge into [Schema].[Target Table] as DBT_INTERNAL_DEST
        using [Schema].[Target Table]__dbt_tmp as DBT_INTERNAL_SOURCE
        on 
            DBT_INTERNAL_SOURCE.PRIMARY_KEY = DBT_INTERNAL_DEST.PRIMARY_KEY
      
   when matched then update set
        "Attribute_1" = DBT_INTERNAL_SOURCE."Attribute_1"
	   ,"Attribute_2" = DBT_INTERNAL_SOURCE."Attribute_2"
	   ,"PRIMARY_KEY" = DBT_INTERNAL_SOURCE."PRIMARY_KEY"
...

```
Suggested Code:
```
merge into [Schema].[Target Table] as DBT_INTERNAL_DEST
        using [Schema].[Target Table]__dbt_tmp as DBT_INTERNAL_SOURCE
        on 
            DBT_INTERNAL_SOURCE.PRIMARY_KEY = DBT_INTERNAL_DEST.PRIMARY_KEY
        WHERE (   coalesce(DBT_INTERNAL_DEST.Attribute_1, [Default Value]) <> coalesce(DBT_INTERNAL_DEST.Attribute_1, [Default Value]) 
	           OR coalesce(DBT_INTERNAL_DEST.Attribute_2, [Default Value]) <> coalesce(DBT_INTERNAL_DEST.Attribute_2, [Default Value])
		      )
			  
   when matched then update set
        "Attribute_1" = DBT_INTERNAL_SOURCE."Attribute_1"
	   ,"Attribute_2" = DBT_INTERNAL_SOURCE."Attribute_2"
	   ,"PRIMARY_KEY" = DBT_INTERNAL_SOURCE."PRIMARY_KEY"
...

```

### Describe alternatives you've considered
If people don't agree this should be the default behavior, I think it should at least be an optional configuration.

### Additional context
My use case for this is the following.
I am using a replication tool (Fivetran) to replicate tables from an Oracle database into Snowflake.  Tables are replicated in their entirety to a "staging" schema.  I am then using dbt to create star schema models, using the replicated tables as my source.  My dbt model for a simple dimension table may source from one or more tables, but only selecting a few columns (not every column from the source table(s)). It is very common that rows from the source table would be updated, but not affect the columns I am selecting from.  If I do an incremental materialization, using the Fivetran synced date (_FIVETRAN_SYNCED) to limit the query to only new/updated rows it includes these irrelevant record updates are also included.  This results in unnecessary updates on my target table.

### Are you interested in contributing this feature?
I would be happy to contribute myself.  I pulled open the macro code, but couldn't figure out all the pieces I need to make this work.

**Comment by jtcohen6** [comment]
Hey @naterinke! Thanks for the detailed writeup.

Following the approach you've outlined, I'm not convinced that there's a gain in database performance or human intuition:

- The database has to perform a more expensive merge join, comparing values of many more columns, with the potential benefit of updating fewer rows. In columnar databases like Snowflake, I _believe_ the performance cost of additional join keys outweighs the cost of batch-updating rows. (That said, if you've been able to do any benchmarking on this, I'd be very curious to see details!)
- Conceptually, the record _has_ been updated, reflected in the timestamp you're using in your `{% is_incremental() %}` condition. If you're only pulling in a subset of columns, it's likely that some updates will not be relevant to your model, but they're still updates. Writing extra logic to distinguish between relevant and irrelevant updates doesn't feel worth it: it's additional code complexity, with a very low upside—the record stays the same, instead of updating to be... also the same—and a significant downside—what if your logic causes you to _miss_ a relevant update by mistake?

### Local override

All that said, if this is the behavior you want in your own project, you can override `get_merge_sql` by creating a macro by the same name in your own project's `macros/` folder. You would want to change the logic from:

https://github.com/fishtown-analytics/dbt/blob/b188a9488a41ddcfd73c9291d425e41760ccd280/core/dbt/include/global_project/macros/materializations/common/merge.sql#L38-L44

To:

```sql
    {% if unique_key %}
    when matched AND
    {% for column in dest_columns %}
        DBT_INTERNAL_SOURCE.{{ column }} != DBT_INTERNAL_DEST.{{ column }}
        {{ "OR" if not loop.last }}
    {% endfor %}

    then update set
        {% for column in dest_columns -%}
            {{ adapter.quote(column.name) }} = DBT_INTERNAL_SOURCE.{{ adapter.quote(column.name) }}
            {%- if not loop.last %}, {%- endif %}
        {%- endfor %}
    {% endif %}
```

I'm going to close this because I don't see us making a code change to dbt, but I'd encourage you to keep commenting here with your thoughts + findings!

**Comment by naterinke** [comment]
Thanks for the help!  I appreciate you providing the code anyways.  That helps me understand it a bit better.  I did make one minor tweak to get it to run (FYI to anyone that wants to do the same).

`DBT_INTERNAL_SOURCE.{{ column.name }} != DBT_INTERNAL_DEST.{{ column.name }}`

My intention is not to improve performance, but to improve data accuracy.  To expand on my use case, I intend to add additional system columns to my fact and dimension tables that provide some data lineage and processing related information.  I will have a column that indicates the date the record was initially loaded into the table as well as a column that indicates the date it was last changed.  These columns help to facilitate "As-is" "As-was" reporting/analysis.  This is a common requirement in financial analytics projects I have worked on.  I am aware there are other ways to achieve the same functionality. Snowflake time travel, for example, allows for the same functionality, but 90 days isn't always sufficient, plus I prefer a solution that is database agnostic (to the extent possible).   

I did do a quick performance comparison between the two code versions.  I plan to do more robust testing when I have the time. I also want to add the coalesce into the comparision as well to measure it's impact.  FYI...


Code   Version | Warehous Size | Duration | Execution Time | Bytes Scanned | Updated Rows | Total Rows | Processing | Remote Disk IO | Synchronization | Initialization
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
Original | x-small | 1.1s | 616ms | 8.7MB | 29.8K | 1m | 76% | 14% | 5% | 5%
Updated | x-small | 1.3s | 600ms | 48.6MB | 29.8K | 1m | 57% | 29% | 0% | 14%
