### ISSUE TITLE
dbt adapter for Teradata

### ISSUE THREAD

**Issue by KrisCorrin** [fishtown-analytics/dbt#2856]
### Describe the feature
Here's a link to a gist with answers to the New Adapter Information Sheet questionnaire, for Teradata (16.20 onwards)

https://gist.github.com/KrisCorrin/b1b5ef6d418b4b8d75889d2602a30a80

### Describe alternatives you've considered
N/A

### Additional context
N/A

### Who will this benefit?
Teradata customers

### Are you interested in contributing this feature?
Yes

**Comment by jtcohen6** [comment]
Hey @KrisCorrin, thanks for writing this up!

To be honest, the "new adapter information sheet" is fairly out of date, as is the rest of what's in the GitHub wiki. https://github.com/fishtown-analytics/dbt/wiki/New-Adapter-Information-Sheet

As of dbt v0.13.0 (March 2019), we introduced a "plugin" mechanism for [building new adapters](https://docs.getdbt.com/docs/contributing/building-a-new-adapter/). We don't have the capacity to build new adapters on our own, but we can make high-leverage changes to dbt-core that better support community members who maintain adapter plugins.

I'm going to close this issue, because it's out of scope for dbt-core, but I'd encourage you to either:
- give it a go! bootstrap a dbt-teradata adapter using [this script](https://github.com/fishtown-analytics/dbt/blob/dev/octavius-catto/core/scripts/create_adapter_plugins.py) and by checking out the [other open source plugins](https://docs.getdbt.com/docs/supported-databases/)
- post the questionnaire in [discourse](https://discourse.getdbt.com/) as a call for support and/or contribution
