### ISSUE TITLE
DBT Snapshot filling in dbt_valid_to for most recent record

### ISSUE THREAD

**Issue by skamalgl** [fishtown-analytics/dbt#2871]
### Describe the bug
We have a bug where a DBT Snapshot model is populating a timestamp in the column "dbt_valid_to" for the most recent record of a unique key. This happens for around 70k unique keys out of 20 million in our table. The snapshot is using the timestamp strategy. The row is not deleted in the source table. 

### Steps To Reproduce
**config**
`config(

unique_key='ID',

target_database='SNAPSHOT' if target.name != 'dev' else 'SNAPSHOT_DEV',

target_schema='SCHEMA',

strategy='timestamp',

updated_at='ROW_UPDATED_AT',

)`

**DBT Version**
It has been running on 0.16.0 but just upgraded to 0.18.0 in dbt cloud to see if it helps.

### Expected behavior
The most recent row per unique key should have a NULL value in the dbt_valid_to column. When this gets populated it does two things:
1. It looks like the record is no longer active when it is
2. The update / insert logic when using snapshots seem to ignore this unique key now. When the record changes, no new entries occur

### Screenshots and log output
**Sql Query**
`
SELECT id
	,dbt_valid_from
	,dbt_valid_to
FROM WAREHOUSE.SCHEMA.TABLE
WHERE id = 4251182
ORDER BY dbt_valid_to DESC`

**Screenshot of Output**
![image](https://user-images.githubusercontent.com/62021867/98377478-d92c6e80-2012-11eb-92ee-5caa9cdc6161.png)

### System information
**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [ ] bigquery
- [x] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
0.16.0
```

**The operating system you're using:**
DBT Cloud
**The output of `python --version`:**
This happens in dbt cloud

**Comment by jtcohen6** [comment]
@skamalgl It sounds like this is an error you experienced while using dbt v0.16.0. In that case, this bug sounds a lot like the one outlined in https://github.com/fishtown-analytics/dbt/issues/1884, which we resolved in v0.17.0. If that's so, upgrading is the ultimate resolution here.

That doesn't get you out of a tricky spot with the handful of records that were errantly updated without a corresponding insert. In that regard, your recourses are:
- Correct those records manually by nullifying the `dbt_valid_to` of the most recent record.
- Try out / wait for dbt v0.19.0 (currently in beta), which has [an optional config](https://next.docs.getdbt.com/docs/building-a-dbt-project/snapshots/#snapshot-configurations) for detecting hard-deleted records, both when they go missing and when they "revive." In this case, because there is no record with unique identifier `4251182`, its next detection would be considered a revival.

I'm going to close this issue as a duplicate, but please continue to comment here if I've missed or misunderstood an important piece of this.
