### ISSUE TITLE
Feature-flag - allow non disruptive jinja syntax

### ISSUE THREAD

**Issue by amigold** [fishtown-analytics/dbt#2873]
### Describe the feature
Since not all editors support jinja-sql but we want all analysts and developers to use DBT, I suggest a flag to allow non disruptive jinja syntax by using multi-line comments in SQL in addition to a simple pre-processing function to prepare the raw SQL strings before comilation

How would this syntax look like? Very simple - just wrap jinja tags with `/*dbt` and `*/`.
The `/*dbt` is there to help distinguish between actual multiline comments and dbt code.

Examples:

1. 
```
/*dbt
{{
    config(
        materialized='table'
    )
}}
 */
```

2. 
```sql
STRONG_REFERENCE_TABLE /*dbt {{ref('some_model')}} */ alias
```

3.
```
/*dbt
{% if is_incremental() %}
WHERE
    updated_at > (
    SELECT max_updated_at FROM {{self}})

{% endif %}
 */
```

### Who will this benefit?
Developers and analysts who do not use SQL editors that support jinja-sql (Atom and VSCode)

### Are you interested in contributing this feature?
Would love to

I essentially already built this simple function and tested it internally with our analysts. See here https://github.com/amigold/dbt/commit/6465d36146062f5f106e46a60e2841fdf9a5ad2a

**Comment by amigold** [comment]
Forgot to mention - this way we can keep using existing linters and code assistance by editors such as Datagrip while still enjoying the full capabilities of DBT

**Comment by jtcohen6** [comment]
@amigold Based on your second comment, when you say text editor support for jinja-sql, I take it to mean things like:
- syntax highlighting
- snippets and auto-completion
- linting and auto-formatting
- the ability to compile + run Jinja-fied SQL from a model file

Across the board, I think the real answers here are text editor plugins (as they exist for Atom and VSCode today), better dedicated development environments (i.e. the dbt Cloud IDE), and standalone linters / formatters than can handle Jinja + SQL (e.g. [SQLfluff](https://github.com/sqlfluff/sqlfluff), or [a longtime hobby horse of our own](https://github.com/fishtown-analytics/dbt-sql-formatter)).

I hesitate to add more regex steps within dbt itself, especially as we think about how to speed up the parsing and compilation of files in large dbt projects. That said, I'm also not sure this is strictly necessary. Since Jinja doesn't respect SQL comments, anyway, some of what you've outlined is already possible today, either verbatim or with slight modification:

1.
```sql
/*
{{
    config(
        materialized='table'
    )
}}
*/
```

3.
```sql
/* {% if is_incremental() %} */
WHERE
    updated_at > (
    SELECT max_updated_at FROM {{self}})
/* {% endif %} */
```

**Comment by amigold** [comment]
Thanks for responding so quickly, @jtcohen6, and for the explanation. I understand your reasons and logic so I will close this issue.

We just recently just switched to using DBT in our pipeline (it is great, btw. We owe you a lot) but are heavy Datagrip users. That's why I was looking for a quick way to get the best of both worlds without forcing our analysts (too much) out of their comfort zones and editors)

The comments do indeed work but the only thing that isn't - is the table reference trick. Perhaps there is another way you can think of to support that?

**Comment by jtcohen6** [comment]
Heard, I know there are other community members using Datagrip. I think there'd be interest in developing a dbt plugin that can support those nice-to-haves alongside Jinja.

In the meantime, if you want to embed `ref`s in a SQL comment, I _guess_ you could use an approach like the one below, though I think it's much hackier than is justified for this purpose.

Override the `ref` macro in your project:
```sql
{% macro ref(model_name) %}
  {% set rel = builtins.ref(model_name) %}
  {% set within_comment = '*/' ~ rel ~ '/*' %}
  {% do return(within_comment) %}
{% endmacro %}
```

Then in your model file:
```sql
with my_cte as (
  select * from /* {{ref('some_model')}} */
  where filter = 1
),
```

Which compiles to:
```sql
with my_cte as (
  select * from /* */ dbt_you.some_model /* */
  where filter = 1
),
```
