### ISSUE TITLE
Dependencies implied by relationship test should be included when selecting model parents

### ISSUE THREAD

**Issue by ruisun-pep** [fishtown-analytics/dbt#2874]
### Describe the feature

When plus sign is used in node selector to select parent models of another model, implied model dependencies in relationship / referential integrity tests should be included along with explicit dependencies from using `{{ ref() }}`. Otherwise those tests won't be able to run.

### Describe alternatives you've considered

- Build the whole project
The disadvantage is obvious for this approach - inefficiency, time consuming, etc.

- Manually include those implied dependencies in node selector
The disadvantage is obvious for this approach - manual, error-prone, cannot be automated, etc.

- Deferral feature recently introduced in dbt.
Deferral in dbt will delegate reference to any model that is not currently selected to those already built in previous run, usually the production database. There is an issue of stale data if not timed correctly - if table a has a relationship test to table b, and table b has changed since last batch run.

- Forced dependency
There is a way to force dbt to consider model A as the parent of model B by writing the macro call to `{{ref('a') }}` in a comment within the model source. However, this process is manual, ungraceful, and causing unnecessary burden to developers both initially creating it as well as maintaining it. It is even less desirable when dbt has the potential to do this automatically (because it already builds the manifest and graph).

### Additional context

This feature is not database specific and is applicable to any vendor.

### Who will this benefit?

- Continuous integration
In a CI/CD setting, a developer would like to build models they made changes to / newly added to the project, and they want to be able to run the tests for that model, including referential integrity tests. With this feature, CI system can automatically build both explicit and implied dependencies for that model, without suffering the down side of alternatives mentioned above.

### Are you interested in contributing this feature?

We already implemented this feature internally and would like to see the response from community to decide if we are going to release this to the public.

**Comment by jtcohen6** [comment]
Thanks for the detailed writeup, @ruisun-pep! I'll share some of my thoughts below on (a) why I don't think this is desirable behavior, and (b) how I see it being possible all the same, without any changes to dbt code.

### Recommendation

My personal take: I don't think it makes a lot of sense to test referential integrity in a CI environment. Data sources in sandbox environments are frequently limited, sampled, or fabricated; `relationships` tests already result in a lot of false alarms. I think it's _especially_ weird in a case where you've only built one "leg" of a `relationships` test. Which other leg would you test against? The prod version?

So in general, my recommendation is to exclude `relationships` tests from CI jobs:
```bash
dbt run -m state:modified
dbt test -m state:modified --exclude test_name:relationships
```
(N.B. `--state` and `--defer` are implied here, since their inclusion will vary based on your deployment environment.)

### Alternative approach

All that being said, from the pure standpoint of node selection, it is possible to do the thing you're after. I don't think it would make sense for `+model_a` to include `model_b` on the basis of their sharing a child (the `relationships` test), since `model_b` is not truly a parent of `model_a`. Instead, I think it makes sense for `model_b` to be included in the criteria of `@model_a` ([the @ operator](https://docs.getdbt.com/reference/node-selection/graph-operators/#the-at-operator), i.e., all children of `model_a` and other parents of those children). Indeed, it is.

As such, you could choose to still run `relationships` tests in your CI job—as long as you ensure that both parents of each `relationships` tests are always built, should one of those parents be modified:

```bash
dbt run -m state:modified @state:modified,1+test_name:relationships
dbt test -m state:modified
```

Note that there is a small risk of extra baggage here: if a model satisfies both conditions independently, but not together, it will be included in your selection criteria even though it isn't strictly necessary. I think the downside here is pretty small.

See caveats to state comparison: [prerelease docs](https://next.docs.getdbt.com/reference/node-selection/state-comparison-caveats), https://github.com/fishtown-analytics/docs.getdbt.com/pull/453

**Comment by jtcohen6** [comment]
I'm going to close this issue. I believe the specific thing requested—the ability to run a given model's co-parent, on the basis of its being a common ancestor of a relationships test—is better captured by the `@my_model` operator than the `+my_model` operator.

I'd be open to conversation about adding a depth specification to the `@` graph operator, since that's where my mind went after considering this issue at length. I don't know exactly how it should work, though: Would `1@my_model` run:
- only the first-order parents of `my_model`, or all its parents?
- only the first-order children of `my_model`, or all its children?
- only the first-order parents of those children, or all their parents?

I'd lean toward "only first-order" in all three cases, but it feels complex enough that I'd want to think through some concrete examples before deciding.

**Comment by ruisun-pep** [comment]
@jtcohen6 I have been thinking about this from time to time and I apologize for the late reply (and the need for you to re-read previous long posts).

I think my (former) confusion with the `@` operator was what type of dbt objects (model, test, etc.) would count as valid children (that will lead to their respective parents) when going through the graph. Since `dbt run` runs *models* only, I first thought tests would be excluded, which was not the case. This is significant in some cases (e.g. referential integrity test of productID in sales to productID in products, where sales does not have any downstream model). I would recommend that we document it in the graph section.

With regard to depth specification of `@` operator, I like the idea. I would like to propose something like `1@model_1@2`, which in my definition, means

> Up to first order parents of up to second order children of model_1.

This mimics the syntax of `+`, where `2+model_1` means up to second order parents of model 1 and `model_1+3` means up to third order children of model 1. Actually my mind defaulted to being able to use `@` both before and after a model name when I first learned about this operator, until dbt told me `model_1@` is illegal.

**Comment by jtcohen6** [comment]
> It seems what `dbt run` does is first, select whatever node that qualifies the node selector, then, filter for models only. If so, I would recommend that we document it.

That's exactly right! I agree that documenting this feels critical. You've reminded me that I have an open issue on the docs repo to do just this: https://github.com/fishtown-analytics/docs.getdbt.com/issues/514.

> However, `dbt test` does not seem to follow the same algorithm - you can execute `dbt test -m model_1` without specifying `+` at the end. Technically speaking, tests are the children of that model, so the above logic should return nothing for `dbt test` to execute. I know using `dbt test -m model_1` to test model 1 is the naturally expected behavior from users, but it really isn't logically sound. I would love to hear your thoughts and how I can reconcile the different graph behaviors by dbt.

Again, you've nailed it. It actually follows the same algorithm as above, with one important addition: For `dbt test`, and only `dbt test`, dbt also selects any test that directly depends on a selected resource. You could think of this as an implicit `+1` for tests _only_: I've selected a model to test, therefore I must really be selecting the first-order test children of that model. We support this because it's expected and intuitive behavior, even though it throws a bit of a monkey wrench into understanding selection criteria and logical operators in the abstract. 

Let's keep thinking about the nth-degree `@` operator.

**Comment by alexeyegorov** [comment]
As I was looking for the same issue, I came across another option that one can pass to DBT: [``indirect-selection-mode``](https://docs.getdbt.com/reference/node-selection/test-selection-examples?indirect-selection-mode=buildable#indirect-selection). You can select between:

- eager (default)
- buildable
- cautious
- empty

For me, `buildable` was enough, while cautious could go a bit further. :)
