### ISSUE TITLE
use downstream config to compile ephemeral models

### ISSUE THREAD

**Issue by lambert-lemanh-cko** [fishtown-analytics/dbt#2901]
### Describe the feature
I'm building ephemeral models with a lot of transformations. Ideally, I'd like to apply the` is_incremental()` statement within ephemeral models at specific places and logic to be applied or not based on downstream model configurations. I tuned the is_incremental() macro but wasn't able to extract downstream information when compiling ephemeral models.

### Describe alternatives you've considered
Being able to call downstream model configurations and relations in ephemeral models.

### Who will this benefit?
Would benefit anyone trying to replace CTEs by ephemeral models. 

### Are you interested in contributing this feature?

Is_incremental() tuned:

```
{% macro is_incremental(downstream_relation = none, downstream_config = none) %}
    {#-- do not run introspective queries in parsing #}
    {% if not execute %}
        {{ return(False) }}
    {% elif model.config.materialized == 'ephemeral' %}
    {{return(downstream_relation is not none
                  and downstream_relation.type == 'table' 
                  and downstream_config.materialized == 'incremental'
                  and not flags.FULL_REFRESH)}}
    {% else %}
        {% set relation = adapter.get_relation(this.database, this.schema, this.table) %}
        {{ return(relation is not none
                  and relation.type == 'table' 
                  and model.config.materialized == 'incremental'
                  and not flags.FULL_REFRESH) }}
    {% endif %}
{% endmacro %}
```

Original macro:

```
{% macro is_incremental(downstream_relation = none, downstream_config = none) %}
    {#-- do not run introspective queries in parsing #}
    {% if not execute %}
        {{ return(False) }}
        {% set relation = adapter.get_relation(this.database, this.schema, this.table) %}
    {% else %}
        {{ return(relation is not none
                  and relation.type == 'table' 
                  and model.config.materialized == 'incremental'
                  and not flags.FULL_REFRESH) }}
    {% endif %}
{% endmacro %}
```

Here I need to retrieve `downstream_relation `and `downstream_config ` each time an ephemeral model is compiled.

We could probably do this in a macro but it's not really user friendly.

**Comment by jtcohen6** [comment]
@lambert-lemanh-cko I've wanted to do exactly this on several previous occasions. I've felt this pain, wanting to split out incremental model logic into more modular components. That said, I don't think it's something we should do.

When a model wants to know something about one of its parents—a config value, the list of columns, the number of rows in the database, whatever—it should use the `ref()` function as its first pointer to that parent model. Whereas, if a model wants to know something about a _downstream_ model, and tries to `ref()` it, it would result in a circular dependency... as it should. Nodes in a DAG _cannot_ know anything about the nodes that depend on them downstream, else the graph is really cyclic.

So I think your options in this case are:

1. Wrap the ephemeral model reference with an `is_incremental()` filter within your incremental model, and see if your database optimizer is smart enough to push down the predicate, despite the (nested) CTEs. Ideally, it is.

2. Use a macro.

> We could probably do this in a macro but it's not really user friendly.

I hear you on preferring to define core model logic in model SQL, rather than a macro. Still, a macro accurately captures what you're after: you have model SQL that you want to repurpose, with dynamic inputs and modifications each time.

I'm going to close this issue, only because I don't see us making a dbt code change. I'm interested to keep the conversation going, and to see if we can come up with more compelling answers here.

**Comment by lambert-lemanh-cko** [comment]
Hi @jtcohen6,

Thanks for your answer. 

1. Yes unfortunately Snowflake is not smart enough to apply the filter at the beginning. It will end up scanning the whole dataset. 

2. Fair enough.

I was thinking of adding optional arguments in the {{ ref() }} macros to parse through information to upstream models. Or maybe if {% set %} could be defined in a model but reused in a upstream/downstream model.

**Comment by jtcohen6** [comment]
> I was thinking of adding optional arguments in the {{ ref() }} macros to parse through information to upstream models. Or maybe if {% set %} could be defined in a model but reused in a upstream/downstream model.

You can certainly use static run-level information, such as `vars` or `flags.FULL_REFRESH`, to inform models at every stage along the DAG. An upstream ephemeral model could check the full-refresh status to determine its filtering. But even that will miss some edge cases, such as if it's a standard (incremental) run, but the downstream incremental model's associated table is missing from the database.

**Comment by lambert-lemanh-cko** [comment]
> > I was thinking of adding optional arguments in the {{ ref() }} macros to parse through information to upstream models. Or maybe if {% set %} could be defined in a model but reused in a upstream/downstream model.
> 
> You can certainly use static run-level information, such as `vars` or `flags.FULL_REFRESH`, to inform models at every stage along the DAG. An upstream ephemeral model could check the full-refresh status to determine its filtering. But even that will miss some edge cases, such as if it's a standard (incremental) run, but the downstream incremental model's associated table is missing from the database.

Ideally we need a variable dynamically defined defined by the dowstream model and parse through the ephemeral model when compiled. Could we not have something like this:

`select * from {{ ref(ephemeral_model), config_arg = model.config, relation = this) }}`

{{config_arg}} and {{relation}} can then be used when compiling the ephemeral_model. This should also not create cyclic relationships.
