### ISSUE TITLE
Required var 'username' not found in config.

### ISSUE THREAD

**Issue by RoniFinTech** [fishtown-analytics/dbt#2904]
### Describe the bug
I defined `vars` in `dbt_project.yml` and I then try to access them inside `profiles.yml`. 
This is how I'm doing it:

`{{ var("username") }}`

but it complains:
```
 ERROR Runtime Error
  Compilation Error
    Could not render {{ var("user") }}: Required var 'user' not found in config:
    Vars supplied to <Configuration> = {}
```

### Steps To Reproduce
in `dbt_project.yml` add this var:

```
vars:
    username: 'my_user_name`
```
Then in `profiles.yml` call the var this way:

```
user: '{{ var("username") }}'
```

### System information
```
installed version: 0.18.1
   latest version: 0.18.1

Up to date!

Plugins:
  - bigquery: 0.18.1
  - snowflake: 0.18.1
  - redshift: 0.18.1
  - postgres: 0.18.1

```
OS: MacOS
Python: 3.7.9

**Comment by jtcohen6** [comment]
@RoniFinTech check out [the docs](https://docs.getdbt.com/reference/dbt-jinja-functions/profiles-yml-context/) on what's available in `profiles.yml`: 

> Available context variables:
> 
> * [env_var](https://docs.getdbt.com/reference/dbt-jinja-functions/env_var/)
> * [vars](https://docs.getdbt.com/reference/dbt-jinja-functions/var/) (Note: only variables defined with `--vars` are available)

Default values of `vars` that you set in `dbt_project.yml` will _not_ work for `profiles.yml`. Instead, you can set a default value inline:
```yml
user: '{{ var("username", "my_user_name") }}'
```
Or pass a value every time from the CLI:
```bash
dbt run --vars 'username: my_user_name'
```

In general, I recommend using environment variables for values in `profiles.yml`, since they tend to reflect the details of deployment environments.

**Comment by adeolaemmanuelmorren** [comment]
@jtcohen6 how would one use environment variables with the dbt command?
