### ISSUE TITLE
Cannot set query_tag through macro

### ISSUE THREAD

**Issue by magnusfurugard** [fishtown-analytics/dbt#2942]
### Describe the bug
Trying to set `query_tag` in `dbt_project.yml` through a macro doesn't work. Returns an error `'<macro>' is undefined`. 

### Steps To Reproduce
1. Create a macro which returns some text.
2. Use that macro as your `query_tag`, e.g:
```
models:
  query_tag: "{{ build_qtag('le_tag') }}" 
```

### Expected behavior
The tag should be set from the macro... :smile: 

### Screenshots and log output
```
Running with dbt=0.18.0
Encountered an error:
Compilation Error
  Could not render {{ build_qtag('le_tag') }}: 'build_qtag' is undefined
```

### System information
**Which database are you using dbt with?**
- [x] snowflake

**The output of `dbt --version`:**
```
installed version: 0.18.0
   latest version: 0.18.1

Your version of dbt is out of date! You can find instructions for upgrading here:
https://docs.getdbt.com/docs/installation

Plugins:
  - postgres: 0.18.0
  - redshift: 0.18.0
  - bigquery: 0.18.0
  - snowflake: 0.18.0
```

(Note: The same issue exists on `0.18.1`)

**The operating system you're using:** 
* Docker, `python:3.7`
```
root@fa939f48db3d:/dbt# uname -a
Linux fa939f48db3d 5.8.0-7630-generic #32~1607010078~20.04~383a644-Ubuntu SMP Thu Dec 3 19:14:47 UTC 2 x86_64 GNU/Linux
```

**The output of `python --version`:** `Python 3.7.9`

**Comment by jtcohen6** [comment]
Hey @magnusfurugard, it's not currently possible to call custom macros within YAML files. (That includes `dbt_project.yml` + all resource property files, like `models/*.yml`.) You can see the limited context available to `dbt_project.yml` ([docs](https://docs.getdbt.com/reference/dbt-jinja-functions/dbt-project-yml-context/)), with the exception of hooks, which are specifically late-rendered.

This is a technical limitation of dbt today, and we'd like it to be someday possible. Such an undertaking may require dbt to differentiate between a notion of "pure" macros (static input, static output) and "dirty" macros (ones that perform database introspection, or depend on the state of other objects).

In the meantime, your options are:
- Set `query_tag` as a Jinja expression in `dbt_project.yml`. You can use `target`, `env_var`, or CLI-provided `var` values.
- Set `config(query_tag = build_qtag('le_tag'))` in each of your models
- Override the built-in `set_query_tag()` macro, by creating a macro with the same name in your own project:

https://github.com/fishtown-analytics/dbt/blob/886b574987488b2e8d1809d07d692da6b611d8e5/plugins/snowflake/dbt/include/snowflake/macros/adapters.sql#L170-L179

I'm going to close this issue because it's not something we can fix in the near term, but I'm happy to answer questions and help you suss out a workaround.

**Comment by magnusfurugard** [comment]
Gotcha, so solving through `hooks` is the only way to solve it for the time being.

For anyone else who might google their way here, this is how I solved it:

```
# dbt/macros/make_query_tag.sql
{% macro make_query_tag(tag) -%}
    alter session set query_tag = 'some_static_prefix:{{ tag }}'
{%- endmacro %}

--

# dbt/dbt_project.yml
models:
    <resource>:
        +pre-hook: "{{ make_query_tag('howdy') }}"
```

**Comment by magnusfurugard** [comment]
> Be sure to check that the query tag set for the pre-hook session persists into the main model session.

Could you provide an example where this approach would break?

**Comment by jtcohen6** [comment]
We've seen issues where folks try to run `alter session` commands in a pre-hook, e.g. to change session parameters or the default timezone. Because dbt closes the connection once done, Snowflake may end the session, causing the model SQL to then run in a different session (with different session parameters, defaults, and tags).

Could you try this approach, and check the Snowflake query history to confirm that your model query ran with the tag you expect?

**Comment by magnusfurugard** [comment]
I ran a small integration test (~100 models) and the only anomaly I could find was that the initial query (the one which actually sets the `query_tag`). I'll let this run for a while and we'll see what happens.
