### ISSUE TITLE
Snowflake- syntax error line 1 at position 50 unexpected '@gmail.com'.

### ISSUE THREAD

**Issue by RoniFinTech** [fishtown-analytics/dbt#2952]
### Describe the bug
I run a macro using the DBT Python SDK and Snowflake and I send args 
`args='{username: first.last@gmail.com}'`

Then inside a macro I run the sql query:
`GRANT ROLE {{ prefix }}_ADMIN TO USER {{ username }};`

And this is the error I get:

`Encountered an error while running operation: Database Error
  001003 (42000): SQL compilation error:
  syntax error line 1 at position 50 unexpected '@gmail.com'.`

I do know that when the USER is an email, snowflake expects the whole email to be in double quotes.
I tried changing the args to 
`args='{username: "first.last@gmail.com"}'` and `args='{username: \"first.last@gmail.com\"}'`
but no help.

Any idea how to get the double quotes around the username after it resolves?

**Comment by jtcohen6** [comment]
Hey @RoniFinTech, this is pretty specific to a custom Jinja macro in your project. In the future, I'd recommend that you post a question like this [in stackoverflow and tag it `dbt`](https://stackoverflow.com/questions/tagged/dbt).

> the DBT Python SDK

Are you running dbt from the command line? Or [importing and invoking dbt as a python module](https://docs.getdbt.com/docs/running-a-dbt-project/dbt-api/)? We don't document or recommend the latter approach, since the python API is liable to change in any release.

If you want to run the macro from the command line exactly as you have it written, I believe this would work:
```
dbt run-operation my_macro --args 'username: "\"first.last@gmail.com\""'
```

Alternatively, you could add this quote-if-email handling as logic in your macro. I'd much rather handle special characters there, rather than needing to pass in the perfectly cased + quoted args:
```sql
{% my_macro(username) %}

    {% set user = '"' ~ username ~ '"' if '@' in username else username %}
    GRANT ROLE {{ prefix }}_ADMIN TO USER {{ user }};

{% endmacro %}
```

**Comment by RoniFinTech** [comment]
Thanks for the help!

The issue actually was on my side ( I was sending the email in lowercase but registered on snowflake in uppercase).
