### ISSUE TITLE
Raise a warning for required, but uninstalled packages

### ISSUE THREAD

**Issue by clrcrl** [fishtown-analytics/dbt#2999]
### Describe the feature
The error message for an uninstalled package comes straight out of the Jinja library:
```
Compilation Error in analysis scratch (analysis/scratch.sql)
    'dbt_utils' is undefined
```

This error message _is_ strictly true, but I think it might be worth taking the time to write a more explicit warning message for uninstalled packages

```
Warning: The following packages are listed as required in `packages.yml` but have not been installed
- dbt_utils

Run `dbt deps` to install these packages
```

Since we have the expected packages in `packages.yml` and the installed packages in `dbt_modules`, this should be possible, right? And not that hard?

Note: I've only got it as a warning so that the places where the package is referenced still causes an error, but I'm open to having this as an error instead

### Describe alternatives you've considered
Keep as is

### Who will this benefit?
Confused users

### Are you interested in contributing this feature?
No ty :)

**Comment by jtcohen6** [comment]
Love it. I'll take a look at some of the code paths involved, and see if this can be a good first issue

**Comment by EdwinTh** [comment]
FYI, I finally stumbled upon this issue when googling this error message, so yes, updated error message would be very much appreciated.

**Comment by jtcohen6** [comment]
The message for this is indeed coming from Jinja. The simplest version could just raise a more helpful compilation exception when Jinja returns an `UndefinedError` here:
https://github.com/fishtown-analytics/dbt/blob/749f87397ec1e0a270b2e09bd8dbeb71862fdb81/core/dbt/clients/jinja.py#L505-L506

For instance:
```python
    except jinja2.exceptions.UndefinedError as e:
        raise CompilationException(
            f'{e}. This can happen when calling a macro that is missing. ' \
            'Do you need to install a package dependency with `dbt deps`?'
        , node) from e
```
```
Encountered an error:
Runtime Error
  Compilation Error in model model_b (models/model_b.sql)
    'dbt_utils' is undefined. This can happen when calling a macro that is missing. Do you need to install a package dependency with `dbt deps`?
```

The downside of an approach this simple is that it isn't possible to distinguish between an undefined value that corresponds to a missing namespace/package, versus just a typo in the macro call (`{{ my_marco() }}` when you've defined `{% macro my_macro() %}`). So the message has to be a bit vague. The upside is that we don't need to make the Jinja context aware of the information in `packages.yml`.

I'm going to mark this a good first issue! And a nice chance to add a new [dbt exception](https://github.com/fishtown-analytics/dbt/blob/develop/core/dbt/exceptions.py) :)

**Comment by jaypeedevlin** [comment]
@jtcohen6 I'd love to jump onto this one in the next day or so.

Just to clarify, regarding:

> I'm going to mark this a good first issue! And a nice chance to add a new dbt exception :)

Will catching and reraising the exception be enough, or do I also need to modify `exceptions.py`?

**Comment by jtcohen6** [comment]
@jaypeedevlin Nice! Would love to have you contribute this :)

I think a new exception in `exceptions.py` is warranted, to wrap the error message above (rather than burying it deep in `clients/jinja.py`), and to name that we're doing something a little funky: `PossiblyUninstalledPackageError`?

After rereading this issue, the _absolute best_ version of this probably does the thing Claire mentioned in the original description, and checks to (as a very first step) to see if the contents of `dbt_modules` matches what's specified in `packages.yml`. That would involve touching more code-paths than this approach, which I think is good enough for 90% of times users see this `UndefinedError`.

**Comment by jtcohen6** [comment]
@jaypeedevlin I don't know why I thought this would be so tricky! At the prompting of your PR comment, I took a look down this code path, and I think it could be as simple as sticking a check right in `load_dependencies`:
https://github.com/fishtown-analytics/dbt/blob/1f33b6a74a614aa346824f16c5629e4d910d2106/core/dbt/config/runtime.py#L327-L334

```python
    def load_dependencies(self) -> Mapping[str, 'RuntimeConfig']:
        if self.dependencies is None:
            all_projects = {self.project_name: self}
            internal_packages = get_include_paths(self.credentials.type)
            # raise exception if fewer installed packages than specified packages
            package_dirs = self._get_project_directories()
            count_packages_specified = len(self.packages.packages)
            count_packages_installed = len(tuple(package_dirs))
            if count_packages_specified > count_packages_installed:
                raise_compiler_error(
                    f'dbt found {count_packages_specified} package(s) specified in packages.yml, '
                    f'but only {count_packages_installed} package(s) installed in {self.modules_path}. '
                    f'Run "dbt deps" to install package dependencies.'
                )
            project_paths = itertools.chain(internal_packages, package_dirs)
```

We can't match on names, since `self.packages.packages` is just the info from `packages.yml` (which may or may not match the package name, if it's a git repo name or local directory). We also can't check lengths for perfect equality, since it's possible that `count_packages_installed` will be greater than `count_packages_installed`, if the specified packages have package dependencies of their own. But I'd say this is a _lot_ better than nothing, and I'd be excited about pairing it with the kinder `UndefinedMacroException` you've got over in #3343.
