### ISSUE TITLE
Detailed log data

### ISSUE THREAD

**Issue by rpammeraal** [fishtown-analytics/dbt#3029]
It would be great to have access to the logs that DBT in the cloud creates. 
Currently, there is none.

**Comment by jtcohen6** [comment]
Hey @rpammeraal, it should be possible to access the debug-level logs that dbt Cloud creates when running a specific job, You can view the last 1000 lines in browser, or click the "Debug Logs" button to download the full logs:

<img width="863" alt="Screen Shot 2021-01-26 at 11 25 02 AM" src="https://user-images.githubusercontent.com/13897643/105833211-280df280-5fc9-11eb-8d70-4beecefa00ab.png">

If you're instead referring to debug-level logs when developing in the dbt Cloud IDE, those should available (as they are on the CLI) in the `logs/` folder, or whatever your [`log-path`](https://docs.getdbt.com/reference/project-configs/log-path/) is.

In any event, I'm going to close this issue because it relates to dbt Cloud, not dbt Core (the code in this repository). If you have questions about dbt Cloud, your best bet is to contact support from within the application.

**Comment by rpammeraal** [comment]
Hi Jeremy,

Thanks for your answer.
I am looking for a way to automate this, i.e. download this data
automatically.
The goal is to parse this data and put this into one or more database
tables, create reports and alerts on it, so we can proactively take action
if the population of a DBT model fails or take too long.
Is there a way to do this?

Thanks,
Roy

**Comment by jtcohen6** [comment]
@rpammeraal Interesting! I don't believe there's a way to do this using dbt Cloud today, but it touches on a few long-term, pie-in-the-sky conversations we've had about real-time log streaming or alerting via integrations with tools like DataDog, PagerDuty, etc.

In the meantime:
- dbt Cloud can alert you if a model fails to build
- All dbt Cloud jobs support a "run timeout" parameter
- For longitudinal analysis of model build times, dbt artifacts can play a role
    - For now, by downloading `run_results.json`, ingesting in your database, and modeling (see: [discourse](https://discourse.getdbt.com/t/using-dbt-artifacts-to-track-project-performance/1873) for inspiration)
    - Someday soon, via dbt Cloud's metadata API—something the team is actively developing. If alerting and observability are things you want to dive deeper into, consider joining the #beta-metadata channel in dbt Slack

**Comment by rpammeraal** [comment]
Yes! At Peerstreet, we continue to be amazed by the rich feature set that
DBT provides.
I personally just found out about the `test` feature in DBT. In the past I
created a mechanism that does exactly the same.
But yes, if we were able to get real time data on runtimes, it'll provides
us a way to proactively adjust models (add indexes et al) if they start to
become slow in population.

Thanks for the feedback Jeremy,

Roy

**Comment by pdr** [comment]
> In any event, I'm going to close this issue because it relates to dbt Cloud, not dbt Core (the code in this repository). If you have questions about dbt Cloud, your best bet is to contact support from within the application.

Ah I just saw this ... apologies. We will reach out to support as well. Thanks.
