### ISSUE TITLE
After a git merge I am unable to run any command because dbt cannot find any of the raw tables in my datasets(bigquery)

### ISSUE THREAD

**Issue by pedrostoren** [fishtown-analytics/dbt#3099]
### Describe the bug
After a git merge I am unable to run any command because dbt cannot find any of the raw tables in my datasets(bigquery).
It's as if it ignores the yml file with the sources. I am sure this yml file is well formatted. Everything was also working perfectly just before this git commit. 

This started to happen after I merged two branches(with the master branch of my old computer) on a git commit. I get the compile error: Compilation Error in model "x" depends on a source named  "y" which was not found. 

### Steps To Reproduce
In as much detail as possible, please provide steps to reproduce the issue. Sample data that triggers the issue, example model code, etc is all very helpful here.

### Screenshots and log output
If applicable, add screenshots or log output to help explain your problem.

### System information
**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [x] bigquery
- [ ] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
<output goes here>
``` 0.18.1

**The operating system you're using:**
MacOS
**The output of `python --version`:**
Python 2.7.16
### Additional context
Add any other context about the problem here.

**Comment by jtcohen6** [comment]
Hey @pedrostoren, I'm not sure what could have happened here, but it's hard to tell what's going on without being able to see the files in your project. If I had to guess, it sounds like the `sources` definition in a `.yml` file may have been deleted, overwritten, or moved as a result of the git operation.

Another thing to check: If your `.yml` file has multiple `sources:` blocks, then the second one "overwrites" the first one. (This is, for better or worse, a feature of YAML.) So for instances:
```yml
# models/my_sources.yml
version: 2

sources:
  - name: y
     tables:
       - name: one
       - name: two


# further down in same file
# this overwrites the sources block above
sources:
  - name: z
```
This would result in an error because `y` is not registered as a source:
```sql
# models/x.sql
select * from {{ source('y', 'one') }}
```
```
Compilation Error in model "x" depends on a source named "y" which was not found.
```

**Comment by pedrostoren** [comment]
Hi @jtcohen6! It was exactly that. Thank you so much. I did not thought of that as it was working perfectly fine before that git pull. Thanks again!!

**Comment by jtcohen6** [comment]
Glad you got to the bottom of this!
