### ISSUE TITLE
Issue with Third Party dbt plugins

### ISSUE THREAD

**Issue by namanjainzeta** [fishtown-analytics/dbt#3123]
I am working to create dbt plugin for clickhouse ,but my plugin doesn't show up when I execute dbt version ,I even tried installing other community plugins like dbt mssql but even they are not listed while executing dbt version .

I tried building from the source for a few versions but couldn't run and kept getting errors due to unsatisfied dependencies.

dbt --version output

installed version: 0.19.0
   latest version: 0.19.0

Up to date!

Plugins:
  - bigquery: 0.19.0
  - snowflake: 0.19.0
  - redshift: 0.19.0
  - postgres: 0.19.0

OS- MacOS Mojave (10.14.6)

Python version output-
Python 3.8.5

**Comment by jtcohen6** [comment]
Very cool @namanjainzeta! Did you have a chance to see this dbt-clickhouse plugin (https://github.com/silentsokolov/dbt-clickhouse), just added to the [docs site](https://docs.getdbt.com/reference/warehouse-profiles/clickhouse-profile/)?

> I am working to create dbt plugin for clickhouse ,but my plugin doesn't show up when I execute dbt version ,I even tried installing other community plugins like dbt mssql but even they are not listed while executing dbt version .

In order to show up in the plugin entries for `dbt --version`, each plugin must have a file `dbt/adapters/[name]/__version__.py`. See [dbt-spark](https://github.com/fishtown-analytics/dbt-spark/blob/master/dbt/adapters/spark/__version__.py), [dbt-presto](https://github.com/fishtown-analytics/dbt-presto/blob/master/dbt/adapters/presto/__version__.py) for instance.

> I tried building from the source for a few versions but couldn't run and kept getting errors due to unsatisfied dependencies.

Yes, this is a temporary issue: dbt on the default `develop` branch cannot be built from source while we work out a plan for new dependencies in v0.19.1. Sorry about that! You should be to resolve this by either:
- `pip install -r dev_requirements.txt`
- building from a tagged release of dbt ([v0.19.0](https://github.com/fishtown-analytics/dbt/releases/tag/v0.19.0) or [v0.19.1b2](https://github.com/fishtown-analytics/dbt/releases/tag/v0.19.1b2)) instead

**Comment by jtcohen6** [comment]
I'm going to close this, as dbt can now be built from source on the `develop` branch. Happy to help if you run into other issues during adapter development
