### ISSUE TITLE
DBT Deps Does not Install Redshift Package

### ISSUE THREAD

**Issue by bab354** [fishtown-analytics/dbt#3175]
### Describe the bug
My understanding is that DBT deps should install all packages in the packages.yml file. This does not seem to be happening.  
This package is not installed: https://github.com/fishtown-analytics/redshift

### Steps To Reproduce
See Screenshots

### Expected behavior
I expect all packages in my yml file to be installed which doesn't seem to be the case

### Screenshots and log output
packages.yml
![image](https://user-images.githubusercontent.com/25424439/111465018-f1667580-86f7-11eb-870f-c6f554334357.png)
when I run DBT deps
![image](https://user-images.githubusercontent.com/25424439/111465045-fdeace00-86f7-11eb-8785-0a3f727649d9.png)

trying DBT clean and running DBT deps again:
![image](https://user-images.githubusercontent.com/25424439/111465114-135ff800-86f8-11eb-853c-954c7646faba.png)

Then when I tried to run a model where we use that package:
![image](https://user-images.githubusercontent.com/25424439/111465296-499d7780-86f8-11eb-9247-7f55b9096307.png)

Here's how we fix, put Redshift as only package:
![image](https://user-images.githubusercontent.com/25424439/111465357-620d9200-86f8-11eb-9a71-57126913c718.png)

And then this works:
![image](https://user-images.githubusercontent.com/25424439/111465389-6c2f9080-86f8-11eb-9beb-d65f0567b570.png)

and then git  checkout

### System information
**Which database are you using dbt with?**
- [ ] postgres
- [ x] redshift
- [ ] bigquery
- [ ] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
``` 
0.19.0 (also happened before we upgraded 0.18.0)
```

**The operating system you're using:**
Ubuntu 18.04
**The output of `python --version`:**
python 3.7.5

**Comment by jtcohen6** [comment]
Hey @bab354, you just need to change your `packages.yml` file so that it's one `packages:` key followed by a continuous list. Like so:
```yml
packages:
  - package: fishtown-analytics/dbt_utils
    version: 0.6.2
  - package: fishtown-analytics/redshift
    version: 0.4.1
  - package: fishtown-analytics/codegen
    version: 0.3.1
  - package: calogica/dbt_expectations
    version: 0.2.7
```
By defining `packages:` multiple times, the subsequent definitions override the previous definitions. That's technically valid YAML, and maybe it's useful in certain cases, though I'm not sure which. Unfortunately, we don't do a great job of raising a warning or exception about this in our YAML parser today.

I'm going to close this, as I don't believe there's a required code change in dbt to resolve this particular error. I'd definitely welcome another issue with a focused proposal around improved warning- or exception-raising when duplicated YAML keys in the same file are detected.

**Comment by bab354** [comment]
ahh thank you @jtcohen6! Really appreciate the quick response and tbh that makes more sense, should have done more YML digging before opening
