### ISSUE TITLE
Snoflake SSO authentication from WSL2 (windows subsystem for linux)

### ISSUE THREAD

**Issue by rahul-ve** [fishtown-analytics/dbt#3183]
### Describe the feature
When snowflake config is set to  " authenticator: externalbrowser",  it fails with the below error when using dbt on WSL2. I am guessing this will be an issue on headless linux boxes.

Is there a way to print the URL, so it can be copied over to a browser to authenticate?

### Error

```
Initiating login request with your identity provider. A browser window should have opened for you to complete the login. If you can't see it, check existing browser windows, or your OS settings. Press CTRL+C to abort and try again...
  Connection test: ERROR

dbt was unable to connect to the specified database.
The database returned the following error:

  >Database Error
  390190 (08001): Failed to connect to DB: xxxxx.snowflakecomputing.com:443, There was an error related to the SAML Identity Provider account parameter. Contact Snowflake support.
```

**Comment by jtcohen6** [comment]
Hey @rahul-ve, this is a totally reasonable request. Unfortunately, I've got bad news: When `authenticator: externalbrowser`, dbt is doing little more here than passing a set of arguments along to `snowflake-connector-python`:

https://github.com/fishtown-analytics/dbt/blob/77c10713a325d2bee91d1822951ce5d91ccc3278/plugins/snowflake/dbt/adapters/snowflake/connections.py#L203-L214

The connector contains all the logic for grabbing the SSO URL, opening it in a browser, and logging the messages you're seeing above. The only recourse dbt has for you is an optional environment variable, `DBT_SNOWFLAKE_CONNECTOR_DEBUG_LOGGING`, which you can use to open the floodgates and pass along most (or all) of the connector's debug-level logging.

https://github.com/fishtown-analytics/dbt/blob/77c10713a325d2bee91d1822951ce5d91ccc3278/core/dbt/logger.py#L613

Again, I think this is a reasonable thing to want in environments that do not allow for opening browsers programmatically. You may want to open an issue in the `snowflake-connector-python` repo. If you're interested in looking further, I believe the relevant spot in their codebase is [here](https://github.com/snowflakedb/snowflake-connector-python/blob/b59814d0e6c3493d5c5aa975d4f1e5d090015344/src/snowflake/connector/auth_webbrowser.py#L111-L134).

I'm going to close this because the relevant code lives elsewhere, and I would like to avoid owning or vendoring any code that is better maintained by the Snowflake team.

**Comment by feluelle** [comment]
There is a PR out for open the url manually (host browser if you want to) and then continuing in the terminal.

See: https://github.com/snowflakedb/snowflake-connector-python/pull/883
