### ISSUE TITLE
Can't update jinja2 - version hardcoded

### ISSUE THREAD

**Issue by eugene-nikolaev** [fishtown-analytics/dbt#3186]
Hello!
### Describe the bug
Tried to resolve a security alert:
https://github.com/advisories/GHSA-g3rq-g295-4j3m
But `jinja2` version is harcoded here
https://github.com/fishtown-analytics/dbt/blob/77c10713a325d2bee91d1822951ce5d91ccc3278/core/setup.py#L62
So I was not able to bump up the version within my project.

### Steps To Reproduce
- I've just set this in Pipfile:
```
[packages]
jinja2 = ">=2.11.3"
```

### Expected behavior
jinja2 to be upgraded

### Screenshots and log output
not applicable

### System information
**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [ ] bigquery
- [ ] snowflake
- [X] other (specify: not relevant)

**The output of `dbt --version`:**
```
0.19.1-rc1
```
But basically it was merged in master in: https://github.com/fishtown-analytics/dbt/commit/626f8356015aea77410868bacd5724032473cf1f
so not only

**The operating system you're using:**
MacOS

**The output of `python --version`:**
`Python 3.7.7`

**Comment by jtcohen6** [comment]
Hey @eugene-nikolaev, dbt started tightly pinning `Jinja2` because of a breaking change in a patch release last year (April 2020, see https://github.com/fishtown-analytics/dbt/pull/2318/commits/626f8356015aea77410868bacd5724032473cf1f in https://github.com/fishtown-analytics/dbt/pull/2318).

Thanks for calling out the security advisory. We currently intend to bump the `Jinja2` pin (https://github.com/fishtown-analytics/dbt/pull/3077), along with all other pinned dependencies, before the next minor version of dbt.

**Comment by jtcohen6** [comment]
Resolved by #3077
