### ISSUE TITLE
Allow package seed configurations to apply to projects that use that package

### ISSUE THREAD

**Issue by emmacooperpeterson** [fishtown-analytics/dbt#3237]
### Describe the feature
It's entirely possible that this is already a feature, but I've been playing around with it for awhile / asked about it on StackOverflow and Slack, and so far I'm thinking it isn't currently doable.

I'd like to set some seed configurations in the `dbt_project.yml` of my package code, and have those configurations apply to all projects that use my package. Users of my package will have the ability to create their own .csvs to load with `dbt seed`, but I'd like to configure those seeds once at the package level. This is already possible for seed properties, but I haven't found a way to do it for seed configurations.

One specific example is configuring column length. If a package user runs `dbt seed` when their column has a maximum length of 25, the data will be loaded as type varchar(25). If they then add a longer string to that column, the following `dbt seed` fails. I'd like to specify the following in the package-level `dbt_project.yml`:

```
seeds:
  seed_name:
    +quote_columns: false
    +column_types:
          column_name: varchar(127)
```

I realize that for this particular particular example, the `--full-refresh` flag could help. However, there are cases where the inclusion of `--full-refresh` isn't necessarily desirable. I'd also like to be able to set `+quote_columns: false` and some specific post-hooks once at the package level, and have this apply to all projects that use the package.  

### Describe alternatives you've considered
The main alternative that I'm aware of is for package users to copy a chunk of seed configuration code into their individual project-specific `dbt_project.yml` files. This creates an unnecessary duplication of code across projects and also limits the package owner's ability to control those configurations.

### Additional context
Because this package is for internal use only, I'm able to make some very strong assumptions about these configurations up front. But I definitely recognize that applying package-level configs to all projects should not be the default.

### Who will this benefit?
I think this would benefit package maintainers and users by making it easier for package-wide configurations to be set one time.

### Are you interested in contributing this feature?
I don't think I have the right expertise, but I'd certainly be interested in the possibility of contributing depending on the implementation details.

**Comment by jtcohen6** [comment]
Thanks for the thoughtful writeup @emmacooperpeterson!

The short answer is: No, it isn't possible today for a dbt package to configure objects in the root project that installs it (or in a different installed package, for that matter).

```
 -----       ---------       --------------
| dbt | --> | package | --> | root project |
 -----       ---------       --------------
 ```

The inclusion of resources works from left to right, and so hierarchical configuration works from right-to-left: The root project can configure its own objects and anything further back/left: the objects in any installed package or the global dbt project of builtins. A package can configure its own resources, or resources in a package that _it_ installs, but it _cannot_ push its configurations forward/right to the root project's objects.

So by adding a configuration to your package like:
```
seeds:
  seed_name:
    +quote_columns: false
    +column_types:
          column_name: varchar(127)
```

That rightly says, All seeds in _this_ package will not quote their columns and will treat `column_name` as `varchar(127)`. But it cannot say those things about objects in _other_ projects, which it does not know anything about.

(This is conceptually similar to how overriding macros works, though there are a few ways they differ, mostly due to the complexity of adapter-level and dispatched macros.)

At the same time, I totally appreciate your use case: I'm all for limiting duplicated code (including configuration code) where possible. Turning off seed column quoting feels like a dbt-wide setting that you want to flip on or off on behalf of a team you're enabling. I do think it's the exception that a package author can know and say exactly how downstream projects ought to work, though: most package maintainer is about making the package as self-contained and configurable as possible, to work with whatever root project it may meet. So I think copy-paste may be your best bet here.

One potentially wacky option is to flip the script: Create a highest-level root project (really just a `dbt_project.yml` file), containing _just_ these default configurations, which then installs your team's other packages and applies/overrides these configurations once and for all.

I'm going to close this issue, because I don't think this is a change we can make given the conceptual model of dbt packages today. That said, I'm happy to keep thinking here about what the right approach for your use case is, given the constructs that exist today.

**Comment by emmacooperpeterson** [comment]
This is a super helpful response, thank you! I feel like I have a better understanding now of why this works the way that it does. I do think the idea of enabling this specific type of package where the maintainer is in a position to be super opinionated about each project is an interesting one, but there are definitely workarounds. I'm working on a script that generates the necessary config files for each project given a few inputs from the user – this solves my primary concern that the seed configuration might create confusion because my target users are not familiar with dbt.

Thanks again and have a great weekend!
