### ISSUE TITLE
Use optional dependencies in setup.py to optionally install the various connectors

### ISSUE THREAD

**Issue by c0state** [fishtown-analytics/dbt#3245]
### Describe the feature
Currently, it looks like `dbt` installs all the connectors by default, even if the user doesn't use some of them.

### Describe alternatives you've considered
The optional dependencies feature of setuptools (see: https://setuptools.readthedocs.io/en/latest/userguide/dependency_management.html#optional-dependencies) should be used to allow the user to explicitly declare which "connectors" they want

### Additional context
n/a

### Who will this benefit?
All users will benefit to some degree. For example, say I don't use snowflake, but yet all the snowflake dependencies are installed which are quite a bit.

### Are you interested in contributing this feature?
Will try to propose a PR, though I'm not an expert on setuptools.

**Comment by jtcohen6** [comment]
Hey @c0state! This is already possible today:
- [`pip install dbt-core`](https://pypi.org/project/dbt-core/): installs _just_ [`core/setup.py`](https://github.com/fishtown-analytics/dbt/blob/develop/core/setup.py)
- [`pip install dbt-postgres`](https://pypi.org/project/dbt-postgres/): installs [`plugins/postgres/setup.py`](https://github.com/fishtown-analytics/dbt/blob/develop/plugins/postgres/setup.py), which includes `dbt-core`
- [`pip install dbt-redshift`](https://pypi.org/project/dbt-redshift/): installs [`plugins/redshift/setup.py`](https://github.com/fishtown-analytics/dbt/blob/develop/plugins/redshift/setup.py), which includes `dbt-postgres` + `dbt-core`

The same goes for [`dbt-snowflake`](https://pypi.org/project/dbt-snowflake/) and [`dbt-bigquery`](https://pypi.org/project/dbt-bigquery/), and also for external plugins such as [`dbt-spark`](https://pypi.org/project/dbt-spark/) or [`dbt-synapse`](https://pypi.org/project/dbt-synapse/).

This has been the case since v0.13.0, when we fully split up dbt adapters into plugins. For historical reasons and backwards compatibility, [`pip install dbt`](https://pypi.org/project/dbt/) still includes all four of the "core" adapters, but you do not need to install them all—especially if one of the plugins has dependencies that make installation difficult.

**Comment by itajaja** [comment]
nice! I think just adding a couple lines here https://docs.getdbt.com/dbt-cli/installation#pip will be excellent :)

**Comment by jtcohen6** [comment]
PR to add instructions for installing a specific adapter: https://github.com/fishtown-analytics/docs.getdbt.com/pull/638
