### ISSUE TITLE
Add alias to test

### ISSUE THREAD

**Issue by brylie** [fishtown-analytics/dbt#3266]
It would be useful to be able to specify a specific "alias" for dbt tests.

Currently, test names in the `dbt test` output seem to be auto-generated. At times, these auto-generated test names can be lengthy or ambiguous, such as when running an `accepted_values` test with dozens of values. Furthermore, the automated test names explain the "how" but not necessarily the "why" of the test.

If we could add an "alias" to tests, we could add context and clarity to our test cases, such as applying TDD naming conventions.

I am available to help develop this feature.

**Comment by jtcohen6** [comment]
Hey @brylie, thanks for opening this issue! We're thinking a lot _right now_ about how to make tests clearer and more intuitive.

I see some overlap in this issue with a few other issues:
- From a technical perspective: test `unique_id` construction needs to work better—though that's more about guaranteeing uniqueness than guaranteeing readability (#3254).
- From the perspective of a dbt developer / stakeholder: tests should have the ability to dynamically construct clear descriptions (https://github.com/fishtown-analytics/dbt/issues/3249) and log messages which populate in stdout, dbt artifacts, and the dbt-docs site (https://github.com/fishtown-analytics/dbt/issues/2959). This is how I'm hoping we can get at the "why," even if the test's actual node name (`unique_id`) ends up being inscrutable.

I'm going to close this issue, not because I don't want to do this or think it's very important, but because I'm hopeful that one or more of the mechanisms above is going to provide us with a path there. I'd love to hear your thoughts on any of those issues!

**Comment by brylie** [comment]
Yeah, thanks. Those issues are in the same vein.

I looked for duplicates but wasn't sure what keywords to use.
