### ISSUE TITLE
RPC RAT - `dbt ls` benchmarking

### ISSUE THREAD

**Issue by iknox-fa** [fishtown-analytics/dbt#3269]
Benchmark the speed at which dbt can return results from `ls` in the RPC server to determine if this method of retrieving data meets the needs of the IDE team (response time < 1s)

Should be done and examined over different project sizes and will require wiring `ls` into the RPC server.

**Comment by jtcohen6** [comment]
@iknox-fa Just want to be extra-clear here: We need to determine the latency of running a `"list"` RPC command—which doesn't yet exist, but we (hope we) could make it exist pretty quickly. The key difference is that the RPC server keeps an internal manifest in memory, whereas the `dbt ls` CLI command is going to need to parse + reconstruct that manifest for every single invocation, adding to the perceived latency.

**Comment by iknox-fa** [comment]
@jtcohen6 Thanks for that.  THis is what I get for writing tickets without consulting the meeting notes.  Updated.

**Comment by jtcohen6** [comment]
One potential challenge that I ran into while (half) attempting this a few weeks ago: Currently, the list task expects to run in single-threaded mode:
https://github.com/fishtown-analytics/dbt/blob/cee0bfbfa2596520032b766fd1027fe748777c75/core/dbt/task/list.py#L45

We know that the RPC server has issues running in single-threaded / synchronous mode today. (https://github.com/fishtown-analytics/dbt/issues/3211). The simple answer, in the short term, may be to enable running `list` in multi-threaded mode. Ultimately, we would want a synchronous way to return results from a `list` method, because polling adds significant latency and orchestration complexity.

**Comment by iknox-fa** [comment]
Work complete and captured here:
https://www.notion.so/fishtownanalytics/RAT-notes-for-list-in-dbt-RPC-ccf332bb83ed4436bf1221ab009bcae0
