### ISSUE TITLE
Internal type error when using manifest from 0.18.0 in 0.19.1

### ISSUE THREAD

**Issue by walshie4** [fishtown-analytics/dbt#3319]
### Describe the bug
A clear and concise description of what the bug is. What command did you run? What happened?

Running the command `pipenv run dbt run --state /tmp/dbt.iMpUubo --defer -m state:modified --threads 10`

with the previous dbt cloud run's (of version 0.18.0 I believe) manifest.json being downloaded into that tmp directory.

```
+ pipenv run dbt run --state /tmp/dbt.iMpUubo --defer -m state:modified --threads 10
Running with dbt=0.19.1
Encountered an error:
Field "exposures" of type typing.Mapping[str, dbt.contracts.graph.parsed.ParsedExposure] is missing in dbt.contracts.graph.manifest.WritableManifest instance
```

### Steps To Reproduce
In as much detail as possible, please provide steps to reproduce the issue. Sample data that triggers the issue, example model code, etc is all very helpful here.

See above

### Expected behavior

This error message left me with little to do other than dig into the dbt source code, ideally we can provide a more informative message here.

### Screenshots and log output
If applicable, add screenshots or log output to help explain your problem.

### System information
**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [x] bigquery
- [ ] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
0.19.1
```

Although as mentioned the manifest is for an older version.  I suspect this is the cause of the failure.

**The operating system you're using:**
Ubuntu 18.04.5 LTS

**The output of `python --version`:**
3.8.5

**Comment by jtcohen6** [comment]
Hey @walshie4, thanks for opening! Your instincts here are all right on.

```
Field "exposures" of type typing.Mapping[str, dbt.contracts.graph.parsed.ParsedExposure] is missing in dbt.contracts.graph.manifest.WritableManifest instance
```
That's a pretty gross error (though I've seen grosser). The issue here is that state comparison requires comparison between the current manifest (your project, being run, right now) and the state manifest (the file passed to `--state`). A manifest produced by `v0.18.0` and a manifest produced by `v0.19.1` have different and incompatible schemas. In particular, `v0.19.1` uses the [`v1` manifest schema](https://schemas.getdbt.com/dbt/manifest/v1/index.html), whereas `v0.18.0` uses a pre-v0 (unversioned, uncontracted, undocumented) schema, and there were breaking changes between them.

Going forward, now that artifact schemas are versioned and contracted, we'll raise a much more helpful error if there's a mismatch:

https://github.com/fishtown-analytics/dbt/blob/26fb58bd1b08218781b182918f5ed4dec3f735d9/core/dbt/exceptions.py#L277-L285

Something like:
```
  Expected a schema version of "https://schemas.getdbt.com/dbt/manifest/v1.json" in
.state/manifest.json, but found "https://schemas.getdbt.com/dbt/manifest/v2.json".
Are you running with a different version of dbt?
```

That error is not guaranteed every time the dbt versions are different—only if there was a breaking change to the artifact schema between them, making comparison impossible.

I'm going to close this issue, since we'll have a more helpful error message going forward, so long as the state artifact and the current dbt invocations are both produced with versions >= 0.19.0.
