### ISSUE TITLE
slim ci state:modified doesn't select a downstream child model when the parent tables changed

### ISSUE THREAD

**Issue by mv1742** [fishtown-analytics/dbt#3349]
### Describe the feature
Running the slim ci `state:modified` doesn't select child models when its parent ephemeral dependencies changed.

I have a model folder that looks like this:

```.
└──  models
    └── model1
        ├── intermediate
        │   └── ephemeral_model.sql
        └──  model1.sql
```

the child 'model1.sql' depends on the parent 'ephemeral_model.sql'.

model1.sql looks something like this:

**model1.sql**
```
select
*
FROM another_table
INNER JOIN {{ ref('ephemeral_model.sql')}} ON ...
```

After changing 'ephemeral_model.sql' in my dbt repo, 'model1.sql' is not selected (listed or ran) in my ci when running the `state:modified` command below:

`dbt run -m state:modified --stage <compare_target>`

The new feature should select all dependent models when using `-m state:modified`.

### Describe alternatives you've considered
To run my dependent child model, I made added an arbitrary new line change somewhere in 'model1.sql' so that my model gets selected, ran, and tested with the parent model changes.

### Additional context
I am using dbt-spark, but I believe this applies to all databases.

### Who will this benefit?
This will guarantee more robust testing given that child models should be tested when parent models dependencies changed.

### Are you interested in contributing this feature?
I am willing to contribute to this.

**Comment by jtcohen6** [comment]
@mv1742 Thanks for opening, and I totally agree with your reasoning here! It's possible to achieve this behavior using dbt's [node selection syntax](https://docs.getdbt.com/reference/node-selection/syntax), in particular, [the `+` graph operator](https://docs.getdbt.com/reference/node-selection/graph-operators#the-plus-operator).

In our [documented best practices](https://docs.getdbt.com/docs/guides/best-practices#run-only-modified-models-to-test-changes-slim-ci), we recommend using the following selection syntax:
```
dbt run -m state:modified+ --state path/to/artifacts
```
I'm going to close this issue, since what you've asked for is 100% possible—and desirable!—in dbt today.
