### ISSUE TITLE
Deference with `state:modified` selectors do not detect changes to macros that impact downstream models that rely on the macro

### ISSUE THREAD

**Issue by randypitcherii** [fishtown-analytics/dbt#3373]
### Describe the bug
I noticed when using deference that changes to my macros (such as a timestamp standardization macro) did not set the models I have that use that macro to a modified state.

This could be problematic in a number of ways if I rely on deference in my pull request process because no models would run after a macro change, my tests would pass, and I could introduce breaking bugs in my prod pipelines.

### Steps To Reproduce
In an environment that uses deference to a previous run:
1. modify a macro that is used in 1 or more models in your current project
2. Execute a dbt run filtered to only the `state:modified` models
3. observe that the models that rely on your changed macros are treated as if they have not changed.

### Expected behavior
I would expect that if a model relies on a macro that a change to that macro would mark this model as changed or have some other way to select models in a deference run by whether any macros they rely on have changed or not.

### System information
**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [ ] bigquery
- [X] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
installed version: 0.19.1
   latest version: 0.19.1

Up to date!

Plugins:
  - bigquery: 0.19.1
  - snowflake: 0.19.1
  - redshift: 0.19.1
  - postgres: 0.19.1
```

**The operating system you're using:**
MacOS Big Sur

**The output of `python --version`:**
```
Python 3.8.6
```

**Comment by jtcohen6** [comment]
@randypitcherii I 100% agree! This is one of the [known + documented limitations](https://docs.getdbt.com/reference/node-selection/state-comparison-caveats) to `state:modified` today. All dbt is able to do today is raise a lame warning:
https://github.com/fishtown-analytics/dbt/blob/17555faaca70b4a9cd9e202097ababa1aca7839e/core/dbt/graph/selector_methods.py#L416-L426

Historically, the issue was incomplete dependency tracking between macros. So dbt might know that `model_a` depends on `macro_a`, but if `macro_a` calls `macro_b`, we didn't have a reliable way to note a change to `macro_b` and mark `model_a` as modified.

For unrelated performance reasons, we're finally building a reliable version of `depends_on.macros` in, for each macro in a project. (This is a change coming in v0.19.2 + v0.20.0.) This means all inter-macro dependencies are now tracked, and full macro lineage can be reconstructed. I opened https://github.com/fishtown-analytics/dbt/issues/3278 to propose leveraging that `depends_on.macros` for the sake of `state:modified`.

I'm going to close this issue as a dupe, insofar as #3278 describes the code change we need to make, but I _completely_ agree that this is something we should do.
