### ISSUE TITLE
Running a snapshot with missing required configurations results in uncaught Python exception

### ISSUE THREAD

**Issue by jnatkins** [fishtown-analytics/dbt#3381]
### Describe the bug
In an attempt to educate myself on how snapshots work, I created a snapshot to test out, but neglected to realize that the configuration object was required. When I ran `dbt snapshot`, it failed with a fairly non-actionable error message:

```
2021-05-20T22:41:00.291112Z: uncaught python exception
'NoneType' object has no attribute 'lower' Code: -32000
```

### Steps To Reproduce
1. Create a snapshot without a config object, i.e.
```
{% snapshot snap_demo %}

select * from {{ ref('snapshot_demo_source') }}

{% endsnapshot %}
```
2. Run `dbt snapshot`

### Expected behavior
It would be helpful to get an error message that indicates what actually went wrong, and guides the user to provide required configurations

### Screenshots and log output
If applicable, add screenshots or log output to help explain your problem.

### System information
**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [ ] bigquery
- [X] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
0.19.1
```

**The operating system you're using:**
MacOS

**The output of `python --version`:**

**Comment by jtcohen6** [comment]
@jnatkins Such a good issue, and a great catch, thank you for opening!

I think there's a pretty straightforward resolution here, which is adding a check to the `validate` method of `SnapshotConfig`:

https://github.com/fishtown-analytics/dbt/blob/e775f2b38e52e8b9f25f8ac98c942d22b2c8c55d/core/dbt/contracts/graph/model_config.py#L448-L485

This method already exists to ensure that snapshots with certain strategies (`timestamp`, `check`) also contain the required associated configurations. We should first just check to make sure the [three required configurations](https://docs.getdbt.com/docs/building-a-dbt-project/snapshots#snapshot-configurations) are present. Something like:
```python
        if not data.get('strategy') or not data.get('unique_key') or not data.get('target_schema'):
            raise ValidationError(
                "Snapshots must be configured with a 'strategy', 'unique_key', and 'target_schema'.")
```

So instead of `'NoneType' object has no attribute 'lower'`, you'd get:
```
Compilation Error in snapshot my_snap (snapshots/my_snap.sql)
  at path []: Snapshots must be configured with a 'strategy', 'unique_key', and 'target_schema'.
```

Whether those configs are set via in-file `config()` blocks, or in `dbt_project.yml`, doesn't much matter. They just need to be set one way or another.

I'm going to tag this as a `good first issue`. Is this a fix you (or anyone else) might be interested in contributing? :)

**Comment by jnatkins** [comment]
@jtcohen6 I'd definitely be interested in contributing a fix here. I don't have a dev environment set up for dbt core yet, but I can probably scrape something together pretty quickly.
