### ISSUE TITLE
seed schema 

### ISSUE THREAD

**Issue by cbarry85** [fishtown-analytics/dbt#3389]
Running dbt seed generates a query test_static instead of test.static

dbt_project.yml
seeds:
    +schema: static
    +database: test

**Log**
1 of 1 OK loaded seed file test_static.DateDimension.......... [CREATE 2191 in 4.98s]

**Comment by jtcohen6** [comment]
Hi @cbarry85, check out the docs on [using custom schemas](https://docs.getdbt.com/docs/building-a-dbt-project/building-models/using-custom-schemas).

By default, dbt will _append_ custom schema names to your `target.schema`, rather than replacing it entirely. Why? If your colleagues were to run `dbt seed` with the same objects, we want to be sure to avoid collisions—so the default behavior is to populate `cbarry85_static` and `jtcohen6_static`, rather than both of us into a single `static` schema.

Of course, it's understood that, in certain environments, you may want dbt to create objects straight into the `static` schema, with no prefix, suffix, or any-other-fix. dbt gives you the ability to define the pattern of schema name generation via a macro named `generate_schema_name`, and it even ships with an alternative pattern built-in: `generate_schema_name_for_env`. You can see the code for both of these macros [here](https://github.com/fishtown-analytics/dbt/blob/develop/core/dbt/include/global_project/macros/etc/get_custom_schema.sql).
