### ISSUE TITLE
DBT Postgres Commit and Rollback

### ISSUE THREAD

**Issue by rajeshmese** [fishtown-analytics/dbt#3401]
Does DBT have option to commit only if all models execution is completed?. Ex. I have two models and it inserts data to two target tables from same source with different filters, so if  load failed in second model then first model also should not commit or it should be rollback.

**Comment by jtcohen6** [comment]
Hey @rajeshmese, this isn't something dbt is capable to doing today.

When materializing a single model, dbt does its best to roll back the materialization if any step within it fails. It accomplishes this through either:
- Transactional logic (e.g. on Postgres, Redshift, sometimes Snowflake) 
- A single atomic DDL/DML operation (e.g. on BigQuery, Apache Spark/Databricks, sometimes Snowflake)

In the former case, each model gets its own transaction; that transaction is committed on success or rolled back on failure. So it's not possible to roll back upstream model changes if a downstream model fails.

There's a different pattern that gets at what you're after: [blue-green deployment](https://discourse.getdbt.com/t/performing-a-blue-green-deploy-of-your-dbt-project-on-snowflake/1349). Production jobs, instead of running directly into the production schema, first create models in a sandboxed staging schema, and test those models after creation. If all models and tests pass, the schemas are swapped; if anything fails, the operation is rolled back and the existing production schema left in place.

There are some limitations. If you use incremental models, you need some way to first clone or copy the existing tables into the sandbox schema. Snowflake and BigQuery offer good mechanisms for this. While other data warehouses don't yet offer this capability, we believe it's such a compelling feature, they should seek to offer it soon.
