### ISSUE TITLE
Branching from non master branch

### ISSUE THREAD

**Issue by skiwan** [fishtown-analytics/dbt#3409]
### Describe the feature
I would like to be able to create a new branch from within dbt, based on another branch that is not master.

For example I have my development branch. And I would like to create a feature branch from that development branch instead of changing to master and then creating the feature branch based on the master branch

### Additional context
Standard Git Workflow in most companies, so it would be nice to have

### Who will this benefit?
This will enable more flexible git workflows for people

### Are you interested in contributing this feature?
Hell ya, just tell me what I need to do and I implement it :D

**Comment by jtcohen6** [comment]
Hi @skiwan, thanks for opening!

Help me understand what you're after here. Is this a feature request for the dbt Cloud Develop IDE? If so, I'd be happy to pass along the feedback. This isn't the codebase where we could make that change, however.

**Comment by skiwan** [comment]
DBt cloud indeed. So if possible please pass that along :) 

In DBT Cloud within the GUI currently (to the best of my knowledge) we can only create a new branch while we are on the master branch. But I also would like to be able to create branches from a sub branch that is not the master branch.

**Comment by jtcohen6** [comment]
@skiwan Got it!

I think the dbt Cloud development environment is always going to support a subset of git functionality (it gets very complex!). The ability to create branches off non-default branches is a reasonable ask, and I can definitely pass along your interest. In the meantime, it's something you need to work around, by creating a new branch via git CLI or in your git provider's UI, and checking out that new branch in the dbt Cloud IDE.

I am going to close this issue, since there isn't any change we could make in this or any other open source codebase to support the enhancement you're after.
