### ISSUE TITLE
dbt ls updates manifest

### ISSUE THREAD

**Issue by bibli-alex** [fishtown-analytics/dbt#3410]
### Describe the bug
When trying to use `-m state:modified` to find altered models and re-run them, I found that using `dbt ls -m state:modified` updates the manifest.json, causing the change to disappear after that point. 

### Steps To Reproduce
1. Create simple model, run `dbt run -m MODEL_NAME`
2. Check that manifest.json now exists
3. `dbt ls -m state:modified` - no changes should exist
4. Edit simple model, make minor change
5. `dbt ls -m state:modified` - change shows correctly
6. `dbt ls -m state:modified` again - change no longer shows. `dbt run -m state:modified` will also no longer see this change. 

### Expected behavior
`dbt ls` should not alter the `manifest.json`, as it hides changed state, making it impossible to determine what has been run

### System information
**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [ ] bigquery
- [x] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
$ dbt --version
installed version: 0.19.1
   latest version: 0.19.1

Up to date!

Plugins:
  - bigquery: 0.19.1
  - snowflake: 0.19.1
  - redshift: 0.19.1
  - postgres: 0.19.1
```

**The operating system you're using:**
MacOS 10.15.7

**The output of `python --version`:**
```
$ python --version
Python 2.7.16
```

**Comment by jtcohen6** [comment]
Hey @bibli-alex, thanks for opening the issue, and for the detailed explanation of your use case.

It sounds like your specific question is motivated by `state:modified` functionality, which requires a comparison manifest. Is there a reason why, after step 4, you don't move the manifest from out of the `target/` directory (where it will be overwritten by future commands), and into a different directory in your relative path (`comparison/`, `.state/`, whatever you'd like)? Then steps 5 + 6 just need to specify that directory: `dbt ls -m state:modified --state comparison`. This is what I do when using this functionality locally, for exactly the reason you describe: I don't want to accidentally conflate (or clobber) comparison and current state by having both live in `target/manifest.json`.

The fact is that `dbt ls` parses the project and constructs a manifest just as much as any other task/command does. Today, the _fastest_ way to write a manifest is to use `dbt ls` (with `--exclude fqn:* source:* exposure:*` to avoid printing a bunch of noise to stdout). I know there are community members who rely on this functionality today.

I would like to see greater consistency between `dbt parse` and `dbt ls`. [The former](https://docs.getdbt.com/reference/commands/parse) doesn't write `manifest.json` because we wanted it to perform the barest-bones, fastest-possible project parse. Serializing to JSON and writing a large file can add quite a few seconds on top of that bare parse. All the same, I'd lean in the direction of having _both_ commands write `manifest.json`, rather than neither.

I'm going to close this issue, insofar as I don't see us changing `ls` behavior around writing manifests, and I think there's a better local workflow for comparison manifests. That said, I'm always open to a larger discussion around which tasks should write which JSON artifacts.
