### ISSUE TITLE
0.20.0rc1 can't "dbt init" without Redshift

### ISSUE THREAD

**Issue by joshpeng** [fishtown-analytics/dbt#3434]
### Describe the bug
When installing only `dbt-core==0.20.0rc1` and `dbt-bigquery==0.20.0rc1`, doing `dbt init` does not work because it is looking for the Redshift package. This used to work fine in `0.19.1` without Redshift package.

### Steps To Reproduce
```
pip install dbt-core==0.20.0rc1 dbt-bigquery==0.20.0rc1
dbt init new_project
```
Results in the following error:
```
Running with dbt=0.20.0-rc1
Creating dbt configuration folder at /home/josh/.dbt
With sample profiles.yml for redshift
Encountered an error:
Runtime Error
  Could not find adapter type redshift!
```

### Expected behavior
New project directory to be initialized without Redshift.

### System information
**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [x] bigquery
- [ ] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
$ dbt --version
installed version: 0.20.0-rc1
   latest version: 0.19.1

Your version of dbt is ahead of the latest release!

Plugins:
  - bigquery: 0.20.0rc1
```

**The operating system you're using:**
Windows and Mac

**The output of `python --version`:**
Python 3.8.3

**Comment by jtcohen6** [comment]
Thanks for opening @joshpeng!

This should still work:
```
dbt init --adapter bigquery
```

> This used to work fine in 0.19.1 without Redshift package.

I don't think this is a difference between 0.19.1 and 0.20.0rc1, as much as a result of now encouraging users to install specific adapter plugins.

This is undesirable in two ways:
- You have to specify `--adapter bigquery`, even if your only installed adapter is `dbt-bigquery`
- `dbt init` (no flags) raises an error for anyone who doesn't have `dbt-redshift` installed, and even then, it doesn't do something very helpful

If the `--adapter` argument is not passed, I think our options are:
- `init` checks the adapters available, rather than falling back to `redshift` as the default
- `init` falls back to a more reasonable, generic default (not `redshift`) that ships inside of `core`

In the meantime, I'm going to include a note on #2814, and close this issue as a duplicate. I really appreciate you opening, and providing some appetite to get this fixed.
