### ISSUE TITLE
CircleCI test suite errors involving 'access_token'

### ISSUE THREAD

**Issue by gshank** [fishtown-analytics/dbt#3457]
This is happening on both develop and 0.19.latest. 

Error from 0.19.latest:
```
        if 'access_token' not in result_json:
>           raise DatabaseException(f'Did not get a token: {result_json}')
E           dbt.exceptions.DatabaseException: Database Error
E             Did not get a token: {'data': None, 'error': 'invalid_grant', 'code': None, 'message': 'The provided grant or refresh token is invalid.', 'success': False, 'headers': None}
```

Error from develop:

```
>       return result_json['access_token']
E       KeyError: 'access_token'
```

**Comment by jtcohen6** [comment]
This one is on me! Quick summary:
- Testing Snowflake OAuth functionality requires an OAuth refresh tokens
- Tokens are valid for 90 days max
- Getting a new refresh token is pretty simple, it involves following [these steps](https://github.com/fishtown-analytics/dbt/blob/14507a283e6acd710363aab9fc8fbcac1658002d/test/integration/057_oauth_tests/test_oauth.py#L18-L31)
- I have a calendar reminder to do this every 60 days
- I missed the reminder on May 9 (Sunday) :)

Things we could do to improve this:
- Find a way to automate via a headless browser (probably hard)
- This would be _marginally_ easier if we ran all our CI from one service (a GitHub action in the `dbt` repo) rather than the three we rely on today (CircleCI, Azure Pipelines, GitHub action in `dbt-release`). That said, it doesn't take much longer to do this for three tokens vs. one.

In any event, I just replaced all three tokens and triggered re-runs for CircleCI + Azure jobs that failed earlier.
