### ISSUE TITLE
0.20.0rc1 test `where` config doesn't support single quotes

### ISSUE THREAD

**Issue by ilmari-aalto** [fishtown-analytics/dbt#3458]
### Describe the bug
I'm trying out 0.20.0rc1 with BigQuery with the following test configuration, using the brand new `where` config:

```
        tests:
          - not_null:
              where: "col != 'none'"
```

`dbt test` fails with the following error because it doesn't support single quotes:

```
Compilation Error in test not_null_my_first_dbt_model_id (models/example/schema.yml)
  expected token ',', got 'none'
    line 1
      {{ test_not_null(**_dbt_schema_test_kwargs) }}{{ config(where='col != 'none'') }}
```

### Steps To Reproduce
Try to specify a `where` condition that includes single quotes. Run `dbt test` and it should fail when compiling the project.

### Expected behavior
Allow using single quotes in a `where` config to filter text/varchar columns

### Screenshots and log output
If applicable, add screenshots or log output to help explain your problem.

### System information
**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [x ] bigquery
- [ ] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
installed version: 0.20.0-rc1
   latest version: 0.19.1

Your version of dbt is ahead of the latest release!

Plugins:
  - bigquery: 0.20.0rc1
  - snowflake: 0.20.0rc1
  - redshift: 0.20.0rc1
  - postgres: 0.20.0rc1
```

**The operating system you're using:**
macOS Big Sur 11.4

**The output of `python --version`:**
```
Python 3.9.5
```

**Comment by tconbeer** [comment]
I ran into the same issue on Redshift (and py 3.8). The new built-in tests (`not_null`, etc.) work okay for me, but I had several custom tests that accepted a `where` kwarg, and those get the Compilation Error above, since dbt seems to be treating the `where` keyword as a config, instead of a kwarg (and isn't safely handling single quotes in that config)

**Comment by jtcohen6** [comment]
@ilmari-aalto Thanks for opening the issue! I definitely want to fix this ahead of the final release, and I think the fix should be straightforward.

@tconbeer You're right, dbt will now "intercept" the `where` arguments previously passed to custom tests and treat them as a `where` config instead. This is strictly better, since you have more control levers for configs than for arguments, but it's not better at all if there isn't safe handling for quotes.

**Comment by tconbeer** [comment]
Awesome, thank you!

**Comment by ilmari-aalto** [comment]
Thanks for the quick fix & glad to hear it's going to be in the final release!
