### ISSUE TITLE
Running DBT Databricks jobs on cloud

### ISSUE THREAD

**Issue by danielgsanz** [fishtown-analytics/dbt#3479]
I'm not being able to run jobs on the DBT cloud using a Databricks connection. My development cluster works fine, but when I try to run `dbt run` on my deployment cluster, I'm getting the following error: 
`Credentials in profile "user", target "default" invalid: 'schema' is a required property`. 

It looks like that DBT it's not using the credentials I've created in my profile.  How should I set my profile correctly in a deployment cluster using DBT cloud?

![image](https://user-images.githubusercontent.com/12350123/122747094-f0128f00-d28a-11eb-99f3-93d1ac273418.png)

Looking forward to hearing from you. Thanks!

**Comment by jtcohen6** [comment]
Hi @danielgsanz, sorry you're having trouble connecting! Could you send a message to dbt Cloud support, using the chat icon in the top-right corner? They'll be able to look into the specific details of your connection, and to help diagnose what might be causing the error.

In the meantime, I'm going to close this issue, since it's not associated with any code changes we can make in this repo (dbt Core).
