### ISSUE TITLE
dbt install fails on Windows

### ISSUE THREAD

**Issue by kanchank** [fishtown-analytics/dbt#3492]
### Describe the bug
DBT Install fails on Windows either using 
1. pip install dbt, OR
2. pip install -r requirements.txt

### Steps To Reproduce
Run above steps to install it on windows using document using 
https://docs.getdbt.com/dbt-cli/installation#pip, or
https://docs.getdbt.com/dbt-cli/installation#install-from-source

### Expected behavior
Expected to install dbt cli.

### Screenshots and log output
Error using PIP method:
![image](https://user-images.githubusercontent.com/7372799/123150208-f46bb300-d416-11eb-9f8e-33919488e074.png)

Using install from source:
![image](https://user-images.githubusercontent.com/7372799/123150563-5af0d100-d417-11eb-8868-0e43a55f47a7.png)

### System information
**Which database are you using dbt with?**
- [ ] snowflake

**The output of `dbt --version`:**
```
not able to install```

**The operating system you're using:**
Windows 10

**The output of `python --version`:**
Python 3.9.5

### Additional context
Upgrade the visual C++ from as mentioned in the error message. Restarted the PC.
![image](https://user-images.githubusercontent.com/7372799/123150760-9390aa80-d417-11eb-9db4-8137aaab2170.png)

**Comment by jtcohen6** [comment]
Hey @kanchank, you're running into two unrelated issues here:

1. `pip install dbt` includes `dbt-snowflake==0.19.1`, which is not compatible with python 3.9 because of second-order dependencies of `snowflake-connector-python==2.3.6`. (https://github.com/fishtown-analytics/dbt/issues/2985)

2. Installing dbt from source, on the `develop` branch, requires `tree-sitter` as a dependency, which in turn requires a C compiler (https://github.com/fishtown-analytics/dbt/issues/3433) We're working to remove that requirement for the next release candidate of dbt, which is coming very soon.

In the meantime, I'd recommend changing your python version to 3.8 (if possible) and reinstalling the latest stable version of dbt for Snowflake via:
```
pip install dbt-snowflake
```
