### ISSUE TITLE
commented out macros can still render into target sql in strange ways

### ISSUE THREAD

**Issue by cmcarthur** [fishtown-analytics/dbt#458]
Given a multiline macro:

```
{% macro multiline(field) -%}
  {{field}}
  as {{field}}
{%- endmacro %}
```

and model sql:

```sql
select
  *
  -- {{multiline('id')}}
```

the target sql is:

```sql
select
  *
  -- id
  as id
```

I'm not sure there's anything we can do about this besides recommend using multiline comments, it's just unexpected the first time it happens

**Comment by jthandy** [comment]
I've run into this before. At first it was perplexing / frustrating to me that SQL comments don't also comment out jinja code; however, I came to see that as unreasonable. Of course the jinja compiler doesn't respect SQL comments...

Do you think there is a "solve" for this?

**Comment by drewbanin** [comment]
@jthandy I think we have two options here:

1. Encourage the use of jinja commments:

```sql
select
  *
  {# {{multiline('id')}} #}
...
```

2. We can configure the jinja compiler to use `--` as a line comment identifier. Check [this](http://jinja.pocoo.org/docs/2.9/templates/#line-statements) out

**Comment by jthandy** [comment]
Whoah! That is super-cool. I think adding `--` as a comment identifier would be fucking sweet.

I also really like the line statement identifier defined in those docs—we should consider incorporating that as well. I find the `{% %}` syntax very ugly / un-SQL-y. The `{{ }}` syntax feels totally reasonable to me because it's always in-line and fairly limited in scope, but sometimes you need a ton of `{% %}` to get something done.

**Comment by jthandy** [comment]
I'm closing this. Really, the answer here is to use correct jinja commenting syntax, which I just didn't know about at the time I originally logged this (from connor's computer). The comment about line identifiers is captured in another issue.
