### ISSUE TITLE
Ability to specify timezone on `run_started_at` or providing `utc_run_started_at` 

### ISSUE THREAD

**Issue by michael-erasmus** [fishtown-analytics/dbt#474]
Right now it seems like the [`run_started_at` function](https://dbt.readme.io/v0.8/reference#run_started_at) will default to being in your local system timezone. 

This could pose an issue if you want to store the value in your db along with runs (for say auditing purposes)

The actual value can change depending on where you run it from (say your running it locally vs on a production server). 

It would be great be able to control the TZ (`run_started_at('utc')`) or having another `utc_run_started_at` function (you can also convert that to another TZ if needed in SQL)

**Comment by mturzanska** [comment]
@drewbanin I would like to work on this issue

One could add `--time-standard` parameter that for now accepts either 'utc' or 'local' (default).

The parsed value would become an argument to either tracking.do_not_track or tracking.initialize_tracking in order to be passed to User init.
To simplify it, one could move the creation of the User instance out of tracking.do_not_track and tracking.initialize_tracking, and make both of them accept User instance as an argument.

Does it sound ok?

**Comment by drewbanin** [comment]
@mturzanska I think that approach would work, but I also think we can bypass the tracking code here. Let's try to define the timezone config in code instead of as a command line argument if possible.

We're interested in pushing a lot of logic like this out of dbt "core" and into macros. Whereas we could provide a `utc_run_started_at` variable, the end goal is to let anyone define their own `run_started_at` implementation!

My thinking is:
1. Change [run_started_at](https://github.com/fishtown-analytics/dbt/blob/development/dbt/tracking.py#L47) to use utc time. This is a "breaking" change, but I think it's the better and more sane implementation than the existing one.
2. Add `pytz` as a dependency in `setup.py` and `requirements.txt`, the add it to the [context](https://github.com/fishtown-analytics/dbt/blob/development/dbt/context/common.py#L269) (along with `datetime` too?)

Then, end-users can define their own macros like:
```sql
{% macro utc_run_started_at() %}
  {{ run_started_at.astimezone(pytz.timezone('America/New_York')) }}
{% endmacro %}
```

Now, users can do their own timezone calculations, both for `run_started_at`, and for any other dates! Does that sound reasonable?

**Comment by mturzanska** [comment]
@drewbanin your solution sounds really great. Will work on it in the upcoming week.

**Comment by drewbanin** [comment]
This is merged (thanks @mturzanska) -- closing!

Example usage:
```
select
  '{{ run_started_at.astimezone(modules.pytz.timezone("America/New_York")) }}' as run_started_at_est,
  '{{ run_started_at }}' as run_started_at_utc
```

Additionally, `run_started_at` is now reported in utc time. This change will go out in dbt 0.9.1

**Comment by michael-erasmus** [comment]
Thanks @mturzanska and @drewbanin!
