### ISSUE TITLE
Running dbt models without any reference to ephemeral does not create views 

### ISSUE THREAD

**Issue by izdi** [fishtown-analytics/dbt#479]
Suppose I have plain SQL (without any config and refs) in my models and want to materialize it running `dbt run` it does not produce all models and sometimes I bump into `ERROR:  relation "dbt_analytics.my_relation" does not exist`.

What logic is used behind materialization ?
Are there any hidden dependencies, or some kind of sequence is used when creating views ?

**Comment by drewbanin** [comment]
Hey @izdi -- that sounds strange! Could you tell me what version of dbt you're using? You can find that with
```
dbt --version
```

Additionally, it would be helpful if you pasted in the contents of your `dbt_project.yml` file, and the contents of a model in your project that dbt is having trouble with.

dbt uses the `ref()` calls in models to build a dependency graph. Next, dbt walks this graph and executes the models in order. This ensures that if Model B depends on Model A, Model A will be run first. If the materialization configs for a model are not set explicitly, the default is `view`.

**Comment by izdi** [comment]
Hey, there is our version

```
$ dbt --version
installed version: 0.8.2
   latest version: 0.8.2
Up to date!
```

Sorry ,can't provide you with query information yet.

Is it possible somehow to show dependency graph via debug mode or could you point at code where I could debug final print of dependency graph ?

Thanks!

**Comment by drewbanin** [comment]
Hey @izdi -- so, to be clear: Do your models depend on each other? You pasted the error:

> ERROR: relation "dbt_analytics.my_relation" does not exist

above. In this example, does another model reference `my_relation`? If so: You should use
```
{{ ref('my_relation') }}
```
in your model SQL instead of hard-coding `dbt_analytics.my_relation`.

I wrote a little script to quickly show the ancestors for a dbt graph file:
https://gist.github.com/drewbanin/58e8ecfae93c930624f17517799821f2

Run it with
```python
$ python show_ancestors.py target/graph.gpickle
```

We're also around on the [dbt slack](http://ac-slackin.herokuapp.com/) if you feel more comfortable sharing any relevant code over there.

**Comment by izdi** [comment]
Thanks for the script. Indeed, our models have been using view names instead of `ref` function, so changing to `ref` fixed the issue. 

Previously we have not seen the issues since we had few models, so we used generated views names. But as we got many more of them we started seeing dependency issues, when we had to rebuild. 

Thanks!

**Comment by drewbanin** [comment]
Glad you got it working!
