### ISSUE TITLE
vacuum fails when running with multiple threads

### ISSUE THREAD

**Issue by HarlanH** [fishtown-analytics/dbt#639]
Capturing this from a Slack conversation... Unsure how to solve, or where it lives in priorities... Would still like to be able to run vacuum as a post-hook for specific models only. (I believe running vacuum in an overall post-hook is viable, but would require me to specify the tables explicitly, rather than being able to leverage `{{this.schema}}.{{this.name}}`.)

> harlanh [Dec 14th, 2017 at 6:05 PM]
> in #support
> Playing with hooks for vacuuming Redshift tables. I found the docs on how to do it outside of the transactions. But on my first test, I got a failure because I run with multiple threads. If I’m using vacuuming, does that mean that I have to set threads to 1?
> 
> 
> 13 replies
> drew.banin [1 month ago]
> @harlanh hmm — what does the error look like?
> 
> 
> harlanh [1 month ago]
> ```Database Error in model stg_activity_applies (models/staging/activity/stg_activity_applies.sql)
>   VACUUM is running
>   HINT:  re-execute after other vacuum finished
>   compiled SQL at target/run/wayup_warehouse/staging/activity/stg_activity_applies.sql
> ```
> 
> 
> harlanh [1 month ago]
> and of course it caused the model to fail.
> 
> 
> drew.banin [1 month ago]
> oh oh oh, only one vacuum can run at a time
> 
> 
> drew.banin [1 month ago]
> darnit, Redshift
> 
> 
> harlanh [1 month ago]
> yes
> 
> 
> drew.banin [1 month ago]
> yeah, I think using a single thread is probably the only reasonable answer for right now (edited)
> 
> 
> harlanh [1 month ago]
> ok. bummer.

**Comment by drewbanin** [comment]
Thanks for making this issue @HarlanH. I think we need some sort of lock / mutex here, right? Any ideas for how this could work?

**Comment by HarlanH** [comment]
agree, but no idea... you almost need to create new nodes in the DAG for these...

**Comment by drewbanin** [comment]
yeah. It's frustrating because this is a non-trivial amount of work for a single feature of a single database. That said, I think Redshift's market/mind share necessitates some extra attention in cases like this.

Let me have a think about how we could implement this without re-architecting dbt :) Will post back here with any updates

**Comment by HarlanH** [comment]
note it doesn't actually have to run the vacuum at that point in the DAG. If you just pushed the vacuum into a queue and ran it at the end, that'd be totally cool with me... (Although it might not for others, as there coudl be a performance hit in the interim...)

**Comment by pedromachados** [comment]
Ideally, the VACUUM would run right after the model creation/update before dependent models are run, but if it doesn't that wouldn't be a deal killer. Presumably, tables will be in decent shape if the VACUUM commands are being run frequently so if this cannot happen at the ideal time, that's OK. 

One idea is to have a FIFO queue that would be populated with commands like VACUUM queued by the hooks. The process that runs each model could check if there are any of these operations pending and run them in blocking mode before the next model is run. This may not ensure optimal sequencing, but it should, for the most part, preserve the order of the graph.

**Comment by drewbanin** [comment]
While dbt tries to be pretty good about supporting Redshift's quirks, I think this is a bridge too far. I'd recommend running a vacuum nightly, rather than at the end of a given run. There's a decent writeup for how to do this here: https://gist.github.com/jthandy/b5860a829d220eb9d8e76aa76aada5b2

A personal note: the quirks around vacuum (concurrency and column limits, deep copy requirements, the fact that it is required at all, etc) are supremely frustrating to me as a dbt maintainer, and as an analyst. I take no pleasure in #wontfixing you folks, but this is not a use case that we believe dbt should support.
