### ISSUE TITLE
Support for postgres index creation?

### ISSUE THREAD

**Issue by ryantuck** [fishtown-analytics/dbt#804]
Is there a way, using `dbt`, to create an index in postgres as part of a run? Given that everything is a `select`, it's not clear where this functionality would live, and I couldn't find anything in the docs or issues about it. 

Or, is the answer to just get out of postgres and move to BigQuery etc :) ?

**Comment by drewbanin** [comment]
Hey @ryantuck - you can accomplish this with a [post-hook](https://docs.getdbt.com/docs/using-hooks#section-configuring-hooks). You'll probably want to do something like

```sql
{{
  config({
    "materialized" : "table",
    "post-hook": 'create index if not exists {{ this.name }}__index_on_FIELD on {{ this }} ("FIELD")'
    })
}}

select ...
```

^ assuming the index you want to add is on a column called FIELD. If you find yourself doing this a lot, you can create a [macro](https://docs.getdbt.com/docs/macros) to add an index to an parameterized column. We also have a nascent [postgres package](https://github.com/fishtown-analytics/postgres) that does exactly this :)


I think in general, dbt works best with Redshift/Snowflake/BigQuery, but sounds like there are at least a few folks using it on postgres with some success! Hope this helps :)

**Comment by max-sixty** [comment]
An issue I've found with the suggested hook is it seems to only add an index every second run. But if I remove the `if not exists`, then it fails on it already existing (after the first run).

Is this something to do with how dbt handles the cleverness of the table creation and renames? Is there a fix that will solve the immediate problem?

**Comment by max-sixty** [comment]
Discussion for that at https://github.com/fishtown-analytics/dbt/issues/804

**Comment by drewbanin** [comment]
Let's add first-class support for an `index` config to models running on Postgres. We support the analogues for Redshift/Snowflake/BigQuery -- we might as well support these natively on Postgres too.

We don't intend to prioritize this directly (we always recommend using a proper data warehouse with dbt like Redshift, Snowflake, or BigQuery), but I would be _very_ happy to work with a community contributor to implement this functionality in dbt!

**Comment by rapala61** [comment]
Hi all. Just wanted to update this issue with the workaround (Proposed by drewbanin in https://github.com/fishtown-analytics/dbt/issues/1945#issuecomment-576826021) we are going to use @ DoSomething.org. For context: our former data lead created this related issue https://github.com/fishtown-analytics/dbt/issues/1945#issue-526684234.

### Macro

```
{% macro get_index_name(model, idx_name) %}
    {{ model.schema ~ '_' ~ model.table ~ '_' ~ idx_name ~ '_' ~ run_started_at.strftime('%Y%m%d_%H%M%S') ~ ' ON ' ~ model }}
{% endmacro %}
```

### Usage

Creates indexes consistently on every run for the given table in the pattern `<schema>_<table_name>_<idx_name>_<yyyymmdd_hhmmss>`, e.g. "public_post_actions_unique_20200804_235704"

```
models:
    ds_dbt:
        ...
        model_name:
            table_mame:
                alias: post_actions
                materialized: table
                 post-hook:
                    - "CREATE UNIQUE INDEX {{ get_index_name(this, 'unique') }} (created_at, id)"
```

**Comment by arzavj** [comment]
@drewbanin I've gone through a few iterations of my own macro to create an index in Postgres. I'd love to contribute it. It handles the timestamp naming above as well as supports indexes on multiple columns (and chooses the best index name such that the index name is a unique function of the columns the index is on).

Should I contribute it to the main repo or to the [Postgres package](https://github.com/fishtown-analytics/postgres)? I'm a first time contributor and am happy to follow the process [here](https://github.com/fishtown-analytics/dbt/blob/dev/margaret-mead/CONTRIBUTING.md).

**Comment by drewbanin** [comment]
nice one @arzavj ! @jtcohen6 what do you reckon the right home for a macro like this would be?

**Comment by jtcohen6** [comment]
@drewbanin I agree with your statement last year about adding first-class support for index creation to `dbt-postgres`. It's such a common need and request.

I definitely don't think the Fishtown-maintained Postgres package is the right place for it—we haven't updated it in years, and we've never added it to [hub.getdbt.com](https://hub.getdbt.com/). At the same time, there is a hub package maintained by @sgoley, [`postgres_utils`](https://hub.getdbt.com/sgoley/postgres_utils/latest/), which for now includes `index` and `uindex` macros but with [eventual plans of much more](https://trello.com/b/jG0KfNzl/dbt-postgres-utils).

I believe that package was spurred to creation by the proposal of custom Postgres types (https://github.com/fishtown-analytics/dbt/issues/2619)—for which, since it could be accomplished via a simple DDL statement wrapped in a Jinja macro, I didn't want the dbt contribution/release/etc process to be an obstacle. In retrospect, I don't know if that was the right call; I'm going to own that and clean the slate.

We _know_ that indexing is used by so many `dbt-postgres` users. I'm be in favor of adding:
1. `index` as an [adapter config](https://github.com/fishtown-analytics/dbt/blob/6c6649f9129d5d108aa3b0526f634cd8f3a9d1ed/plugins/postgres/dbt/adapters/postgres/impl.py#L17)
2. A `create_index` macro [here](https://github.com/fishtown-analytics/dbt/blob/develop/plugins/postgres/dbt/include/postgres/macros/adapters.sql) that prepares the appropriate DDL, including the finer points that @arzavj mentions above. (And maybe handles unique naming or `drop index if exists`, too? See [discourse](https://discourse.getdbt.com/t/issue-with-post-hooks-not-running-with-dbt-0-16-1/1235/6).)
3. An update to the [`table` materialization](https://github.com/fishtown-analytics/dbt/blob/develop/core/dbt/include/global_project/macros/materializations/table/table.sql) that executes `create_index` after `create_table_as`, before closing the transaction. Given that postgres uses the default `table` materialization, we'll need to think about how to do this in a way that doesn't affect other databases. A dispatched macro, whereby `default__create_index` noops? Appending it to the set of inside-transaction `post_hooks`?

@arzavj Is that code you'd be interested in contributing?

**Comment by arzavj** [comment]
@jtcohen6 yes that sounds good! I'll get my dev env set up and start working on this

**Comment by arzavj** [comment]
@jtcohen6 would love to get your thoughts on the first draft above

**Comment by sgoley** [comment]
> We _know_ that indexing is used by so many `dbt-postgres` users. I'm be in favor of adding:

@jtcohen6 such a synchronicity to find this issue / thread today as I've been trying to revive my package, find some time to work 
 on it, and make some initial overtures towards work in this area *exactly*. 

To make sure I understand the path forward correctly, you are putting forward these options: 

1) make indexes a first class citizen of the python adapter to postgres from dbt
2) add indexes to the dbt postgres adapter default macros
3) fold indexes into the table materialization script itself 

From my perspective, I was thinking path 2 was the best route forward here but I was starting to plan for the package to "override" the default `adapters.sql` for a database from a package. (That is possible correct?)

And then some of the things that I've run into in the testing of my package are the necessity of:
- create or replace if not exists (otherwise indexes will be full re-built during every run including incremental runs)
- index types (since postgres supports multiple and even further extends that with index extensions like [trigram](https://www.postgresql.org/docs/9.6/pgtrgm.html)

Just some thoughts!

**Comment by jtcohen6** [comment]
Glad to have you here, @sgoley!

The three things I listed weren't mutually exclusive options, but rather (in my view) the three necessary ingredients of a solid implementation:
1. Adding `index` as an adapter config enables users to set this config from `dbt_project.yml` as well as in-file `config()` files.
2. Wrapping the necessary PostgreSQL in a Jinja macro, for modularity/accessibility/cleanliness.
3. If the `index` config is specified on a model, the Postgres materializations should take notice. Good callout of incremental models—we'll want to create the index for new and full-refresh runs, but not incremental models. We could accomplish that via `if not exists`, or `should_full_refresh()`, or (ideally) both.

@arzavj Thanks for taking the plunge here! I'll check out #3106 momentarily, and would invite others to do the same. The more eyes on that code, the merrier.
