### ISSUE TITLE
Bump google-cloud-bigquery version to 1.3.0

### ISSUE THREAD

**Issue by max-sixty** [fishtown-analytics/dbt#806]
This is currently at `0.29.0`. The latest is `1.1.0`, and `0.29.0` doesn't support some features that are required with recent versions of `pandas-gbq`

**Comment by drewbanin** [comment]
Thanks @maxim-lian -- those Google engineers... they work quick :). Looks like the latest release is [1.3.0](https://google-cloud-python.readthedocs.io/en/latest/bigquery/changelog.html)

Summary of changes from 0.29.0 to 0.1.3.0:
*0.30.0*:
- Add `delete_contents` to `delete_dataset`

*0.32.0*:
- Use job.configuration resource for XXXJobConfig classes

*1.0.0*
- Remove deprecated Client methods

*1.2.0*:
- Add column based time partitioning

*1.3.0*:
- Add client.load_table_from_dataframe()

...

I think the `job.configuration` change in 0.32.0 might require a code change, but otherwise, I think there are a lot of nice new features here that we can take advantage of. We'll definitely to check out which methods were removed in `1.0.0` as well.

**Comment by maxim-lian** [comment]
Thanks @drewbanin !

A few other dependencies that are out of date (a couple really out of date):

```
dbt 0.10.1 has requirement celery==3.1.23, but you'll have celery 4.2.0 which is incompatible.
dbt 0.10.1 has requirement google-cloud-bigquery==0.29.0, but you'll have google-cloud-bigquery 0.30.0 which is incompatible.
dbt 0.10.1 has requirement networkx==1.11, but you'll have networkx 2.1 which is incompatible.
dbt 0.10.1 has requirement pytz==2017.2, but you'll have pytz 2018.4 which is incompatible.
```

**Comment by vaughnkoch** [comment]
+1 for fixing the pytz and other requirements. In particular, some Singer taps don't support pytz=2017.2.

**Comment by cmcarthur** [comment]
should we use client.load_table_from_dataframe() for seed?
