### ISSUE TITLE
add compiled sql to manifest

### ISSUE THREAD

**Issue by drewbanin** [fishtown-analytics/dbt#829]
The `manifest.json` file should contain compiled SQL for every node. This will be used for rendering documentation for a dbt project.

**Comment by cmcarthur** [comment]
add any sql that we have to the manifest

**Comment by beckjake** [comment]
Ignoring the metadata for the moment (that looks easy since we have the project config), here's the current code layout. Things can get a bit confusing as we use the name 'compile' a lot:

 - `dbt.runner.RunManager.run_from_graph()` ends up getting called
 - which calls `dbt.runner.RunManager.compile()`
 - which calls `dbt.compilation.Compiler.compile()`.
 - which is the only place that has access to the manifest, and it throws it away after writing the manifest to disk (which currently happens even pre-linking).

The node compilation that generates the actual `compiled_sql` value has a different chain:
 - we start at `dbt.runner.RunManager.run_from_graph()` again
 - which calls `dbt.runner.RunManager.execute_nodes()`
 - which calls, via a thread pool, `dbt.runner.RunManager.call_runner()`
 - which calls `runner.safe_run()` (which _should_ always be `dbt.node_runners.BaseRunner.safe_run()`)
 - which calls `self.compile()` (which should always be `dbt.node_runners.CompileRunner.compile()` in this case)
 - which calls `dbt.node_runners.CompileRunner._compile_node()`, which does the actual jinja rendering (this nuance is important as `_compile_node()` has multiple entry points)

So the place that we'd have to do this is in `run_from_graph()`, but a lot has to change - we have to pass the manifest back up the stack from `Compiler.compile()`, and then pass it down all the way through the node runners.

My intuition is this is the way to go:
 1) Change `Compiler.compile()` and its callers to return the manifest as well.
 2) Store the manifest as an attribute on the `RunManager`. This is not elegant or anything, but at least it doesn't have to be a new parameter on all the RunManager method (`call_runner` is potentially extra-annoying due to threading and having to stuff multiple references into the `args_list`)
 3) pass the manifest into the runner as an argument (ugh). Runners that don't compile will need some thought here.
 4) (ab)use the fact that Python dicts are thread-safe for storage to just live-update the nodes in the manifest with the compiled SQL. Alternatively we could invent a new manifest type here + new node types (`CompiledManifest`/`CompiledNode`?) but I am not sure how much that buys us, it's basically the same issues.
 5) Move writing out the manifest to `RunManager.run_from_graph`. The various threads have been updating the manifest along the way, so we can just move `dbt.compilation.Compiler.write_manifest_file` into the RunManager or something.

One big downside: this will fall apart pretty horribly if we ever were to switch from threading to multiprocessing, which seems very limiting. Also this will probably break many tests due to new method signatures, but that's to be expected.

**Comment by drewbanin** [comment]
@beckjake thanks for the detailed writeup! I agree - no part of this sounds pleasant. What I was picturing was a much simpler implementation in which we effectively just call the code in the `CompileTask`, then inspect the compiled results to pluck out the `compiled_sql`.

I think that, for example, the `results` var [here](https://github.com/fishtown-analytics/dbt/blob/development/dbt/task/compile.py#L25) should contain a list of all of the nodes in the graph, and they should all have `compiled_sql` attributes. I totally recognize that at this point, we _already need to have created_ the manifest based on the current flow of things.

I wonder if it makes sense to invent a new `CompiledManifest`, created by merging a ParsedManifest and the output of `runner.run(query, CompileRunner)`. I don't want to do something totally hacky here - we can ship docs without the compiled code if we need to - but I did want to suggest an alternative way of approaching this problem.

More broadly, we're eventually going to want to record the output from dbt invocations so that we can surface information like test failures, model build times, etc, in the docs. It could be that trying to force this `compiled_sql` attribute into the manifest is the wrong idea, and we're actually better suited to tackle the question of serializing "run results" instead.

cc @cmcarthur

**Comment by cmcarthur** [comment]
> serializing "run results" instead

This is a really interesting way of reframing the problem. The manifest is supposed to be a representation of the project with no understanding of the warehouse, but incorporating compiled SQL kind of breaks that abstraction. And, in all of these cases, we have the compiled SQL right there in the target directory. We could always just serve it up from the filesystem

**Comment by beckjake** [comment]
Lots of great questions here!

I think passing the ParsedManifest along as we go, and updating it with CompiledNodes (and more, seeds for instance end up with their own situation that is neither a ParsedNode nor a CompiledNode), is the cleanest way we'll get things. If we do it right, at any point in the run we can serialize the current manifest and write it to disk. One example that comes to mind is on a failure, you will be able to get `compiled_sql` for the failing node in your manifest, which seems pretty awesome to me.

Regarding multiprocessing, sometimes for cross platform stuff like dbt you end up having to use processes because of the subtle differences in how threads behave across platforms - processes are a bit more of a level playing field. If you need to be able to kill background tasks cleanly no matter what, threads aren't viable either. Hopefully we can avoid those as threads are much more pleasant in the happy path at least. In the past I've rolled my own on top of python's standard library - if your data is pickle-able, it's not that hard of a problem, it just introduces some design constraints.

And we are actually going to be effectively serializing the run results in this new model, because [this](https://github.com/fishtown-analytics/dbt/blob/development/dbt/runner.py#L81) is where we probably have to get our compiled node to put into the manifest (`result.node` is the result of `CompileRunner.compile()`)
